#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/bare-entity-ref-scan.ts

// Pure scanner for the turn-end bare-entity-ref detector (mt#3286).
//
// Split from the guard shell deliberately: everything here is a string ->
// findings function with no fs, no clock, no env. The shell
// (`turn-end-bare-ref-scan.ts`) does the IO. That is the functional-core /
// imperative-shell split ADR-036 prescribes, and it is what lets the
// must-not-flag cases below be covered by fixtures rather than by patching.
//
// WHAT IS FLAGGED (v0, advisory only — never blocking):
//   1. bare-ref        — `mt#N` / `PR #N` present with no minsky:// link for
//                        that entity anywhere in the SAME message.
//   2. malformed-target— a minsky://ask|memory|session link whose id segment
//                        is not a full 36-char UUID (ADR-029: the UUID is the
//                        sole deeplink target). Deterministically wrong, so no
//                        calibration gate applies.
//   3. raw-uuid-label  — a minsky:// link whose LABEL is a raw UUID fragment
//                        wearing a short-id prefix (`ask#…86ac1dbe`). A real
//                        short id is `#` followed by decimal digits only, so
//                        this is wrong by construction too.
//
// WHAT IS LOGGED BUT NOT FLAGGED (v0): bare `ask#N` / `mem#N` / `ws#N`. The
// deeplink rule legitimately permits a bare short id when the UUID is not in
// hand, and this scanner cannot know whether it was. mt#3286's R6 argues the
// carve-out should be narrowed for decision-handing closing messages; that is
// a recorded recommendation, NOT an accepted criterion, and is deliberately
// not implemented here.
//
// @see .minsky/hooks/turn-end-bare-ref-scan.ts — the guard shell
// @see docs/architecture/adr-029-* — full UUID as the sole deeplink target
// @see mem#623 — the linked-reference-actionability family (R1-R6)

import { elideMarkdownContexts } from "./pre-narration-detector";

/** A full 36-char canonical UUID, the only legal ask/memory/session target. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * `decodeURIComponent` that returns null instead of throwing.
 *
 * This scanner runs inside a Stop hook over arbitrary assistant prose, so its
 * input includes half-written and hand-typed links. `decodeURIComponent`
 * throws a URIError on malformed percent-encoding (`%2`, a bare `%`), and an
 * uncaught throw here would take down the whole scan for the turn.
 */
function safeDecode(value: string): string | null {
  try {
    return decodeURIComponent(value);
  } catch {
    // intentional-swallow: a link whose id cannot be decoded simply does not
    // register as linking an entity; the caller degrades to treating the ref
    // as unlinked, which is the conservative direction for an advisory.
    return null;
  }
}

/** Entity classes whose deeplink target is DERIVABLE from the visible label. */
export type FlaggedKind = "bare-ref" | "malformed-target" | "raw-uuid-label";

export interface ScanFinding {
  kind: FlaggedKind | "bare-short-id";
  /** The reference as it appeared, e.g. "mt#3286" or "minsky://ask/fa4b942e". */
  ref: string;
  /** One-line reason, rendered into the advisory. */
  reason: string;
}

export interface ScanResult {
  /** Findings that produce advisory text (v0 enforced classes). */
  flagged: ScanFinding[];
  /** Findings recorded for calibration only — never rendered. */
  logged: ScanFinding[];
}

/**
 * Collect every `minsky://<type>/<id>` target present in the text, plus the
 * label each one carries. Operates on already-elided text so a link inside a
 * fenced block or a quoted spec excerpt is invisible here by construction.
 */
function collectLinks(elided: string): Array<{ label: string; type: string; id: string }> {
  const links: Array<{ label: string; type: string; id: string }> = [];
  const linkRe = /\[([^\]]*)\]\(minsky:\/\/([a-z]+)\/([^)\s]+)\)/gi;
  let m: RegExpExecArray | null;
  while ((m = linkRe.exec(elided)) !== null) {
    links.push({ label: m[1] ?? "", type: (m[2] ?? "").toLowerCase(), id: m[3] ?? "" });
  }
  return links;
}

/**
 * Scan one assistant message for deeplink defects.
 *
 * `text` is the raw message; elision happens here so every caller inherits the
 * must-not-flag behavior for code fences, inline spans and blockquotes rather
 * than having to remember it.
 */
export function scanMessage(text: string): ScanResult {
  const elided = elideMarkdownContexts(text);
  const links = collectLinks(elided);
  const flagged: ScanFinding[] = [];
  const logged: ScanFinding[] = [];

  // --- class 2: malformed ask/memory/session targets (ADR-029) -------------
  for (const link of links) {
    if (link.type !== "ask" && link.type !== "memory" && link.type !== "session") continue;
    if (!UUID_RE.test(link.id)) {
      flagged.push({
        kind: "malformed-target",
        ref: `minsky://${link.type}/${link.id}`,
        reason: `target is not a full 36-char UUID — ADR-029 makes the UUID the sole ${link.type} deeplink target`,
      });
    }
  }

  // --- class 3: raw-UUID-fragment labels -----------------------------------
  // A legitimate short-id label is `ask#6984` — `#` then DECIMAL digits only.
  // A label whose tail is a hex run (with or without a leading elision marker)
  // is a UUID fragment dressed as a short id, which defeats the label's whole
  // purpose.
  //
  // The decimal case is tested FIRST and returns, rather than being caught by
  // an exemption after a broader pattern already matched (PR #2717 R1). A
  // pattern whose correctness depends on a later `continue` is one edit away
  // from silently over-flagging every large short id.
  for (const link of links) {
    const label = link.label.trim();
    const tail = /^(?:ask|mem|ws)#(.+)$/i.exec(label)?.[1];
    if (tail === undefined) continue;
    // Legitimate short id — any length.
    if (/^\d+$/.test(tail)) continue;
    // A UUID fragment, optionally preceded by an elision marker. Anything else
    // (a name, a word, an unrecognized shape) is left alone: this class only
    // claims the defect it can prove.
    if (!/^[.…]*[0-9a-f]{6,}$/i.test(tail)) continue;
    flagged.push({
      kind: "raw-uuid-label",
      ref: label,
      reason:
        "link label is a raw UUID fragment — use the short id (e.g. ask#6984) so the reader is not reading a UUID",
    });
  }

  // --- class 1: bare mt#N / PR #N ------------------------------------------
  const linkedTaskIds = new Set<string>();
  const linkedChangesetIds = new Set<string>();
  for (const link of links) {
    if (link.type === "task") {
      // Targets are percent-encoded: mt%233286 -> mt#3286.
      //
      // GUARDED (PR #2717 R1): decodeURIComponent THROWS on malformed
      // percent-encoding (`mt%2`, a lone `%`), and this runs inside a Stop
      // hook over arbitrary assistant prose — a message containing a
      // half-written link would take the whole scan down. A link we cannot
      // decode simply does not count as linking anything, which degrades to
      // "the ref looks bare" rather than to a crash.
      const decoded = safeDecode(link.id);
      if (decoded === null) continue;
      const num = /^mt#(\d+)$/i.exec(decoded)?.[1];
      if (num) linkedTaskIds.add(num);
    } else if (link.type === "changeset") {
      if (/^\d+$/.test(link.id)) linkedChangesetIds.add(link.id);
    }
  }

  const seenTask = new Set<string>();
  for (const m of elided.matchAll(/\bmt#(\d+)\b/gi)) {
    const num = m[1];
    if (!num || seenTask.has(num)) continue;
    seenTask.add(num);
    if (!linkedTaskIds.has(num)) {
      flagged.push({
        kind: "bare-ref",
        ref: `mt#${num}`,
        reason: "no minsky://task link for this task in this message",
      });
    }
  }

  const seenPr = new Set<string>();
  // `PR #123` only — a bare `#123`, or the phrase "PR #" used generally about
  // GitHub, carries no id and must not fire.
  for (const m of elided.matchAll(/\bPR #(\d+)\b/g)) {
    const num = m[1];
    if (!num || seenPr.has(num)) continue;
    seenPr.add(num);
    if (!linkedChangesetIds.has(num)) {
      flagged.push({
        kind: "bare-ref",
        ref: `PR #${num}`,
        reason: "no minsky://changeset link for this PR in this message",
      });
    }
  }

  // --- log-only: bare ask#N / mem#N / ws#N ---------------------------------
  const linkedShortIdTypes = new Set(links.map((l) => l.type));
  const seenShort = new Set<string>();
  for (const m of elided.matchAll(/\b(ask|mem|ws)#(\d+)\b/gi)) {
    const whole = m[0];
    const kind = (m[1] ?? "").toLowerCase();
    if (seenShort.has(whole)) continue;
    seenShort.add(whole);
    // If the message carries ANY link of the corresponding entity type, this
    // mention may well be the label of that link; the v0 carve-out means we
    // record either way and never flag, so precision here costs nothing.
    const entityType = kind === "ask" ? "ask" : kind === "mem" ? "memory" : "session";
    logged.push({
      kind: "bare-short-id",
      ref: whole,
      reason: linkedShortIdTypes.has(entityType)
        ? "bare short id in a message that does link this entity type (possible link-decay)"
        : "bare short id with no link of this entity type in the message",
    });
  }

  return { flagged, logged };
}
