#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/calibration-review-cadence-detector.ts

// UserPromptSubmit hook: warn when a hook-calibration JSONL log has crossed its
// review threshold (or has sat unreviewed for too long) so a calibration
// review cannot silently lapse again (mt#2619).
//
// Why this exists. `.minsky/calibration-review-watermarks.json` showed exactly
// ONE calibration review had ever occurred (retrospective-trigger, watermark
// stuck at count=12 since 2026-06-13) despite THREE detectors sitting
// permanently gated at INJECTION_ENABLED=false past their own documented
// "review after ~10 fires" thresholds (ask-routing-deferral: 43 fires;
// code-mechanism-assertion: 52 fires), and a fourth log
// (policy-coverage-calibration.jsonl) growing to 973KB / 1,457 lines with zero
// reviews. The `/calibration-review` skill and the
// `mcp__minsky__observability_calibration-review` command already do the
// mechanical sweep — but nothing PROMPTS an agent to run them. This is the
// same class of gap `skill-staleness-detector.ts` closed for stale
// skill/agent/rule files (mt#1622): the fix that exists is discoverable only
// if someone remembers to look for it.
//
// Two independent review-due conditions (mirrors calibration-sweep.ts's
// pure logic exactly, plus a time-based extension):
//   1. pastThreshold (existing count+diversity-aware bar from
//      calibration-sweep.ts): fires-since-last-review >= FIRES_THRESHOLD (10)
//      AND distinctPhrases >= DIVERSITY_THRESHOLD (3).
//   2. time-stale: the log HAS been reviewed before (a watermark exists), has
//      >= 1 new fire since that review, AND the review is >= STALE_DAYS_MS
//      old. This closes the exact gap that let retrospective-trigger sit
//      forgotten for 3+ weeks: 8 new fires since 2026-06-13 never crossed the
//      10-fire count bar, so the mechanical sweep alone would never flag it.
//
// Re-warning is suppressed via a small persisted last-warned state file
// (mirrors the skill-staleness-detector.ts `lastReported` pattern) so this
// doesn't nag every single turn once a log is due — only when the fire count
// grows further, or a cooldown period has elapsed while still unreviewed.
//
// mt#2659 — ask-aware suppression + policy-coverage time-based re-warn.
// Two follow-on gaps surfaced on 2026-07-07: (1) the policy-coverage log
// fires once per TOOL CALL, so an orchestration session's own activity
// re-crosses FIRES_THRESHOLD every few turns — the fire-count-growth re-warn
// trigger effectively nags every turn for that log class. Fixed by making
// `shouldReWarn` time-only (cooldown-gated, no fire-count trigger) for
// `kind: "policy-coverage"` logs. (2) re-running /calibration-review while
// the PRIOR disposition ask (flip/tune/keep) is still open just reproduces
// the same pending question — the nag demands work that is blocked on the
// operator. Fixed by checking the watermark's `openAskId` (written by the
// /calibration-review skill's Step 5): while it's set, this hook shows a
// single "disposition pending on ask <id>" line at most once per
// `session_id`, instead of the full per-turn warning.
//
// INFORMATIONAL ONLY: always exits 0, never blocks the prompt (fail-open).
//
// Override: MINSKY_SKIP_CALIBRATION_CADENCE=1|true|yes skips the hook with an
// audit-log line to stdout.
//
// @see mt#2619 — this hook (Track-1 item of the mt#2607 tech-debt burndown).
// @see mt#2659 — ask-aware suppression + policy-coverage time-based re-warn
//      (this comment block and the code it documents).
//      The mt#2619 task spec documents two constraints discovered during
//      implementation: the mt#2304 hooks-compile-pipeline PR collision
//      (blocks detector .ts edits — INJECTION_ENABLED flips/pattern tuning
//      are recorded as dispositions, not code changes, in this PR) and the
//      live-registry chicken-and-egg (a newly-registered log's watermark
//      can't be `--ack`'d until the live MCP server has this PR's code).
// @see ask 483dbcb0-788a-4159-9d8a-ba718ba1f2b0 — the FP-classification +
//      flip/tune/retire disposition recommendations for the four
//      past-threshold logs found by this task's review pass.
// @see .claude/hooks/skill-staleness-detector.ts — architectural template
//      (re-warning suppression, per-turn UserPromptSubmit injection)
// @see .claude/hooks/inject-prod-state.ts — sibling cache-staleness framing
// @see src/domain/calibration/calibration-sweep.ts — the pure sweep logic
//      this hook reuses (CALIBRATION_LOG_REGISTRY, runSweep, computeLogResult)
// @see .claude/skills/calibration-review/SKILL.md — the skill this hook
//      points the agent at when a log is review-due

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { readInput, writeOutput, findRepoRoot } from "./types";
import type { ClaudeHookInput, HookOutput } from "./types";
import { ensureHookDomainBootstrap } from "./domain-bootstrap";
import {
  CALIBRATION_LOG_REGISTRY,
  runSweep,
  computeReviewDueLogs,
  STALE_DAYS_MS,
  NEVER_REVIEWED_DAYS,
  type CalibrationLogEntry,
  type WatermarkStore,
  type ReviewDueLog,
} from "../../src/domain/calibration/calibration-sweep";
import type { DispatchContext, GuardOutcome } from "./registry";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export const OVERRIDE_ENV_VAR = "MINSKY_SKIP_CALIBRATION_CADENCE";

const WATERMARK_STORE_PATH = ".minsky/calibration-review-watermarks.json";
const LAST_WARNED_STORE_PATH = ".minsky/calibration-review-cadence-last-warned.json";

/**
 * Re-warning cooldown: once a log is flagged review-due and the operator has
 * NOT acted (no new watermark advance), re-remind every COOLDOWN_MS even
 * without a fire-count change — so the warning doesn't evaporate into a
 * single easily-missed turn. 3 days matches the CLAUDE.md
 * `decision-defaults.mdc §Thresholds` calibration-window family (5-day budget
 * windows, 24h burst-detection) scaled down slightly since this is a repeat
 * nag rather than a single escalation.
 */
export const COOLDOWN_MS = 3 * 24 * 60 * 60 * 1000;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UserPromptSubmitInput extends ClaudeHookInput {
  prompt: string;
}

/** Per-log last-warned record, keyed by log path. */
export interface LastWarnedRecord {
  lastWarnedAt: string;
  lastWarnedFireCount: number;
  /**
   * `session_id` that last received the "disposition pending on ask <id>"
   * line for this log (mt#2659). Compared against the current turn's
   * `session_id` to enforce "at most once per session" independent of the
   * normal cooldown/fire-count re-warn logic.
   */
  pendingAskWarnedSessionId?: string;
}
export type LastWarnedStore = Record<string, LastWarnedRecord>;

/**
 * Log kinds whose fire count grows per TOOL CALL rather than per matched
 * pattern (mt#2659). For these, raw fire-count growth is not a meaningful
 * re-warn signal — an active session's own activity re-crosses
 * FIRES_THRESHOLD every few turns, defeating the cooldown entirely. Only
 * `policy-coverage` (mt#1575) fits this shape today; the set is a Set (not a
 * single string) so a future per-tool-call-volume log can be added without
 * touching `shouldReWarn`'s call site.
 */
const PER_TOOL_CALL_VOLUME_KINDS: ReadonlySet<CalibrationLogEntry["kind"]> = new Set([
  "policy-coverage",
]);

/**
 * Should this due log be (re-)warned about this turn? True when never
 * warned before, when new fires have arrived since the last warning (for
 * ordinary detector-log kinds — see `PER_TOOL_CALL_VOLUME_KINDS` for the
 * mt#2659 exception), or when the cooldown has elapsed while still
 * unaddressed.
 *
 * NOTE: this function does NOT consult `due.openAskId` — that check happens
 * one layer up in `main()` (via `selectPendingAskLogs`), which routes
 * openAskId logs to the "disposition pending" line instead of ever reaching
 * this function.
 */
export function shouldReWarn(
  due: ReviewDueLog,
  lastWarned: LastWarnedStore,
  nowMs: number,
  cooldownMs: number = COOLDOWN_MS
): boolean {
  const prior = lastWarned[due.path];
  if (!prior) return true;
  const fireGrowthTriggers = !PER_TOOL_CALL_VOLUME_KINDS.has(due.kind);
  if (fireGrowthTriggers && due.totalFires > prior.lastWarnedFireCount) return true;
  const warnedMs = Date.parse(prior.lastWarnedAt);
  if (Number.isNaN(warnedMs)) return true;
  return nowMs - warnedMs >= cooldownMs;
}

/**
 * Split `due` logs that carry an open disposition ask (`openAskId` set) from
 * those that don't have already been shown their pending-line this
 * `session_id` (mt#2659).
 *
 * Returns the SUBSET of openAskId-bearing logs that should show the
 * "disposition pending" line THIS turn — i.e. `openAskId` is set AND no
 * prior turn in this same session already showed it (tracked via
 * `pendingAskWarnedSessionId`). A log with `openAskId` set whose pending
 * line was already shown this session is fully suppressed (no line at all,
 * not even a repeat) until either the session changes or the ask resolves.
 */
export function selectPendingAskLogs(
  due: ReviewDueLog[],
  lastWarned: LastWarnedStore,
  sessionId: string
): ReviewDueLog[] {
  return due.filter((d) => {
    if (!d.openAskId) return false;
    return lastWarned[d.path]?.pendingAskWarnedSessionId !== sessionId;
  });
}

/**
 * Build the `LastWarnedRecord` to persist when showing the "disposition
 * pending" line for a log this turn (mt#2659 review fix, non-blocking b).
 *
 * Deliberately does NOT bump `lastWarnedFireCount` to the log's current
 * `totalFires` — the pending line is not a full warning, and stamping the
 * (possibly much higher) current count as the new baseline would raise the
 * fire-growth bar `shouldReWarn` checks against once the ask resolves and
 * `openAskId` is cleared, silently absorbing fires that accrued while the ask
 * was pending — and therefore never actually reviewed — into that bar.
 * `lastWarnedFireCount` instead carries forward from whatever the last REAL
 * warning recorded (0 if this log has never been warned about before), so
 * normal cadence resumes correctly post-resolution.
 */
export function buildPendingAskRecord(
  priorRecord: LastWarnedRecord | undefined,
  sessionId: string,
  nowIso: string
): LastWarnedRecord {
  return {
    lastWarnedAt: nowIso,
    lastWarnedFireCount: priorRecord?.lastWarnedFireCount ?? 0,
    pendingAskWarnedSessionId: sessionId,
  };
}

/** Build the additionalContext warning message for a set of due logs. */
export function formatCadenceWarning(due: ReviewDueLog[]): string {
  const lines: string[] = [
    "[calibration-review-cadence-detector] Calibration log(s) are review-due (mt#2619):",
    "",
  ];
  for (const d of due) {
    const reasonLabel =
      d.reason === "past-threshold"
        ? "past review threshold (fires + diversity)"
        : d.reason === "never-reviewed"
          ? `never reviewed; first fire >= ${d.reviewByDays ?? NEVER_REVIEWED_DAYS} days ago`
          : d.reason === "never-fired"
            ? `confirmed alive (live synthetic test) but ZERO real fires >= ${d.reviewByDays ?? NEVER_REVIEWED_DAYS} days since — check whether the trigger is rare or the detector has silently broken (mt#3078)`
            : `unreviewed for >= ${Math.floor(STALE_DAYS_MS / (24 * 60 * 60 * 1000))} days`;
    lines.push(
      // mt#3197: quote the INJECTED count — the detections that actually
      // reached the operator. The positional count includes suppressed ones,
      // which made a correctly-tuned detector look like a review backlog.
      `  - ${d.name}: ${d.injectedFiresSinceLastReview} new fire(s) since last review ` +
        `${
          d.suppressedSinceLastReview > 0
            ? `(+${d.suppressedSinceLastReview} suppressed, not counted) `
            : ""
        }(${d.totalFires} total, ${d.distinctPhrases} distinct) — ${reasonLabel}`
    );
  }
  lines.push("");
  lines.push(
    "Run the /calibration-review skill (or " +
      "mcp__minsky__observability_calibration-review) to classify false " +
      "positives and record a flip/tune/keep disposition before this drifts " +
      "further out of review."
  );
  lines.push(`Override: ${OVERRIDE_ENV_VAR}=1 suppresses this warning.`);
  return lines.join("\n");
}

/**
 * What a lookup of one `openAskId` established.
 *
 * `unavailable` is deliberately distinct from `not-found`: this detector reached no
 * persistence layer at all before mt#3270, so the lookup added here crosses the
 * hook-bootstrap boundary that silently killed two hooks (mt#3019, mt#3046). Collapsing an
 * unreachable store into "unknown ask" would make a dead lookup render exactly like a healthy
 * one that found nothing — the failure shape this detector's own bug already had.
 */
export type AskLookup =
  | { kind: "open"; state: string; shortId?: string }
  | { kind: "settled"; state: string; shortId?: string }
  | { kind: "not-found" }
  | { kind: "unavailable"; reason: string };

/** Ask states in which the operator genuinely still owes a response. */
const OPEN_ASK_STATES = new Set(["routed", "suspended"]);

/**
 * Resolve the state of each referenced ask.
 *
 * Only called when at least one pending log exists, so the ordinary turn — where nothing is
 * past threshold — pays no database cost at all. Every failure resolves to `unavailable` with
 * the reason attached rather than throwing: a cadence reminder must never break the turn.
 */
export async function resolveAskStates(askIds: string[]): Promise<Map<string, AskLookup>> {
  const out = new Map<string, AskLookup>();
  if (askIds.length === 0) return out;

  const unavailable = (reason: string): Map<string, AskLookup> => {
    process.stderr.write(
      `[calibration-review-cadence-detector] ask lookup unavailable: ${reason}\n`
    );
    for (const id of askIds) out.set(id, { kind: "unavailable", reason });
    return out;
  };

  try {
    const bootstrap = await ensureHookDomainBootstrap();
    if (!bootstrap.ok) {
      return unavailable(bootstrap.error ?? "domain bootstrap failed");
    }

    const { resolvePersistenceProvider } = await import("@minsky/domain/persistence/factory");
    const provider = await resolvePersistenceProvider();
    if (!provider || !("getDatabaseConnection" in provider)) {
      return unavailable("no persistence provider with a database connection");
    }
    const db = await (
      provider as { getDatabaseConnection(): Promise<unknown> }
    ).getDatabaseConnection();

    // `@minsky/domain/ask/repository`, not the `/ask` barrel — the barrel is not an exported
    // subpath, and a wrong specifier here fails at RUNTIME inside a swallowed catch (the
    // mt#2760 shape). Every other call site in the repo uses this same path.
    const { DrizzleAskRepository } = await import("@minsky/domain/ask/repository");
    const repo = new DrizzleAskRepository(
      db as import("drizzle-orm/postgres-js").PostgresJsDatabase
    );

    for (const id of askIds) {
      try {
        const ask = await repo.getById(id);
        if (!ask) {
          out.set(id, { kind: "not-found" });
          continue;
        }
        out.set(id, {
          kind: OPEN_ASK_STATES.has(ask.state) ? "open" : "settled",
          state: ask.state,
          shortId: ask.shortId ?? undefined,
        });
      } catch (err) {
        // A per-id failure is still a lookup failure for THAT id — never silently "not found".
        out.set(id, {
          kind: "unavailable",
          reason: err instanceof Error ? err.message : String(err),
        });
      }
    }
    return out;
  } catch (err) {
    return unavailable(err instanceof Error ? err.message : String(err));
  }
}

/** `[label](minsky://ask/<uuid>)` per cockpit-deeplinks.mdc, so the id is openable from the line. */
function askDeeplink(askId: string, shortId?: string): string {
  return `[${shortId ?? askId.slice(0, 8)}](minsky://ask/${askId})`;
}

/**
 * Render one line per past-threshold log carrying an `openAskId`.
 *
 * Before mt#3270 every line read "awaiting operator response" without the ask's state ever
 * being consulted — so a closed, answered ask was reported as pending for days, and the
 * principal tried to action an ask that could no longer be opened. Each branch below now says
 * only what the lookup actually established.
 *
 * `lookups` is REQUIRED, deliberately. It briefly had a default of `new Map()`, and the CLI
 * entrypoint was then left un-updated — every line it rendered read "ask store unreachable (no
 * lookup performed)" (PR #2374 R1). A default turns "this call site forgot to resolve state"
 * into a wrong message at runtime; requiring the argument turns it into a compile error.
 */
export function formatPendingAskLines(
  pending: ReviewDueLog[],
  lookups: Map<string, AskLookup>
): string {
  const lookupFor = (d: ReviewDueLog): AskLookup =>
    lookups.get(d.openAskId as string) ?? { kind: "unavailable", reason: "no lookup performed" };

  // "no action needed" is only true when every referenced ask is genuinely still open.
  const allOpen = pending.every((d) => lookupFor(d).kind === "open");
  const header = allOpen
    ? "[calibration-review-cadence-detector] Calibration disposition pending — no action needed (mt#2659):"
    : "[calibration-review-cadence-detector] Calibration disposition status (mt#2659):";

  const lines: string[] = [header, ""];

  for (const d of pending) {
    const askId = d.openAskId as string;
    const lookup = lookupFor(d);
    const fires = `(${d.totalFires} total fires)`;

    switch (lookup.kind) {
      case "open":
        lines.push(
          `  - ${d.name}: disposition pending on ask ${askDeeplink(askId, lookup.shortId)} ` +
            `${fires} — awaiting operator response.`
        );
        break;
      case "settled":
        lines.push(
          `  - ${d.name}: prior ask ${askDeeplink(askId, lookup.shortId)} is ${lookup.state} ` +
            `${fires} — this log still needs a disposition; the ask is spent.`
        );
        break;
      case "not-found":
        lines.push(
          `  - ${d.name}: referenced ask ${askDeeplink(askId)} could not be found ` +
            `${fires} — disposition state unknown.`
        );
        break;
      case "unavailable":
        lines.push(
          `  - ${d.name}: could not read the state of ask ${askDeeplink(askId)} ` +
            `${fires} — ask store unreachable (${lookup.reason}); disposition state unknown.`
        );
        break;
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Filesystem helpers
// ---------------------------------------------------------------------------

function readJsonOrDefault<T>(path: string, fallback: T): T {
  try {
    if (!existsSync(path)) return fallback;
    return JSON.parse(readFileSync(path, "utf-8")) as T;
  } catch {
    return fallback;
  }
}

function writeLastWarnedStore(path: string, store: LastWarnedStore): void {
  try {
    const dir = dirname(path);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(path, `${JSON.stringify(store, null, 2)}\n`, "utf-8");
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(
      `[calibration-review-cadence-detector] failed to write last-warned store: ${msg}\n`
    );
  }
}

function isOverrideTruthy(value: string | undefined): boolean {
  if (!value) return false;
  const v = value.toLowerCase();
  return v === "1" || v === "true" || v === "yes";
}

// ---------------------------------------------------------------------------
// Dispatcher-compatible pure function (ADR-028 Phase 2b, mt#2687)
// ---------------------------------------------------------------------------

/**
 * Guard-dispatcher entry point. Mirrors `main()`'s orchestration but returns
 * a `GuardOutcome` instead of writing to stdout / calling `process.exit` —
 * the dispatcher owns stdout and aggregates every matched guard's output
 * (D1). Legacy bespoke override var (`MINSKY_SKIP_CALIBRATION_CADENCE`) is
 * still honored here, independent of the dispatcher's unified
 * `MINSKY_HOOK_OVERRIDE` check (D3). Side effects (`writeLastWarnedStore`)
 * are preserved exactly as `main()` performs them.
 */
export async function run(
  input: ClaudeHookInput,
  _ctx: DispatchContext
): Promise<GuardOutcome | null> {
  if (isOverrideTruthy(process.env[OVERRIDE_ENV_VAR])) {
    return {
      auditLines: [
        `[calibration-review-cadence-detector] override active: ${OVERRIDE_ENV_VAR}=${process.env[OVERRIDE_ENV_VAR]} at ${new Date().toISOString()}\n`,
      ],
    };
  }

  // mt#2710: `input.cwd` (or the `process.cwd()` fallback) is routinely a
  // repo SUBDIRECTORY, not the repo root — findRepoRoot walks up to the
  // nearest `.git` so the watermark/last-warned state files land in
  // `<repo>/.minsky/`, not a stray subdirectory `.minsky/`.
  const repoRoot = findRepoRoot(input.cwd ?? process.cwd());
  const watermarkPath = join(repoRoot, WATERMARK_STORE_PATH);
  const lastWarnedPath = join(repoRoot, LAST_WARNED_STORE_PATH);

  try {
    const watermarks = readJsonOrDefault<WatermarkStore>(watermarkPath, {});
    const readContent = async (relPath: string): Promise<string | null> => {
      try {
        return readFileSync(join(repoRoot, relPath), "utf-8");
      } catch {
        return null;
      }
    };
    const results = await runSweep(CALIBRATION_LOG_REGISTRY, readContent, watermarks);

    const now = Date.now();
    const due = computeReviewDueLogs(results, watermarks, now);
    if (due.length === 0) return null;

    const lastWarned = readJsonOrDefault<LastWarnedStore>(lastWarnedPath, {});

    const pendingCandidates = due.filter((d) => d.openAskId);
    const normalDue = due.filter((d) => !d.openAskId);

    const pendingToShow = selectPendingAskLogs(pendingCandidates, lastWarned, input.session_id);
    const normalToWarn = normalDue.filter((d) => shouldReWarn(d, lastWarned, now));

    if (pendingToShow.length === 0 && normalToWarn.length === 0) return null;

    const updated: LastWarnedStore = { ...lastWarned };
    const nowIso = new Date(now).toISOString();
    for (const d of pendingToShow) {
      updated[d.path] = buildPendingAskRecord(lastWarned[d.path], input.session_id, nowIso);
    }
    for (const d of normalToWarn) {
      updated[d.path] = { lastWarnedAt: nowIso, lastWarnedFireCount: d.totalFires };
    }
    writeLastWarnedStore(lastWarnedPath, updated);

    const parts: string[] = [];
    if (normalToWarn.length > 0) parts.push(formatCadenceWarning(normalToWarn));
    if (pendingToShow.length > 0) {
      // Gated on there being something to render: the ordinary turn resolves no asks and
      // therefore never touches the database.
      const askStates = await resolveAskStates([
        ...new Set(pendingToShow.map((d) => d.openAskId as string)),
      ]);
      parts.push(formatPendingAskLines(pendingToShow, askStates));
    }

    return { additionalContext: parts.join("\n\n") };
  } catch (err) {
    process.stderr.write(
      `[calibration-review-cadence-detector] error: ${err instanceof Error ? err.message : String(err)}\n`
    );
    return null;
  }
}

// ---------------------------------------------------------------------------
// Entrypoint
// ---------------------------------------------------------------------------

export async function main(): Promise<void> {
  if (isOverrideTruthy(process.env[OVERRIDE_ENV_VAR])) {
    process.stdout.write(
      `[calibration-review-cadence-detector] override active: ${OVERRIDE_ENV_VAR}=${process.env[OVERRIDE_ENV_VAR]} at ${new Date().toISOString()}\n`
    );
    process.exit(0);
  }

  let input: UserPromptSubmitInput;
  try {
    input = await readInput<UserPromptSubmitInput>();
  } catch {
    process.exit(0);
  }

  // mt#2710: `input.cwd` (or the `process.cwd()` fallback) is routinely a
  // repo SUBDIRECTORY, not the repo root — findRepoRoot walks up to the
  // nearest `.git` so the watermark/last-warned state files land in
  // `<repo>/.minsky/`, not a stray subdirectory `.minsky/`.
  const repoRoot = findRepoRoot(input.cwd ?? process.cwd());
  const watermarkPath = join(repoRoot, WATERMARK_STORE_PATH);
  const lastWarnedPath = join(repoRoot, LAST_WARNED_STORE_PATH);

  try {
    const watermarks = readJsonOrDefault<WatermarkStore>(watermarkPath, {});
    const readContent = async (relPath: string): Promise<string | null> => {
      try {
        return readFileSync(join(repoRoot, relPath), "utf-8");
      } catch {
        return null;
      }
    };
    const results = await runSweep(CALIBRATION_LOG_REGISTRY, readContent, watermarks);

    const now = Date.now();
    const due = computeReviewDueLogs(results, watermarks, now);
    if (due.length === 0) process.exit(0);

    const lastWarned = readJsonOrDefault<LastWarnedStore>(lastWarnedPath, {});

    // mt#2659: logs with a still-open disposition ask get the low-noise
    // pending line (at most once per session_id) instead of the normal
    // fire-count/cooldown-driven warning — they never reach `shouldReWarn`.
    const pendingCandidates = due.filter((d) => d.openAskId);
    const normalDue = due.filter((d) => !d.openAskId);

    const pendingToShow = selectPendingAskLogs(pendingCandidates, lastWarned, input.session_id);
    const normalToWarn = normalDue.filter((d) => shouldReWarn(d, lastWarned, now));

    if (pendingToShow.length === 0 && normalToWarn.length === 0) process.exit(0);

    const updated: LastWarnedStore = { ...lastWarned };
    const nowIso = new Date(now).toISOString();
    for (const d of pendingToShow) {
      updated[d.path] = buildPendingAskRecord(lastWarned[d.path], input.session_id, nowIso);
    }
    for (const d of normalToWarn) {
      updated[d.path] = {
        lastWarnedAt: nowIso,
        lastWarnedFireCount: d.totalFires,
      };
    }
    writeLastWarnedStore(lastWarnedPath, updated);

    const parts: string[] = [];
    if (normalToWarn.length > 0) parts.push(formatCadenceWarning(normalToWarn));
    if (pendingToShow.length > 0) {
      // Same lookup as the dispatcher path in `run()` — both entrypoints render the same
      // surface, so both must resolve state. Leaving this one unresolved made every CLI-path
      // line read "ask store unreachable (no lookup performed)" (PR #2374 R1 BLOCKING).
      const askStates = await resolveAskStates([
        ...new Set(pendingToShow.map((d) => d.openAskId as string)),
      ]);
      parts.push(formatPendingAskLines(pendingToShow, askStates));
    }

    const output: HookOutput = {
      hookSpecificOutput: {
        hookEventName: "UserPromptSubmit",
        additionalContext: parts.join("\n\n"),
      },
    };
    writeOutput(output);
  } catch (err) {
    process.stderr.write(
      `[calibration-review-cadence-detector] error: ${err instanceof Error ? err.message : String(err)}\n`
    );
    process.exit(0);
  }
}

if (import.meta.main) {
  await main();
}
