#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/canary-dispositions.ts

/**
 * Canary dispositions — the recorded ruling for every catalog entity that has no
 * canary (mt#5079, delivering mt#4606 SC2 and SC4).
 *
 * ## What this answers
 *
 * `coverageGaps: ["canary"]` says an entity has no canary. It does NOT say
 * whether that is a gap somebody owes or a deliberate exclusion, and until this
 * module existed the corpus could not tell those apart for 81 of 154 entities.
 * That undifferentiated majority is what made "the guards are working"
 * unfalsifiable for over half the corpus.
 *
 * ## Why the third value is DERIVED and not authored
 *
 * `canary-declared` is never written here. It is computed by
 * {@link resolveCanaryDisposition} from the absence of a canary gap, which is
 * itself computed from the two real declaration surfaces (`GuardRegistration.canary`
 * and `STANDALONE_GUARD_CANARIES`, joined by mt#5072). An authored
 * `canary-declared` would be a second source of truth for a fact the code
 * already knows, and it would go stale silently the moment a canary was removed
 * — which is precisely the class of drift this task exists to close, so
 * reintroducing it here would be self-defeating.
 *
 * ## Why this is its own module
 *
 * `interceptor-descriptions.ts` is the natural home by subject, and it is
 * already 1690 lines — past the 1500-line error ceiling in `CLAUDE.md §Code
 * Style`. It also holds the "dependency-free leaf" property
 * (`known-guard-names.ts`'s convention), so it may not import this data. The
 * TYPES therefore live there and the DATA lives here, importing them; the
 * builder in `scripts/` reads this module and passes the maps in as DATA,
 * exactly as mt#5072 does for `standaloneCanaryNames`. That keeps
 * `.minsky/hooks/**` from importing `scripts/**` (mt#4010 §Data-access
 * decision) and keeps the leaf a leaf.
 *
 * ## Governing decision record
 *
 * RFC "The evaluation loop — auditing the regulators" (Accepted 2026-07-08,
 * Notion `392937f0-3cb4-8188-aad6-d7d041de814b`). It scopes the canary to a
 * CONDITIONAL diagnostic over an INSTRUMENTED guard — "a guard with zero fires
 * over a rolling window gets its canary run" — where mt#4606 SC2 requires an
 * unconditional ruling for every gapped entity. That is a deliberate EXTENSION,
 * justified by the RFC's own Position 4 ("the ambiguity must be resolvable"),
 * which cannot hold for an entity nobody has ever ruled on.
 *
 * @see .minsky/hooks/interceptor-descriptions.ts — the types and the resolver
 * @see scripts/build-interceptor-catalog.ts — reads this and passes it as data
 * @see docs/architecture/evaluation-loop-fire-log.md — the prior art for the
 *   infeasible-with-a-reason shape; three of the reasons below are ITS reasons,
 *   reused rather than re-derived
 * @see mt#5080 — owns declaring the canaries every `canary-pending` entry names
 * @see mt#5081 — owns fire-log-instrumenting the 29 entities with no fire-log
 */

import type { CanaryDispositionRecord, Stratum } from "./interceptor-descriptions";

/** The task that owns declaring the canaries this module records as pending. */
const CANARY_DECLARATION_OWNER = "mt#5080";

/** Terse constructor for the common case: owed, owned by mt#5080. */
function pending(note?: string): CanaryDispositionRecord {
  return note === undefined
    ? { disposition: "canary-pending", owner: CANARY_DECLARATION_OWNER }
    : { disposition: "canary-pending", owner: CANARY_DECLARATION_OWNER, reason: note };
}

function infeasible(reason: string): CanaryDispositionRecord {
  return { disposition: "canary-infeasible", reason };
}

/**
 * Stratum-level rulings (mt#4606 SC4).
 *
 * SC4 asked for the pre-commit stratum to get ONE ruling rather than 27
 * individual `pending` markers; the same argument applies to the fixture and
 * retired strata, so all three are ruled here. Together they cover 35 of the 81
 * gapped entities. A per-entity entry in {@link CANARY_DISPOSITIONS} overrides
 * its stratum's ruling — the stratum is a default, not a ceiling.
 *
 * The `standalone` and `registry` strata deliberately have NO ruling: every
 * member is ruled individually, so a newly added standalone guard fails the
 * census gate instead of silently inheriting a verdict nobody made about it.
 * That is the whole point of the gate (mt#4606 AT2), and a stratum-wide
 * `pending` there would defeat it.
 */
export const STRATUM_CANARY_DISPOSITIONS: ReadonlyMap<Stratum, CanaryDispositionRecord> = new Map([
  [
    "precommit" as Stratum,
    infeasible(
      "Pre-commit steps are stages of the single `src/hooks/pre-commit.ts` pipeline, invoked by " +
        "git on every commit rather than as independently-addressable entrypoints, so there is no " +
        "per-step surface for a synthetic input to enter. More decisively, the ambiguity a canary " +
        "resolves does not arise for this stratum: all 27 members carry fire-log evidence " +
        "(measured 2026-09-10), and the governing RFC scopes the canary to a guard with ZERO " +
        "fires over a rolling window. A canary here would answer a question the fire-log already " +
        "answers continuously."
    ),
  ],
  [
    "fixture" as Stratum,
    infeasible(
      "Dispatcher test fixtures (`denier`, `first-guard`, `second-guard`, `overridden-guard`, " +
        "`mt3612-live-rewrite`), not production interceptors. A canary over a fixture verifies the " +
        "test harness rather than any enforcement the operator relies on, and the fixtures are " +
        "already exercised directly by `dispatcher.test.ts`."
    ),
  ],
  [
    "retired" as Stratum,
    infeasible(
      "Retired entities kept in the catalog so historical fire-log and canary rows still resolve " +
        "to a name. There is no live mechanism to exercise. `policy-coverage` was retired by " +
        "mt#4197 and its `guard_canary_runs` rows predate that; `unit-tests` and " +
        "`migration-guard-and-duplicate-content-check` were superseded by successor steps."
    ),
  ],
]);

/**
 * Per-entity rulings for the `standalone` and `registry` strata.
 *
 * Ordered `canary-infeasible` first (the rulings that close a gap permanently),
 * then `canary-pending` (the gaps mt#5080 owes), each group alphabetical.
 */
export const CANARY_DISPOSITIONS: ReadonlyMap<string, CanaryDispositionRecord> = new Map([
  // ---------------------------------------------------------------------------
  // canary-infeasible — a synthetic invocation cannot exercise these
  // ---------------------------------------------------------------------------

  [
    "check-branch-fresh",
    infeasible(
      "Its real evaluation has side effects a synthetic invocation cannot safely trigger: a live " +
        "`git fetch`, an actual `git merge` on the blocked-plus-clean-tree auto-merge path " +
        "(mt#2815), and a CAS-marker write on allow. Reason carried over verbatim from " +
        "`docs/architecture/evaluation-loop-fire-log.md`, which already documents it as " +
        "fire-log-only."
    ),
  ],
  [
    "dispatch-pretooluse",
    infeasible(
      "A dispatcher entry point, not a guard. It routes to the registered guards and records " +
        "their fire-log rows under the ROUTED guard's name (`dispatcher.ts:1089`), so a canary " +
        "keyed to this name would assert on a name nothing ever writes. The routing itself is " +
        "what the 73 passing canaries exercise on every run."
    ),
  ],
  [
    "dispatch-stop",
    infeasible(
      "Dispatcher entry point for the Stop event — same reason as `dispatch-pretooluse`: it " +
        "records under the routed guard's name, never its own."
    ),
  ],
  [
    "dispatch-userpromptsubmit",
    infeasible(
      "Dispatcher entry point for UserPromptSubmit — same reason as `dispatch-pretooluse`. Note " +
        "mt#3531 reports this entry point's own e2e canaries failing on main; that is a defect in " +
        "an EXISTING end-to-end canary, not evidence that a per-name canary is feasible here."
    ),
  ],
  [
    "linkify-message-display",
    infeasible(
      "Writes no fire-log record by design per ADR-028 D1/D7(5), stated in its own docblock at " +
        "`.minsky/hooks/linkify-message-display.ts:67`; it keeps a separate " +
        "`linkify-fire-log.jsonl`. Its contract is a rewritten message rather than a decision, so " +
        "there is no allow/deny/inject outcome for `expects` to assert."
    ),
  ],
  [
    "loop-preflight-pr-merge-check",
    infeasible(
      "Narrow trigger — it fires only inside a `/loop` preflight on a merge call, a context a " +
        "synthetic input cannot reconstruct without standing up the loop harness. Reason carried " +
        "over from `docs/architecture/evaluation-loop-fire-log.md`."
    ),
  ],
  [
    "parallel-work-guard",
    infeasible(
      "Its `tasks_create` duplicate-child path (`runTasksCreateGuardInner`) resolves its decision " +
        "via an internal `switch` with no return value bubbled to the call site, so there is no " +
        "injectable decision function to call. Attributing an outcome would require restructuring " +
        "that void return into a decision-returning one — a larger change than a canary " +
        "declaration. Reason carried over from `docs/architecture/evaluation-loop-fire-log.md`. " +
        "Note its embedding-backed sibling `standalone-duplicate-matcher` " +
        "(`parallel-work-guard-standalone.ts`) IS separately instrumented and is ruled pending."
    ),
  ],
  [
    "rationalization-review",
    infeasible(
      "Not an interceptor: a corpus NAME for the RFC's periodic rationalization-review pass, " +
        "carried in `known-guard-names.ts` with `deliberatelyUnauthored: true`, no interception " +
        "point, no role and no implementing module. There is nothing to invoke."
    ),
  ],

  [
    "typecheck-on-stop",
    infeasible(
      "Ruled by mt#5080 rather than extracted. The module is top-level script code with no " +
        "`import.meta.main` guard, so importing it runs `main()` against stdin; and its decision " +
        "is the one-line predicate `failedRoots.length > 0` over results that only a state-file " +
        "read plus a `tsgo --noEmit` subprocess per touched root can produce. A pure extraction " +
        "of that predicate would pass while every failure mode this hook actually has — binary " +
        "resolution, the state file, the subprocess — stayed unexercised, and a canary that drives " +
        "the subprocess is outside the declaration convention (mt#5080 SC2: no subprocess spawn). " +
        "Same class as `check-branch-fresh`: the real evaluation IS the side effect."
    ),
  ],

  // ---------------------------------------------------------------------------
  // canary-pending — owed, owned by mt#5080
  // ---------------------------------------------------------------------------

  ["bridge-memory-retirement", pending()],
  ["deploy-verification-after-merge", pending()],
  ["drive-pr-to-convergence", pending()],
  ["guard-events-ingest-on-session-end", pending()],
  ["inject-success-criteria", pending()],
  ["post-merge-pull", pending()],
  ["post-merge-unasked-direction-scan", pending()],
  ["post-session-start", pending()],
  [
    "record-conversation-run-state",
    pending("Fires on PostCompact, which a canary must simulate rather than observe."),
  ],
  ["record-subagent-invocation", pending()],
  [
    "record-turn-anchor",
    pending(
      "One of the two entities in `scripts/run-guard-canaries.ts`'s own MISSING set — it holds a " +
        "`GuardRegistration` with no `canary`, so the registry canary path applies directly and " +
        "no extraction is needed."
    ),
  ],
  [
    "retrospective-completeness-detector",
    pending(
      "The other entity in the runner's MISSING set — registered with no `canary`, so the " +
        "registry canary path applies directly."
    ),
  ],
  ["session-start", pending()],
  ["stamp-ask-conversation", pending()],
  ["stamp-pr-author-link", pending()],
  ["stamp-session-creator-link", pending()],
  [
    "standalone-duplicate-matcher",
    pending(
      'Embedding-backed (`mechanism: "embedding"`), so a canary needs a fixture corpus with ' +
        "stable vectors rather than a single synthetic payload. Feasible, but a different shape " +
        "from the structural guards — and mem#819 records that this matcher cannot discriminate " +
        "at the distances real duplicates sit at, which is a tuning question a canary would not " +
        "settle either way."
    ),
  ],
  ["transcript-ingest-on-session-end", pending()],
  ["two-strikes-record", pending()],
  ["typecheck-on-edit", pending()],
  ["unowned-finding-scan", pending()],
  [
    "verify-subagent-model",
    pending(
      "Records to its own flat state file rather than the guard fire-log, so its shipping state " +
        "is currently checkable only through that file; a canary is the instrument that would " +
        "make it checkable from outside."
    ),
  ],
  ["warn-main-workspace-mutation", pending()],
  ["warn-peer-task-activity", pending()],
  ["warn-stale-forward-reference", pending()],
]);

// ---------------------------------------------------------------------------
// Fire-log instrumentation — the OTHER axis (mt#5081, mt#4606 amendment 3)
// ---------------------------------------------------------------------------
//
// A canary asks "does this guard still DECIDE correctly?" and presupposes a
// fire-log to go quiet in. 29 standalone entities have no fire-log at all
// (measured 2026-09-10: zero `guard_events` rows, and none of the three
// instrumentation paths in their source). This map records, per entity, the
// ruling mt#5081 made — the same shape as the canary ruling above, kept beside
// it as mt#4606 SC2 asked, and for the same reason: an unruled gap and a
// ruled-out gap must not look alike.
//
// The RFC's Position 3 is "every ENFORCEMENT point should write a fire-log."
// A recorder, a stamper, a session-lifecycle hook or a dispatcher ENTRY POINT is
// not an enforcement point — it performs an effect rather than a decision — so
// those are ruled `not-an-enforcement-point` with the reason, and the 14 judges
// and feeders are `instrumented` by mt#5081 through the direct call.

/** How, or why not, an entity reaches the guard fire-log. */
export type FireLogInstrumentation =
  | {
      readonly status: "instrumented";
      /** Which of the three paths carries its rows. */
      readonly path: "direct" | "merge-gate-wrapper" | "dispatcher-routed";
      /** The task that added it. */
      readonly task: string;
    }
  | {
      readonly status: "not-an-enforcement-point";
      readonly reason: string;
    };

const INSTRUMENTED_BY_5081: FireLogInstrumentation = {
  status: "instrumented",
  path: "direct",
  task: "mt#5081",
};

/** The two multi-exit PreToolUse guards reuse the merge-gate family's recorder. */
const INSTRUMENTED_BY_5081_VIA_WRAPPER: FireLogInstrumentation = {
  status: "instrumented",
  path: "merge-gate-wrapper",
  task: "mt#5081",
};

function notEnforcement(reason: string): FireLogInstrumentation {
  return { status: "not-an-enforcement-point", reason };
}

const DISPATCHER_ENTRY_POINT =
  "A dispatcher entry point, not a guard. It routes to the registered guards and records " +
  "each one's fire-log row under the ROUTED guard's name (`dispatcher.ts:1089`); a row " +
  "under its own name would double-count every evaluation it already records.";

const RECORDER =
  "A recorder: it writes a stamp, a link or an ingest row and decides nothing. There is " +
  "no allow/warn/deny to attribute, and the row it writes is itself the evidence it ran.";

/**
 * The 29 entities with no fire-log as of 2026-09-10, each ruled. Keys are the
 * measured population, not a derivation — a new silent guard is caught by the
 * catalog census and `scripts/check-coverage-receipts.ts`, not by this map.
 */
export const FIRE_LOG_INSTRUMENTATION: ReadonlyMap<string, FireLogInstrumentation> = new Map([
  // -- instrumented by mt#5081: judges and feeders, all through the direct call --
  ["ask-permission-bridge", INSTRUMENTED_BY_5081],
  ["block-github-mcp-pr-writes", INSTRUMENTED_BY_5081],
  ["bridge-memory-retirement", INSTRUMENTED_BY_5081],
  ["check-prompt-watermark", INSTRUMENTED_BY_5081],
  ["deploy-verification-after-merge", INSTRUMENTED_BY_5081],
  ["drive-pr-to-convergence", INSTRUMENTED_BY_5081],
  ["inject-success-criteria", INSTRUMENTED_BY_5081],
  ["loop-preflight-pr-merge-check", INSTRUMENTED_BY_5081_VIA_WRAPPER],
  ["parallel-work-guard", INSTRUMENTED_BY_5081_VIA_WRAPPER],
  ["post-merge-unasked-direction-scan", INSTRUMENTED_BY_5081],
  ["two-strikes-record", INSTRUMENTED_BY_5081],
  ["typecheck-on-stop", INSTRUMENTED_BY_5081],
  ["unowned-finding-scan", INSTRUMENTED_BY_5081],
  ["verify-subagent-model", INSTRUMENTED_BY_5081],

  // -- not enforcement points: silent by design, with the reason --
  ["dispatch-pretooluse", notEnforcement(DISPATCHER_ENTRY_POINT)],
  ["dispatch-stop", notEnforcement(DISPATCHER_ENTRY_POINT)],
  ["dispatch-userpromptsubmit", notEnforcement(DISPATCHER_ENTRY_POINT)],
  [
    "linkify-message-display",
    notEnforcement(
      "Off the guard dispatcher by ADR-028 D1/D7(5) and states in its own docblock " +
        "(`linkify-message-display.ts:67`) that it writes no fire-log record; it keeps its own " +
        "`linkify-fire-log.jsonl`. Its contract is a rewritten message, not a decision."
    ),
  ],
  ["guard-events-ingest-on-session-end", notEnforcement(RECORDER)],
  ["post-merge-pull", notEnforcement(RECORDER)],
  ["post-session-start", notEnforcement(RECORDER)],
  ["record-conversation-run-state", notEnforcement(RECORDER)],
  ["record-subagent-invocation", notEnforcement(RECORDER)],
  ["session-start", notEnforcement(RECORDER)],
  ["stamp-ask-conversation", notEnforcement(RECORDER)],
  ["stamp-pr-author-link", notEnforcement(RECORDER)],
  ["stamp-session-creator-link", notEnforcement(RECORDER)],
  ["transcript-ingest-on-session-end", notEnforcement(RECORDER)],
  [
    "typecheck-on-edit",
    notEnforcement(
      "Runs the typechecker after an edit and injects the result as context; it records a " +
        "state file for `typecheck-on-stop`, which is the guard that DECIDES on it — and that " +
        "one is instrumented above."
    ),
  ],
]);
