#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/chained-verification-commands-detector.ts

/**
 * Chained-verification-commands detector (mt#3910).
 *
 * `terminal-command-best-practices.mdc §Verification Commands` bans chaining two or more
 * verification commands in one invocation: you lose which one failed. That rule has shipped
 * TWICE at prose tier (mt#2371, widened by mt#2571) and its class recurred anyway — most
 * recently on 2026-08-10, when `bun run format:all …; echo …; bun test …` returned exit 1 with
 * empty stdout and both commands, run separately, passed. The failure signal was an artifact of
 * the chaining.
 *
 * The rule was in always-on context and had been read. That is the signature of a prose control:
 * it depends on recall at the instant of composing a command, which is exactly when attention is
 * on the outcome instead. This detector moves the check to where the violation is visible — the
 * command string, before it runs.
 *
 * ## Deliberately narrow
 *
 * Fires ONLY when two or more recognized VERIFICATION commands are chained. It does NOT fire on:
 *
 *   - a single verification command wrapped in `echo` labels or a `cd` prefix
 *     (`echo '=== tests ==='; bun test …`) — the dominant benign shape, and by far the most
 *     common in real transcripts;
 *   - chained exploratory commands (`grep …; grep …`), where losing an individual exit code
 *     costs nothing.
 *
 * A detector that fired on those would produce exactly the unmatchable noise mem#719 records as
 * eroding trust in a detector's true positives. The narrow trigger is the design, not a v1
 * limitation.
 *
 * ## Not governed by ADR-024
 *
 * ADR-024's ladder scopes itself to `UserPromptSubmit` guidance hooks matching behavioral trigger
 * phrases in the agent's own prose. Neither of its axes applies here: there is no quotation case
 * to elide (a command is not prose) and no paraphrase to recall-widen (`bun test` is `bun test`).
 * Calibration-first shipping follows the repo-wide observer convention in `hook-observers.mdc`,
 * not that ADR. Recorded in mt#3910 `## ADR check`.
 */

import { CANARY_MODE_ENV } from "./types";
import type { ToolHookInput } from "./types";
import type { DispatchContext, GuardOutcome } from "./registry";
import { leadingCommandOf, splitPipeline, splitTopLevel } from "./command-shape";

// These three were defined here first (mt#3910) and moved to `./command-shape`
// (mt#3533) when the operator-deferral detector needed the same quote-aware
// splitting to compare a denied command's shape against a retry's. Re-exported
// so this module's public surface — and its tests, which import them from here —
// are unchanged.
export { leadingCommandOf, splitPipeline, splitTopLevel };

export const OVERRIDE_ENV = "MINSKY_SKIP_CHAINED_VERIFICATION_SCAN";

/**
 * Commands whose PASS/FAIL is the point of running them. Chaining two of these is what makes an
 * exit code ambiguous.
 *
 * `format` is included in both its `:check` and `:all` forms: `format:all` writes, but it also
 * runs `lint:fix` and exits non-zero on violations, so its status is load-bearing — and it was
 * one of the two commands in the originating incident.
 *
 * Goes stale when a new verification script is added to `package.json` without being listed here.
 * The failure mode is a MISS (no fire), never a false fire, so staleness degrades recall only.
 * To refresh: compare against `package.json`'s scripts block.
 *
 * `bun run build` is deliberately EXCLUDED (PR #2765 R1), despite being listed in this task's
 * original spec. A build is a PREREQUISITE, not an independent check: `bun run build && bun test`
 * expresses ordering — build, then test the artifact — and the `&&` is load-bearing sequencing
 * rather than two results the author needs to tell apart. Firing there would flag a correct
 * idiom. The distinguishing question for anything added here is not "can it fail?" (a build
 * certainly can) but "is its pass/fail the REASON it was run, independent of the command beside
 * it?". `bunx tsc` stays because a typecheck is run to learn its verdict; a build is run to get
 * an artifact.
 */
const VERIFICATION_PATTERNS: readonly RegExp[] = [
  /^bun\s+test\b/,
  /^bun\s+run\s+test/,
  /^bun\s+run\s+lint/,
  /^bun\s+run\s+format/,
  /^bun\s+run\s+typecheck/,
  /^bun\s+run\s+validate/,
  /^bunx\s+eslint\b/,
  /^bunx\s+tsc\b/,
  /^tsgo\b/,
];

/** How many chained verification commands constitute the violation. */
const CHAIN_THRESHOLD = 2;

export function isOverridden(): boolean {
  return process.env[OVERRIDE_ENV] === "1";
}

/** Whether a segment runs a command whose pass/fail is the reason for running it. */
export function isVerificationCommand(segment: string): boolean {
  const leading = leadingCommandOf(segment);
  return VERIFICATION_PATTERNS.some((pattern) => pattern.test(leading));
}

export interface ChainScanResult {
  segmentCount: number;
  verificationSegments: string[];
  chained: boolean;
}

/** The whole decision, as a pure function over the command string. */
export function scanCommand(command: string): ChainScanResult {
  const segments = splitTopLevel(command);
  const verificationSegments = segments.filter(isVerificationCommand).map(leadingCommandOf);
  return {
    segmentCount: segments.length,
    verificationSegments,
    chained: verificationSegments.length >= CHAIN_THRESHOLD,
  };
}

/**
 * Cap on how many chained commands the advisory names. Without it the message grows one
 * backticked entry per command, which makes the rendered size unbounded and the registry's
 * `attentionCost` claim unprovable. Naming the first few is sufficient — the reader needs to
 * recognize the shape, not read an inventory.
 */
const MAX_LISTED_COMMANDS = 5;

function buildWarning(result: ChainScanResult): string {
  const shown = result.verificationSegments.slice(0, MAX_LISTED_COMMANDS);
  const overflow = result.verificationSegments.length - shown.length;
  const listed =
    shown.map((c) => `\`${c}\``).join(", ") + (overflow > 0 ? `, +${overflow} more` : "");
  return (
    `This call chains ${result.verificationSegments.length} verification commands (${listed}) ` +
    `in one invocation. A non-zero exit cannot be attributed to either one, and a ` +
    `piped/truncated run can report failure with no output at all — which is how mt#3910's ` +
    `originating incident produced \`exitCode 1\` with empty stdout while BOTH commands were ` +
    `passing. Run them as separate calls and read each result. ` +
    `(terminal-command-best-practices.mdc §Verification Commands)`
  );
}

export async function run(
  input: ToolHookInput,
  _ctx: DispatchContext
): Promise<GuardOutcome | null> {
  if (isOverridden()) return null;

  const toolInput = input.tool_input ?? {};
  const command = typeof toolInput["command"] === "string" ? (toolInput["command"] as string) : "";
  if (!command) return null;

  const result = scanCommand(command);

  const base = {
    ts: new Date().toISOString(),
    sessionId: input.session_id ?? null,
    toolName: input.tool_name ?? null,
    segmentCount: result.segmentCount,
    verificationCommands: result.verificationSegments,
    // The diversity axis for the calibration sweep is the SHAPE of the violation — the set of
    // chained command heads — not the full command string. A raw command is near-unique, which
    // would satisfy the sweep's distinct-phrase gate by construction and render it inert
    // (the mt#3781 defect).
    phrase: result.verificationSegments.join(" + "),
  };

  // Canary isolation: the scan is pure over its input, so it runs identically in canary mode.
  // Recorded explicitly so a future reader does not add a DB dependency and silently change that.
  if (process.env[CANARY_MODE_ENV] === "1" && !result.chained) {
    return { calibration: { ...base, outcome: "clean" } };
  }

  if (!result.chained) {
    return { calibration: { ...base, outcome: "clean" } };
  }

  return {
    additionalContext: buildWarning(result),
    calibration: { ...base, outcome: "matched" },
  };
}
