#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/dispatch-intent-write-gate.ts

// PreToolUse hook: deny session-mutating / PR-mutating tool calls from a
// subagent whose dispatched session carries a LIVE `"read-only"`
// dispatch-intent declaration (mt#2865).
//
// ## Why this exists
//
// mt#2828 (2026-07-16): an implementer dispatched a `fork` subagent with a
// narrow, bounded, read-only instruction ("search memory for
// reviewer-empty-findings context, report back under 300 words"). The fork
// inherited the FULL conversation context and, primed by that inherited
// implementation context, wrote code, committed to the shared session
// workspace, and edited the shared PR's title/body/author AFTER the
// primary implementer had already finalized it — including writing a false
// test-count claim into the PR body. Confirmed at the transcript level
// (mt#2865 spec, "Incident reconstruction"): even the harness's own
// fork-boilerplate prompt ("you are NOT a continuation... execute ONE
// directive, then stop... do NOT spawn subagents") did not hold. Prompt-
// level containment is not sufficient once a fork carries a full
// implementation context — this guard is the structural (tool-level)
// backstop.
//
// ## Policy
//
// - **Default (no declaration): allow.** This guard only ever adds a NEW
//   denial on top of the default-allow state every session-mutating tool
//   already has — it is not a capability gate like the sibling D5 merge
//   guard. A subagent with no declared intent (the ordinary implementer
//   dispatch case) is completely unaffected — this is the regression
//   acceptance test (mt#2865 SC "a legitimate implementer subagent with
//   implementation intent is NOT impeded").
// - **Deny when:** `agent_id` is present (subagent context — mirrors
//   `block-subagent-merge-without-grant.ts`'s `isSubagentContext`) AND a
//   live (not expired), unexpired `"read-only"` dispatch-intent declaration
//   covers the CALL'S TARGET SESSION (not the calling agent_id — the
//   incident fork's `agent_id` differed from its parent's, but both
//   operated against the SAME session workspace, which is the shared
//   resource this guard protects).
// - **Main-thread calls are unaffected.** When `agent_id` is absent, this
//   guard is a no-op.
//
// ## Session-id resolution (self-contained, no DB lookup)
//
// Prefers `tool_input.sessionId` (the direct param most of these tools
// accept). Falls back to parsing `input.cwd` against
// `check-guessed-session-path.ts`'s `SESSION_DIR_RE` — a subagent operating
// "in a session" has a cwd that IS the session workspace directory
// (`.../state/minsky/sessions/<sessionId>`), so this is a reliable,
// dependency-free resolution path that doesn't require a session-service
// DB lookup (which would violate the hooks tree's self-containment
// invariant — see `.claude/hooks/SPEC.md`). An unresolvable session id is
// treated as "no declaration can match" (allow), NOT as a reason to deny —
// this guard's default state is allow, unlike the D5 merge guard's
// default-deny.
//
// ## Fail-open posture
//
// Fail-open is reserved for GENUINE ERRORS reading the dispatch-intent
// store (file unreadable for reasons other than "doesn't exist yet",
// malformed JSON). A CONFIRMED "no declarations" state (store absent, or
// present but no matching entry) is NOT a fail-open case — it is this
// guard's ordinary default-allow path.
//
// ## Fork containment caveat (mt#2865 SC #4 — documented upstream limitation)
//
// This guard contains a fork's WRITES to the shared session/PR substrate —
// it does not, and structurally cannot, stop a fork from THINKING like an
// implementer (that is a harness context-scoping capability Minsky does
// not control; see mt#2512/mt#2521). The gate is only load-bearing when the
// orchestrator actually calls the dispatch-time issuance surface
// (`session.generate_prompt` with `intent: "read-only"`) BEFORE forking —
// which is exactly what the paired guidance change
// (`.minsky/rules/subagent-routing.mdc`) now instructs for bounded
// lookups. A fork dispatched via the harness's native mechanism, with no
// Minsky-side intent declaration ever issued for its session, is NOT
// covered by this guard — see `docs/architecture/hooks/
// dispatch-intent-write-gate.md` "Known limitations".
//
// ## Override
//
// No override env var. The declaration itself IS the escape valve — if a
// dispatch genuinely needs write access after being declared read-only,
// the orchestrator issues a fresh `intent: "implementation"` declaration
// (or lets the TTL expire) rather than bypassing the gate. This mirrors
// the guard-grant-store family's "the declaration/grant record is the
// audit trail" design, but there is no legitimate "confirmed false
// positive" case here the way there is for the D5 merge guard (a read-only
// declaration existing at all means SOMEONE explicitly asked for the
// write-bound to apply) — the denial message names the sanctioned
// alternative (report findings back; the parent decides) instead.
//
// @see mt#2865 — this guard's tracking task
// @see mt#2828 — the originating incident
// @see .minsky/hooks/dispatch-intent-store.ts — declaration schema + matching logic
// @see .minsky/hooks/block-subagent-merge-without-grant.ts — structural template (D5)
// @see .minsky/hooks/check-guessed-session-path.ts — SESSION_DIR_RE, the cwd-resolution pattern this guard reuses
// @see .minsky/rules/hook-files.mdc "Dispatch-Intent Write Gate"
// @see docs/architecture/hooks/dispatch-intent-write-gate.md

import { readInput, writeOutput } from "./types";
import type { ToolHookInput } from "./types";
import {
  getDispatchIntentStorePath,
  readDispatchIntentStore,
  findLiveReadOnlyDeclaration,
} from "./dispatch-intent-store";
import type { DispatchIntentDeclaration } from "./dispatch-intent-store";
import { SESSION_DIR_RE } from "./check-guessed-session-path";

// ---------------------------------------------------------------------------
// Tool-name matcher (kept as an exported constant so the standalone
// settings.json registration and this guard's own matching logic can never
// drift apart — session_pr_merge is deliberately excluded: it already has
// its own default-deny D5 capability guard, block-subagent-merge-
// without-grant.ts)
// ---------------------------------------------------------------------------

export const GATED_TOOL_NAMES: ReadonlySet<string> = new Set([
  "mcp__minsky__session_commit",
  "mcp__minsky__session_edit_file",
  "mcp__minsky__session_write_file",
  "mcp__minsky__session_search_replace",
  "mcp__minsky__session_pr_create",
  "mcp__minsky__session_pr_edit",
]);

// ---------------------------------------------------------------------------
// Subagent context detection (identical shape to block-subagent-merge-
// without-grant.ts's isSubagentContext)
// ---------------------------------------------------------------------------

export function isSubagentContext(input: ToolHookInput): boolean {
  return typeof input.agent_id === "string" && input.agent_id.length > 0;
}

// ---------------------------------------------------------------------------
// Session-id resolution
// ---------------------------------------------------------------------------

/**
 * Clone `SESSION_DIR_RE` with its EXACT flags (`RegExp.prototype.flags`),
 * never a hardcoded literal — a fresh instance per call avoids shared
 * `lastIndex` state across invocations (the constant is `g`-flagged), while
 * deriving the flags from the source constant (rather than assuming `"g"`)
 * keeps this correct if that pattern's flags ever change. Exported so tests
 * can assert the clone tracks the source exactly (PR #2033 R1 BLOCKING #1).
 */
export function cloneSessionDirRegex(): RegExp {
  return new RegExp(SESSION_DIR_RE.source, SESSION_DIR_RE.flags);
}

/**
 * Best-effort, self-contained session-id resolution for the current tool
 * call. Prefers `tool_input.sessionId` (the direct param most of these
 * tools accept). Falls back to parsing `input.cwd` against the shared
 * `SESSION_DIR_RE` pattern — a subagent's cwd, when it is operating inside
 * a session workspace, literally IS the session directory
 * (`.../state/minsky/sessions/<sessionId>`).
 *
 * Returns `null` when neither source yields a resolvable session id — the
 * guard treats this as "no declaration can match" (allow), NOT as a read
 * error.
 */
export function resolveSessionIdFromInput(input: ToolHookInput): string | null {
  const fromToolInput = input.tool_input?.["sessionId"];
  if (typeof fromToolInput === "string" && fromToolInput.trim().length > 0) {
    return fromToolInput.trim();
  }

  const cwd = input.cwd;
  if (!cwd) return null;

  // Fresh regex per call to avoid shared lastIndex state across invocations
  // (SESSION_DIR_RE is a `g`-flagged module-level constant) — cloned with its
  // EXACT flags (not a hardcoded subset) via `cloneSessionDirRegex`, so this
  // stays correct if the source pattern's flags ever change (PR #2033 R1
  // BLOCKING #1: a prior version hardcoded `"g"` here, which happened to
  // match today's flags by coincidence but would silently drift from
  // SESSION_DIR_RE on any future flag change).
  const re = cloneSessionDirRegex();
  const match = re.exec(cwd);
  const sessionId = match?.[2];
  return sessionId && sessionId.trim().length > 0 ? sessionId.trim() : null;
}

// ---------------------------------------------------------------------------
// Denial message
// ---------------------------------------------------------------------------

export function buildDenialMessage(
  sessionId: string | null,
  declaration: DispatchIntentDeclaration
): string {
  const sessionRef = sessionId ?? "this session";
  const reasonPart = declaration.reason ? ` (declared reason: "${declaration.reason}")` : "";
  return (
    `Write denied (mt#2865 dispatch-intent gate): ${sessionRef} carries a live "read-only" ` +
    `dispatch-intent declaration${reasonPart}, issued ${declaration.issuedAt}. ` +
    "This dispatch was bound to read-only work (investigation, lookup, review) — it is not " +
    "authorized to commit, edit files, or mutate a PR in this session. Report your findings " +
    "back to the parent instead; the parent decides whether to act on them. If this dispatch " +
    'genuinely needs write access, the orchestrator must issue a fresh `intent: "implementation"` ' +
    "declaration via `session.generate_prompt` (or let the read-only declaration's TTL expire) " +
    "before retrying."
  );
}

// ---------------------------------------------------------------------------
// Core decision logic (pure, given already-read declarations — for testability)
// ---------------------------------------------------------------------------

export type DispatchIntentGateDecision =
  | { decision: "allow"; reason: string }
  | { decision: "deny"; reason: string };

/**
 * Pure decision function given the resolved session id, the declarations
 * already read from the store, and the current time. Exported so tests can
 * exercise the deny/allow/expired/wrong-session matrix without touching
 * the filesystem.
 */
export function decideDispatchIntentGate(
  sessionId: string | null,
  declarations: DispatchIntentDeclaration[],
  nowMs: number
): DispatchIntentGateDecision {
  const match = findLiveReadOnlyDeclaration(declarations, { sessionId }, nowMs);
  if (match) {
    return { decision: "deny", reason: buildDenialMessage(sessionId, match) };
  }
  return {
    decision: "allow",
    reason: `no live read-only declaration for session=${sessionId ?? "?"} — write permitted`,
  };
}

// ---------------------------------------------------------------------------
// Hook entry point
// ---------------------------------------------------------------------------

if (import.meta.main) {
  const input = await readInput<ToolHookInput>();

  if (!GATED_TOOL_NAMES.has(input.tool_name)) {
    process.exit(0);
  }

  if (!isSubagentContext(input)) {
    // Main-thread calls are unaffected by this guard.
    process.exit(0);
  }

  const sessionId = resolveSessionIdFromInput(input);

  const storeResult = readDispatchIntentStore(getDispatchIntentStorePath());
  if (storeResult.status === "error") {
    // Fail-open ONLY on genuine dispatch-intent-store read errors (corrupt
    // file, permission denied, etc.) — a broken store must not silently
    // deny every subagent write. This guard's ORDINARY default-allow path
    // (no declarations, or no matching one) is handled below via
    // decideDispatchIntentGate, not here.
    console.error(
      `[dispatch-intent-write-gate] warn: dispatch-intent store read error (${storeResult.message}) ` +
        "— failing open (allowing this call)."
    );
    process.exit(0);
  }

  const decision = decideDispatchIntentGate(sessionId, storeResult.declarations, Date.now());

  if (decision.decision === "allow") {
    process.exit(0);
  }

  writeOutput({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: decision.reason,
    },
  });
  process.exit(0);
}
