#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/inject-memory-capture.ts

// UserPromptSubmit hook: surface a resident-memory capture when one appears (mt#3997).
//
// Why this exists. mt#3973 shipped the capture: when an MCP or cockpit process
// crosses a resident-memory watermark it writes an artifact naming the tool
// calls in flight — the evidence mt#3885 (five whole-machine kernel panics in
// four days) has been unable to obtain. It writes that artifact to
// `~/.local/state/minsky/memory-captures/` and NOTHING READ IT. Verified by
// grep at filing time: the only references were the three writers, the module,
// the doc page, and the verify script reading its own temp dir.
//
// So the leak investigation was blocked on a signal that would land silently on
// disk. The capture fires at most once per process and the runaway is
// intermittent (nothing since 2026-08-08), which means the realistic outcome
// was that the first real capture is found weeks later, or never. Same failure
// class as `work-completion.mdc §Invocation path` — except the writer runs fine
// and the READER is what was never built.
//
// ## Why a hook notice and not an ask
//
// The obvious ADR-008 kind for "tell someone this happened" is
// `coordination.notify` — and it routes to `routingTarget: "peer"` over
// `transport: { kind: "mesh" }` (`packages/domain/src/ask/router.ts`), not to
// the operator. Filing a capture there would put the signal on a channel the
// principal does not read, recreating this hook's own bug one layer up.
//
// `severity: "incident"` would force operator+inbox, but
// `communication-contract.mdc` conditions that marker on remediation being
// OPERATOR-ONLY, and a capture's remediation ("investigate the named tool") is
// not — an agent does it. Borrowing a paging mechanism for a non-paging signal
// would also spend against its 3-per-24h ceiling.
//
// So: an injected notice, on the surface the principal actually works on, with
// the artifact's durability coming from the file already on disk. Known bound,
// stated rather than discovered later: this is Claude Code only, the same limit
// `cockpit-deeplinks.mdc` records for the display linkifier. Acceptable because
// the notice is a POINTER and the payload persists either way.
//
// Override: MINSKY_SKIP_MEMORY_CAPTURE_NOTICE=1 skips injection.
//
// @see mt#3997 — this hook
// @see mt#3973 — the producer (`src/mcp/memory-capture.ts`)
// @see mt#3885 — the leak this evidence chain serves
// @see docs/mcp-memory-forensics.md — artifact format + retrieval path

import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { CANARY_MODE_ENV, readInput, writeOutput } from "./types";
import type { ClaudeHookInput, HookOutput } from "./types";
import type { DispatchContext, GuardOutcome } from "./registry";

export const MEMORY_CAPTURE_NOTICE_OVERRIDE_ENV = "MINSKY_SKIP_MEMORY_CAPTURE_NOTICE";

/**
 * Most captures to describe in one notice.
 *
 * A notice is a pointer, not a report — and the realistic case is one artifact,
 * since each process captures at most once. The cap bounds the injected size if
 * a fleet-wide event ever produces many at once; the remainder is counted, not
 * dropped silently.
 */
export const MAX_DESCRIBED_CAPTURES = 3;

/** Most in-flight tool calls to name per capture. They are sorted longest-first. */
export const MAX_DESCRIBED_TOOL_CALLS = 3;

const BYTES_PER_MB = 1024 * 1024;

/** The subset of the mt#3973 artifact this notice reads. */
export interface CaptureRecord {
  capturedAt?: string;
  pid?: number;
  processRole?: string;
  residentBytes?: number;
  inFlightToolCalls?: Array<{ toolName?: string; elapsedMs?: number }>;
}

export interface SeenState {
  /** Artifact filenames already surfaced. */
  seen: string[];
}

function getStateDir(env: NodeJS.ProcessEnv = process.env): string {
  return env["MINSKY_STATE_DIR"] ?? path.join(os.homedir(), ".local", "state", "minsky");
}

export function getCaptureDir(env: NodeJS.ProcessEnv = process.env): string {
  return path.join(getStateDir(env), "memory-captures");
}

export function getSeenStatePath(env: NodeJS.ProcessEnv = process.env): string {
  return path.join(getStateDir(env), "memory-capture-notice-state.json");
}

/**
 * Which artifacts have not been surfaced yet.
 *
 * Keyed on filename rather than mtime: the filename already carries the capture
 * instant, the role and the pid (mt#3973 builds it that way), so it is unique
 * per capture and stable across a file being touched. An mtime watermark would
 * re-fire the whole directory if anything rewrote a file.
 */
export function selectNewCaptures(filenames: string[], seen: string[]): string[] {
  const seenSet = new Set(seen);
  return filenames
    .filter((name) => name.endsWith(".json") && !seenSet.has(name))
    .sort()
    .reverse();
}

function describeToolCalls(record: CaptureRecord): string {
  const calls = record.inFlightToolCalls ?? [];
  if (calls.length === 0) {
    // Not a non-answer: it rules out an in-flight tool call as the immediate
    // cause and points at retained state instead. Say so, or a reader will
    // treat the empty list as missing data.
    return "no tool call in flight (points at retained state, not a running call)";
  }
  const described = calls
    .slice(0, MAX_DESCRIBED_TOOL_CALLS)
    .map((call) => {
      const seconds = Math.round((call.elapsedMs ?? 0) / 1000);
      return `${call.toolName ?? "unknown"} (${seconds}s in)`;
    })
    .join(", ");
  const remainder = calls.length - MAX_DESCRIBED_TOOL_CALLS;
  return remainder > 0 ? `${described}, +${remainder} more` : described;
}

/**
 * Format the notice. Pure — takes the records, returns the text.
 *
 * Leads with the tool calls because that is the payload the whole chain exists
 * to deliver; the size and role are context for it.
 */
export function formatCaptureNotice(
  entries: Array<{ filename: string; record: CaptureRecord }>,
  captureDir: string
): string {
  const described = entries.slice(0, MAX_DESCRIBED_CAPTURES);
  const remainder = entries.length - described.length;

  const lines = described.map(({ record }) => {
    const mb = Math.round((record.residentBytes ?? 0) / BYTES_PER_MB);
    const role = record.processRole ?? "unknown process";
    return `- **${role}** at ${mb}MB (pid ${record.pid ?? "?"}) — ${describeToolCalls(record)}`;
  });

  const header =
    entries.length === 1
      ? "A resident-memory capture was written (mt#3973)."
      : `${entries.length} resident-memory captures were written (mt#3973).`;

  const footer = [
    `Artifacts: ${captureDir}`,
    "This is the evidence mt#3885 has been blocked on — the leak that kernel-panicked the machine.",
    "Read the artifact, then act on it: the named tool is the allocation-path lead.",
  ];

  return [
    header,
    ...lines,
    ...(remainder > 0 ? [`- +${remainder} more capture(s) not listed`] : []),
    ...footer,
  ].join("\n");
}

/**
 * Write the canary's synthetic capture, reusing this hook's own test fixture
 * shape rather than inventing one (per the registry's canary-input instruction).
 * Best-effort: a failure here degrades the canary to the silent path, which the
 * runner reports as a MISSING expectation — visible, not silent.
 */
function primeCanaryFixture(captureDir: string): void {
  try {
    fs.mkdirSync(captureDir, { recursive: true });
    fs.writeFileSync(
      path.join(
        captureDir,
        "memory-capture-2026-08-11T20-03-39-983Z-mcp-start-stdio-pid48013.json"
      ),
      JSON.stringify({
        capturedAt: "2026-08-11T20:03:39.983Z",
        pid: 48013,
        processRole: "mcp start (stdio)",
        residentBytes: 1500 * BYTES_PER_MB,
        inFlightToolCalls: [{ toolName: "transcripts_search-text", elapsedMs: 91_000 }],
      })
    );
  } catch (error) {
    // Intentionally not rethrown: the canary observing the silent path is a
    // reportable outcome; a canary that CRASHES the dispatcher is not.
    console.error(`[mt#3997] canary fixture priming failed: ${String(error)}`);
  }
}

/**
 * The filesystem this hook touches, behind a seam.
 *
 * Injected rather than called directly so the tests can exercise the real
 * read/format/watermark logic without a real filesystem — required by
 * `custom/no-real-fs-in-tests`, and the right shape anyway: the interesting
 * behavior here is WHICH artifacts are new and WHAT the notice says, neither of
 * which is about disk.
 */
export interface CaptureIo {
  /** Artifact filenames, or null when the directory does not exist. */
  listFilenames(dir: string): string[] | null;
  /** The parsed record, or null when it is absent or unparseable. */
  readRecord(dir: string, filename: string): CaptureRecord | null;
  readSeen(env: NodeJS.ProcessEnv): string[];
  writeSeen(env: NodeJS.ProcessEnv, seen: string[]): void;
}

export const realCaptureIo: CaptureIo = {
  listFilenames(dir) {
    try {
      return fs.readdirSync(dir);
    } catch {
      // No capture directory means no process has ever crossed a watermark —
      // the healthy state, and the one this hook sees on almost every machine.
      return null;
    }
  },
  readRecord(dir, filename) {
    try {
      return JSON.parse(fs.readFileSync(path.join(dir, filename), "utf-8")) as CaptureRecord;
    } catch {
      // Reported by the caller as an unreadable artifact rather than swallowed;
      // returning null keeps the decision about what to SAY in one place.
      return null;
    }
  },
  readSeen(env) {
    try {
      const parsed = JSON.parse(fs.readFileSync(getSeenStatePath(env), "utf-8")) as SeenState;
      return Array.isArray(parsed.seen) ? parsed.seen : [];
    } catch {
      // Absent or unreadable state is "nothing surfaced yet" — the correct
      // starting point. Not logged: a first run has no state file by
      // definition, so logging it would be noise on every fresh machine.
      return [];
    }
  },
  writeSeen(env, seen) {
    const statePath = getSeenStatePath(env);
    fs.mkdirSync(path.dirname(statePath), { recursive: true });
    fs.writeFileSync(statePath, `${JSON.stringify({ seen } satisfies SeenState, null, 2)}\n`);
  },
};

/**
 * Read new captures and mark them surfaced. Returns null when there is nothing
 * to say, which is the overwhelmingly common case — this hook runs every turn.
 */
export function collectNewCaptureNotice(
  env: NodeJS.ProcessEnv = process.env,
  io: CaptureIo = realCaptureIo
): string | null {
  if (env[MEMORY_CAPTURE_NOTICE_OVERRIDE_ENV] === "1") return null;

  const captureDir = getCaptureDir(env);

  // Canary mode primes a synthetic capture so the canary exercises the FIRING
  // path — read, format, watermark — rather than the silent one. A canary that
  // can only observe silence cannot tell a broken guard from a dormant one,
  // which is the blindness the mechanism exists to remove (mt#2889). Safe
  // because `scripts/run-guard-canaries.ts` points MINSKY_STATE_DIR at a fresh
  // temp dir before importing anything, so this never touches real state.
  if (env[CANARY_MODE_ENV] === "1") {
    primeCanaryFixture(captureDir);
  }

  const filenames = io.listFilenames(captureDir);
  if (filenames === null) return null;

  const seen = io.readSeen(env);
  const fresh = selectNewCaptures(filenames, seen);
  if (fresh.length === 0) return null;

  const entries = fresh.map((filename) => {
    const record = io.readRecord(captureDir, filename);
    // A partially-written or corrupt artifact must not suppress the others,
    // and must not re-fire every turn forever — so it is named here and still
    // marked seen below.
    return { filename, record: record ?? { processRole: `unreadable artifact ${filename}` } };
  });

  // Mark surfaced BEFORE returning: SC3 requires the same artifact not
  // re-notify on a later turn, and a write that happened after a failed
  // injection would be worse than one that happened before a successful one.
  io.writeSeen(env, [...seen, ...fresh]);

  return formatCaptureNotice(entries, captureDir);
}

/**
 * Dispatcher entry point. Mirrors `inject-prod-state`'s `run`.
 */
export function run(_input: ClaudeHookInput, _ctx: DispatchContext): GuardOutcome | null {
  const notice = collectNewCaptureNotice();
  if (!notice) return null;
  return { additionalContext: notice };
}

async function main(): Promise<void> {
  await readInput();
  const notice = collectNewCaptureNotice();
  const output: HookOutput = notice
    ? {
        hookSpecificOutput: {
          hookEventName: "UserPromptSubmit",
          additionalContext: notice,
        },
      }
    : {};
  writeOutput(output);
}

if (import.meta.main) {
  await main();
}
