#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/retrospective-discharge.ts

// Discharge check for a fired retrospective trigger (mt#4566).
//
// `turn-end-retro-scan.ts` fires an advisory at `Stop` when a turn carries a
// retrospective-trigger phrase, and NOTHING observes what happens next. Its
// pre-fire suppression is already structural — `hasRetrospectiveSkillInvocation`
// matches a `tool_use` block, not prose — but once it has fired, its dedup store
// filters the same (turn, family, phrase) out of every subsequent `Stop`, so the
// post-continuation re-check that would notice a prose-only response never runs.
// The advisory is delivered and its outcome is unobserved.
//
// ## Why this runs at `UserPromptSubmit` and not at `Stop`
//
// Per ADR-031, sub-operation (3) — "read the turn's TOOL CALLS" — belongs at
// `UserPromptSubmit`, which has strictly more transcript flush time. That is a
// MATCH with the ADR rather than a deviation, and it is independently forced by
// this check's own semantics: at the `Stop` the guard fires on, the remediation
// has not happened yet BY CONSTRUCTION, because prompting the next beat is what
// the advisory is for. An artifact check there fires on the compliant case as
// loudly as the non-compliant one.
//
// ## Why the window is five turns and not one
//
// Compliance does not reliably land in the flagged turn. Measured in the
// originating transcript (session `84d5a587-…`, 2026-08-25): the guard fired at
// 16:06:52Z, and the remediation landed at 16:10:40Z with a REAL user prompt at
// 16:08:56Z between them — a plain-string user line, no `isMeta`, so
// `isRealUserPrompt` returns true and it is a genuine turn boundary. A
// single-turn check would have warned at that prompt, on a turn that was about
// to be complied with.
//
// This is the shape `hasRecentRetrospectiveInvocation` already solves for the
// SUPPRESSION side (mt#3036, widened for advisor-subagent output landing 1-3
// turns later). The same window and the same constant are reused here rather
// than a second number being invented.
//
// ## Three dispositions, because two of them are currently one
//
// Per the accepted RFC *The evaluation loop — auditing the regulators* Position
// 4, a guard's silence is a three-state ambiguity that must be resolvable. One
// level down, the states after a fire are `acted`, `declined` and `unaddressed`
// — and today they are indistinguishable. `declined` needs an explicit marker
// because there is no tool call that means "this was a false positive";
// `[not-a-retrospective: <reason>]` follows the corpus's existing literal-token
// convention (`[unverified-tests]`, `[no-deploy-impact]`, `[atN-deferred: …]`),
// which has no paraphrase axis to tune.
//
// LOG-ONLY, and advisory even after graduation: `turn-end-retro-scan.ts`'s own
// header forbids blocking for this detector family.
//
// @see .minsky/hooks/turn-end-retro-scan.ts — the Stop guard whose fires this observes
// @see .minsky/hooks/turn-end-scan-store.ts — the flag store shared across the boundary
// @see docs/architecture/adr-031-guidance-detector-lifecycle-event.md — the event assignment
// @see mt#4566 — this task

import type { TranscriptLine } from "./transcript";
import { findRealPromptIndices } from "./transcript";
import { hasRetrospectiveSkillInvocation } from "./retrospective-trigger-scanner";
import { flagKey } from "./turn-end-scan-store";

/**
 * Family slot used to mark a turnKey as already reported on, so a finding is
 * emitted once rather than on every subsequent prompt.
 *
 * Recorded as an ADDITIONAL key rather than by REMOVING the trigger's own flags.
 * Those flags do double duty — `turn-end-scan-store.ts`'s header names the
 * prompt-time trigger scanner as their second reader, which relies on them to
 * avoid re-flagging a phrase the agent has already been shown. Clearing them
 * here would silently re-arm that scanner on an old turn.
 */
export const DISCHARGE_REPORTED_FAMILY = "discharge-reported";

/** Tool names whose invocation is a durable artifact for this purpose. */
const DISCHARGE_TOOL_RE = /(?:memory_create|memory_patch|tasks_create)$/i;

/** File-writing tools whose target PATH decides whether they count. */
const FILE_WRITE_TOOL_RE =
  /(?:^|_)(?:Write|Edit)$|(?:session_write_file|session_search_replace|session_edit_file)$/i;

/** Input keys naming a written file, across the two tool families. */
const FILE_PATH_INPUT_KEYS = ["file_path", "path"] as const;

/**
 * Paths whose modification is a durable structural fix — the artifact classes
 * `/retrospective` Step 5 actually produces. Deliberately NOT all of `docs/`:
 * this asks "was a FIX landed", not "was prose written".
 */
const DURABLE_FIX_PATH_RE = /(?:^|\/)CLAUDE\.md$|(?:^|\/)\.minsky\/rules\//i;

/** The same set, for trees rather than a single file. */
const DURABLE_FIX_TREE_RE = /(?:^|\/)\.claude\/skills\/|(?:^|\/)\.minsky\/hooks\//i;

/**
 * Explicit false-positive disposition. A literal token, matched case-insensitively;
 * the reason text is free-form and is not parsed.
 */
export const DECLINE_MARKER_RE = /\[not-a-retrospective\s*:/i;

/** Stable identity of a real-prompt line — the same derivation `turnKeyFor` uses. */
export function promptIdentity(line: TranscriptLine | undefined): string {
  if (!line) return "session-start";
  return line.uuid ?? line.timestamp ?? "session-start";
}

/** Every `tool_use` block in `lines`, in both recorded shapes. */
function forEachToolUse(
  lines: TranscriptLine[],
  visit: (name: string, input: Record<string, unknown> | undefined) => void
): void {
  for (const line of lines) {
    if (line.type === "tool_use") {
      visit(line.name ?? line.tool_name ?? "", line.input);
    }
    const content = line.message?.content;
    if (!Array.isArray(content)) continue;
    for (const block of content as Array<Record<string, unknown>>) {
      if (block["type"] !== "tool_use") continue;
      visit(
        typeof block["name"] === "string" ? block["name"] : "",
        block["input"] as Record<string, unknown> | undefined
      );
    }
  }
}

/**
 * True when `lines` carry a durable RECORD — a memory, a task, or a
 * structural-fix file edit.
 *
 * Deliberately does NOT include the skill invocation, and the separation is the
 * whole point (mt#4566). An earlier revision of this task's criteria folded the
 * two together under "was an artifact produced", which would have passed the
 * incident it was derived from: the originating turn wrote a `memory_patch` and
 * a `tasks_spec_patch` and never invoked `/retrospective`, and the principal's
 * complaint was specifically *"I don't see you using the retrospective skill."*
 * Collapsing "wrote something durable instead of running the skill" into "did
 * nothing at all" loses exactly the observed failure.
 */
export function hasDurableArtifact(lines: TranscriptLine[]): boolean {
  let found = false;
  forEachToolUse(lines, (name, input) => {
    if (found) return;
    if (DISCHARGE_TOOL_RE.test(name)) {
      found = true;
      return;
    }
    if (!FILE_WRITE_TOOL_RE.test(name) || !input) return;
    for (const key of FILE_PATH_INPUT_KEYS) {
      const value = input[key];
      if (typeof value !== "string" || value.trim().length === 0) continue;
      if (DURABLE_FIX_PATH_RE.test(value) || DURABLE_FIX_TREE_RE.test(value)) {
        found = true;
        return;
      }
    }
  });
  return found;
}

/** True when `lines` carry the explicit not-a-retrospective marker in assistant text. */
export function hasDeclineMarker(lines: TranscriptLine[]): boolean {
  for (const line of lines) {
    const content = line.message?.content;
    if (typeof content === "string") {
      if (DECLINE_MARKER_RE.test(content)) return true;
      continue;
    }
    if (!Array.isArray(content)) continue;
    for (const block of content as Array<Record<string, unknown>>) {
      const text = block["text"];
      if (typeof text === "string" && DECLINE_MARKER_RE.test(text)) return true;
    }
  }
  return false;
}

/**
 * What became of a fired trigger.
 *
 * - `acted` — `/retrospective` was invoked. The only unambiguous discharge.
 * - `declined` — the explicit `[not-a-retrospective: …]` marker was written.
 * - `artifact-only` — a durable record was written but the skill was never run.
 *   **This is the originating incident's shape**, and it is its own class rather
 *   than a pass so that "wrote a memory instead" stays distinguishable from both
 *   "ran the retrospective" and "did nothing".
 * - `unaddressed` — the window closed with none of the above.
 */
export type Disposition = "acted" | "declined" | "artifact-only" | "unaddressed";

export interface DischargeFinding {
  /** The flagged turn's stable key (its opening real prompt's uuid/timestamp). */
  turnKey: string;
  /** Trigger families flagged on that turn. */
  families: string[];
  disposition: Disposition;
  /** Real user prompts that have opened since the flagged turn. */
  turnsElapsed: number;
}

/**
 * Parse the Stop guard's flag set into `turnKey -> families`.
 *
 * Keys are `${turnKey}|${family}|${phrase}` (see `flagKey`). A turnKey may
 * itself contain no `|` — it is a uuid or an ISO timestamp — so splitting on
 * the FIRST two separators is unambiguous, and a phrase containing `|` is
 * harmless because the phrase is not read here.
 */
export function groupFlaggedByTurn(flagged: Set<string>): Map<string, Set<string>> {
  const byTurn = new Map<string, Set<string>>();
  for (const key of flagged) {
    const first = key.indexOf("|");
    if (first < 0) continue;
    const turnKey = key.slice(0, first);
    const rest = key.slice(first + 1);
    const second = rest.indexOf("|");
    const family = second < 0 ? rest : rest.slice(0, second);
    if (family === DISCHARGE_REPORTED_FAMILY) continue;
    let set = byTurn.get(turnKey);
    if (!set) {
      set = new Set<string>();
      byTurn.set(turnKey, set);
    }
    if (family.length > 0) set.add(family);
  }
  return byTurn;
}

/**
 * Findings for every flagged turn whose window has resolved, plus the flag keys
 * to record as reported.
 *
 * A turn is skipped — not reported — when it is still the in-flight turn, when
 * its window is open and undischarged, or when its key cannot be located among
 * the transcript's real prompts (that last case is a genuine unknown: the turn
 * may predate the visible transcript, and guessing either way would invent a
 * verdict).
 */
export function analyzeDischarge(
  lines: TranscriptLine[],
  flagged: Set<string>,
  lookbackTurns: number
): {
  findings: DischargeFinding[];
  reportedKeys: string[];
  unresolved: string[];
  degraded?: string;
} {
  const findings: DischargeFinding[] = [];
  const reportedKeys: string[] = [];
  /**
   * Flagged turns whose key matches no real prompt in the visible transcript.
   *
   * Reported as a COUNT rather than as a `degraded` marker, and the distinction
   * is deliberate. ADR-024's invariant is that a scan which cannot COMPLETE
   * must not silently pass; this scan completes and correctly declines to
   * judge, which is the expected outcome for a turn that has rolled out of the
   * visible transcript. Marking it degraded would fire on every long session.
   * Surfacing the count keeps it from being invisible — a rising number is the
   * signal that the store and the transcript have drifted apart.
   */
  const unresolved: string[] = [];

  const byTurn = groupFlaggedByTurn(flagged);
  if (byTurn.size === 0) return { findings, reportedKeys, unresolved };

  const promptIndices = findRealPromptIndices(lines);
  if (promptIndices.length === 0) {
    // THIS is the ADR-024 `degraded` case, and it is the only one here (PR #3382
    // R1, BLOCKING). Flags exist but the transcript yielded no real prompt at
    // all, so the scan cannot run — not "ran and found nothing to say."
    // Distinguishing it from the per-turn `unresolved` count below is the whole
    // point: a turn that rolled out of a long transcript is the EXPECTED
    // outcome, and degrading on it would fire constantly and train the reader
    // to ignore the field (mem#719), which is how a real degradation gets
    // missed.
    return {
      findings,
      reportedKeys,
      unresolved: [...byTurn.keys()],
      degraded: "no real user prompt in the transcript — discharge window is unresolvable",
    };
  }

  for (const [turnKey, families] of byTurn) {
    if (flagged.has(flagKey(turnKey, DISCHARGE_REPORTED_FAMILY, ""))) continue;

    const slot = promptIndices.findIndex((idx) => promptIdentity(lines[idx]) === turnKey);
    if (slot < 0) {
      unresolved.push(turnKey);
      continue;
    }

    // The last real prompt is the one being submitted now, so the flagged turn
    // has completed only if at least one prompt has opened after it.
    const turnsElapsed = promptIndices.length - 1 - slot;
    if (turnsElapsed < 1) continue;

    const startIdx = promptIndices[slot];
    if (startIdx === undefined) continue;

    // Bounded at BOTH ends. The upper bound is what makes `lookbackTurns` mean
    // something: without it the window ran to the end of the transcript, so a
    // `/retrospective` twenty turns later still read as `acted` and the
    // lookback only decided when to give up waiting. That also made the
    // window's negative control untestable — there was no ordering that could
    // distinguish a wide window from an unbounded one.
    const endSlot = slot + lookbackTurns + 1;
    const endIdx = endSlot < promptIndices.length ? promptIndices[endSlot] : lines.length;
    const windowLines = lines.slice(startIdx, endIdx);

    // `acted` and `declined` are terminal as soon as they are observed. The
    // other two are conclusions about the WINDOW, so they wait for it to close
    // — an agent that wrote a memory on turn N may still run the skill on turn
    // N+2, and reporting `artifact-only` early would be a false positive on the
    // ordinary lagging-compliance case this window exists to accommodate.
    let disposition: Disposition;
    if (hasRetrospectiveSkillInvocation(windowLines)) {
      disposition = "acted";
    } else if (hasDeclineMarker(windowLines)) {
      disposition = "declined";
    } else if (turnsElapsed > lookbackTurns) {
      disposition = hasDurableArtifact(windowLines) ? "artifact-only" : "unaddressed";
    } else {
      continue;
    }

    findings.push({
      turnKey,
      families: [...families].sort(),
      disposition,
      turnsElapsed,
    });
    reportedKeys.push(flagKey(turnKey, DISCHARGE_REPORTED_FAMILY, ""));
  }

  return { findings, reportedKeys, unresolved };
}
