#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/turn-end-stale-state-assertion-scan.ts

// Stop-event guard: the closing message says an entity is waiting on the
// principal, and the substrate says it is already terminal (mt#4199).
//
// WHY THIS EXISTS RATHER THAN A CUE:
//   `/check-premise` cue (i) already names this exact shape — "about to tell
//   the principal that an open item requires their action … re-read the item's
//   LIVE state THIS turn" — and shipped as mt#3216 on 2026-07-25. The assertion
//   recurred on 2026-08-16 (mem#669 R17) and again, on the sibling cue (h)'s
//   surface, thirty minutes later (R18). Both failed for one structural reason:
//   `/check-premise` is invoke-on-demand, and its trigger lands while composing
//   the CLOSING MESSAGE, where there is no tool call to gate on.
//
//   mt#4191 then measured the general case and settled it: the skill has NEVER
//   been invoked — zero times across 558 conversations and 1488 transcript
//   files — while eight tasks have been filed to improve its cue text. The cue
//   tier here is not weak; it is inert. This guard is the same discipline at the
//   only interception point that actually runs at composition time.
//
// THE ASYMMETRY THAT JUSTIFIES THE IO:
//   A wrong internal premise costs the agent a rework cycle. A wrong "this needs
//   you" spends the principal's attention on an action that then fails — the
//   exact damage the Ask subsystem exists to prevent. Both recorded occurrences
//   cost the principal a round-trip.
//
// COST DISCIPLINE — the prose gate runs first, ALWAYS:
//   A cold hook DB connect measures 3.3–5.5s (mt#2430's staged breakdown), so a
//   substrate read on every Stop would be a serious regression. The gate below
//   is regex over the elided tail and does no IO; the query runs only when a
//   pending-on-principal assertion AND an entity ref appear TOGETHER. On the
//   overwhelmingly common turn this guard costs a few string scans.
//
// PRECISION — proximity, not co-occurrence:
//   Requiring only that the message contain both a phrase and a ref would fire
//   on any turn that mentions a task anywhere and says "let me know" anywhere.
//   The two must fall within {@link PROXIMITY_CHARS} of each other, which is
//   what makes "Still with you: ask#8467" a hit and a ref three paragraphs from
//   an unrelated sign-off a miss.
//
// CALIBRATION-FIRST (ADR-024): record-only. This emits NO advisory. The
// evaluation stream records the suppressed cases beside the fired ones so the
// miss rate is measurable rather than assumed, per the ladder's Rung-1 posture.
//
// @see .minsky/hooks/turn-end-unescalated-incident-scan.ts — the hybrid
//      phrase-trigger/state-check template this follows
// @see .minsky/hooks/duplicate-signature-scan.ts — the bounded fail-open
//      substrate-read template this follows
// @see mem#669 R17/R18 — the two occurrences; mt#3216 — the cue whose
//      containment this addresses; mt#4194 — the skill-text sibling

import type { DispatchContext, GuardOutcome } from "./registry";
import type { StopHookInput } from "./turn-end-retro-scan";
import { flagKey, readFlagged, writeFlagged } from "./turn-end-scan-store";
import { elideQuotedAndCodeContexts } from "./elision";
import { ensureHookDomainBootstrap, describeProviderResolutionFailure } from "./domain-bootstrap";
import type { SqlCapablePersistenceProvider } from "../../packages/domain/src/persistence/types";
// From @minsky/shared, a dependency-free leaf package — the lightest place to
// share this helper. (The former reason given here, that hooks must avoid `src/`
// so a type-check failure cannot break them, was retired by mt#4373: Bun strips
// types at import and never type-checks, so that failure mode does not exist.
// Note the line above already imports a domain TYPE: `import type` is erased at
// runtime, so it carries no RUNTIME coupling. Build-time coupling still applies
// — path resolution and declaration emit see it, and it breaks if the symbol
// moves or is renamed.)
import { safeTruncate } from "@minsky/shared/safe-truncate";
import {
  nominate,
  type ExemplarSet,
} from "../../packages/domain/src/detectors/embedding-nomination";
import { resolveNominationDeps } from "../../packages/domain/src/detectors/embedding-nomination-factory";

export const OVERRIDE_ENV_VAR = "MINSKY_SKIP_STALE_STATE_ASSERTION_SCAN";

/**
 * How much of the closing message's tail to scan.
 *
 * Matches the unescalated-incident guard's window for the same reason: a
 * "here is what's left for you" passage states the situation and then often
 * continues, so the trigger sentence can sit above the final line.
 */
export const TAIL_WINDOW_CHARS = 1500;

/** How much of the message the calibration record keeps, for a human classifier. */
export const CALIBRATION_TAIL_CHARS = 600;

/**
 * Maximum distance between a pending-assertion phrase and an entity ref for the
 * two to count as one claim. Roughly a long sentence — wide enough for
 * "Still with you: ask#8467 — what mt#2430 should deliver", narrow enough that
 * an unrelated sign-off does not capture a ref from another paragraph.
 */
export const PROXIMITY_CHARS = 200;

// ---------------------------------------------------------------------------
// Rung 2: embedding nomination for the two shapes Rung 1 cannot reach (mt#4580)
// ---------------------------------------------------------------------------

/**
 * Why this guard climbs, and why widening the regex would have been wrong.
 *
 * mt#4199 shipped Rung 1 for ONE assertion shape: "this entity awaits you",
 * checked against terminality. Two adjacent shapes in the same family reached
 * the principal through this same interception point and were not covered.
 * Both occurred in a single turn on 2026-08-25 and are recorded as R19/R20 on
 * the `assertion-without-verification` family (mem#1269):
 *
 *   R19 — recommending work a peer already holds. A closing message said to
 *         START a task another session had picked up twelve minutes earlier.
 *   R20 — a past-tense completion claim. "I've recorded this on the task", in
 *         a turn that made zero tool calls.
 *
 * MEASURED against this file's own prose gate, with a known-positive control:
 *
 *   R19 verbatim   -> findPendingClaims: 0 claims
 *   R20 verbatim   -> findPendingClaims: 0 claims
 *   CONTROL        -> findPendingClaims: 1 claim (ask#8467)
 *
 * The control firing is what makes the two zeros evidence rather than a
 * mis-invocation. It also locates the miss precisely: `findPendingClaims`
 * returns early when no assertion phrase matches, so the substrate read never
 * ran. `collectEntityRefs` would have found both refs. The gap is at
 * RECOGNITION, not at the state check.
 *
 * That is a recurring paraphrase miss, which ADR-024 assigns to Rung 2 —
 * "embedding recall-widening (only if paraphrase misses recur)" — and which its
 * §Context names the anti-pattern for answering with another regex family:
 * "each miss has historically been answered by adding another regex family
 * (R1 -> R5) — an arms race". mt#4565's adopted option B' (principal-decided
 * 2026-08-25) prescribes the same shape: "build per-detector Rung-2 nominators
 * as each detector's evidence gate is met." This guard's gate is met.
 *
 * The sibling `turn-end-untaken-action-scan` has three further recorded escapes
 * across three more grammatical forms (mt#3560, mt#3831) — five in the family
 * altogether, which is why the answer is a semantic stage rather than a sixth
 * pattern.
 */
export const NOMINATION_EXEMPLARS: ExemplarSet[] = [
  {
    // A recommendation that the principal PICK UP work. The defect this
    // catches is not the recommendation — it is that the recommendation went
    // stale, because a peer took the task while the read aged.
    family: "recommend-start",
    exemplars: [
      "The next thing to pick up is that task.",
      "That one is unblocked now and worth starting.",
      "You could take that task next; nothing is blocking it.",
      "The natural follow-on is to begin that piece of work.",
      "That is the one I would start on next.",
    ],
  },
  {
    // A claim that an action ALREADY happened. Distinct from the sibling
    // untaken-action guard, which keys on the opposite tense — a commitment to
    // act NEXT. A false completion claim is worse than an unmet commitment: it
    // asserts the work is done, so nothing downstream looks for it.
    family: "past-tense-claim",
    exemplars: [
      "That change is already written into the task.",
      "I updated the spec with those findings.",
      "The correction has been saved to the record.",
      "That has been filed and noted on the task.",
      "I went ahead and wrote that down.",
    ],
  },
];

/**
 * Operator kill switch for this guard's Rung-2 stage.
 *
 * Named to match the shipped sibling's convention
 * (`MINSKY_DISABLE_RUNG2_NOMINATION` on `retrospective-trigger-scanner`) but
 * scoped to this guard, so one detector's stage can be silenced without
 * silencing the other's. NOT a new operator-override var in the
 * `hook-files.mdc` sense — `MINSKY_SKIP_STALE_STATE_ASSERTION_SCAN` still
 * disables the whole guard, and this only reaches the semantic stage.
 */
export const NOMINATION_DISABLE_ENV_VAR = "MINSKY_DISABLE_STALE_STATE_RUNG2";

/**
 * Bound on the substrate read. Past this the scan reports a skip, never a fire.
 *
 * 6s rather than a tighter number for a measured reason: the bootstrap happens
 * INSIDE this race, and a cold hook domain bootstrap + connect measures 3.3–5.5s
 * (mt#2430's staged breakdown). A 4s bound would therefore time out on the first
 * hit in a fresh process — systematically, not occasionally — and record a
 * suppression where a finding was available. The bootstrap caches per process,
 * so only the first hit pays it.
 *
 * The residual is real and deliberately left measurable rather than assumed
 * away: a genuinely cold first hit can still exceed this, and when it does the
 * record carries `lookup-unavailable`. The replay in the task's SC6 will show
 * how often that happens; if it is common, the fix is to move the read off the
 * critical path, not to keep raising a number.
 */
export const LOOKUP_TIMEOUT_MS = 6_000;

/**
 * Ask states that mean the principal has nothing left to do.
 *
 * `routed` and `suspended` are deliberately ABSENT: a suspended ask genuinely IS
 * awaiting the principal, which is the true-negative this guard must not spoil.
 */
export const TERMINAL_ASK_STATES: readonly string[] = [
  "closed",
  "responded",
  "cancelled",
  "expired",
];

/** Task statuses that mean the principal has nothing left to do. */
export const TERMINAL_TASK_STATUSES_FOR_SCAN: readonly string[] = ["DONE", "CLOSED"];

/**
 * How far into a title/question a resolution declaration may sit and still count.
 *
 * A declaration is a HEADLINE — it opens the text, because its whole purpose is
 * to be read first. Scanning the entire body instead would match any ask that
 * merely discusses resolution, which is the false positive mt#4375 was specced
 * to avoid.
 */
const RESOLUTION_DECLARATION_WINDOW = 200;

/**
 * Phrases that, at the head of an ask's own title or question, mean its author
 * declared it finished — regardless of what the `state` column says.
 *
 * Kept as a named constant beside {@link TERMINAL_ASK_STATES} because it plays
 * the same role for a DIFFERENT signal: that one reads the state column, this
 * one reads what the ask says about itself.
 */
export const RESOLUTION_DECLARATION_PHRASES: readonly string[] = ["no action needed"];

/**
 * Words that count as a declaration when they OPEN the text.
 *
 * Separate from {@link RESOLUTION_DECLARATION_PHRASES} because the two are
 * matched differently, not because one is more important: these need the
 * leading-position anchor to distinguish "RESOLVED — …" from "…is resolved",
 * while the phrases above are unambiguous anywhere near the head. Both are
 * named constants rather than inline literals so the vocabulary is testable and
 * extendable without touching the matcher (mt#4375 SC2).
 */
export const RESOLUTION_DECLARATION_LEAD_WORDS: readonly string[] = ["resolved"];

/**
 * True when an ask's own text declares it resolved (mt#4375).
 *
 * Two independent signals, either sufficient:
 *
 * 1. The text OPENS with `resolved` followed by a boundary — "RESOLVED — …",
 *    "**RESOLVED. No action needed…**". Anchoring at the head is what separates
 *    a declaration from a mention: "blocked until mt#4294 is resolved" contains
 *    the same word and asserts the opposite.
 * 2. It carries an unambiguous phrase from {@link RESOLUTION_DECLARATION_PHRASES}
 *    near the head. "no action needed" has no non-declarative reading, so it does
 *    not need the leading-position anchor that bare "resolved" does.
 *
 * Markdown emphasis is stripped first: the originating ask (ask#9278) wrote
 * `**RESOLVED. No action needed from you.**`, so a check anchored on the raw
 * first character would have missed the exact case this exists for.
 */
export function declaresResolution(...texts: readonly (string | undefined)[]): boolean {
  for (const raw of texts) {
    if (typeof raw !== "string" || raw.length === 0) continue;
    const head = raw.slice(0, RESOLUTION_DECLARATION_WINDOW).toLowerCase();
    // Strip leading markdown emphasis/quote/heading marks and whitespace.
    const anchored = head.replace(/^[\s*_#>`~-]+/, "");
    const opensWithLeadWord = RESOLUTION_DECLARATION_LEAD_WORDS.some(
      (word) => anchored.startsWith(word) && !/[a-z0-9]/.test(anchored.charAt(word.length))
    );
    if (opensWithLeadWord) return true;
    if (RESOLUTION_DECLARATION_PHRASES.some((phrase) => head.includes(phrase))) return true;
  }
  return false;
}

/**
 * Vocabulary asserting that an item is waiting on the PRINCIPAL.
 *
 * Derived from the two recorded occurrences and their nearest paraphrases, not
 * invented. R17's literal phrasing was "Still with you: ask#8467". Kept narrow
 * on purpose — this is the TRIGGER half, and a loose trigger turns every status
 * report into a database query.
 */
const PENDING_ASSERTION_PATTERNS: ReadonlyArray<{ family: string; re: RegExp }> = [
  { family: "still-with-you", re: /\bstill\s+(with|on)\s+you\b/gi },
  { family: "waiting-on-you", re: /\b(waiting|blocked|pending)\s+on\s+(you|your)\b/gi },
  {
    family: "needs-your",
    re: /\bneeds?\s+your\s+(answer|decision|call|input|review|approval)\b/gi,
  },
  { family: "awaiting-you", re: /\bawaiting\s+(you|your)\b/gi },
  { family: "your-call", re: /\b(is|remains)\s+your\s+call\b/gi },
  { family: "in-your-inbox", re: /\b(in|sitting\s+in)\s+your\s+inbox\b/gi },
  { family: "for-you-to", re: /\bfor\s+you\s+to\s+(answer|decide|review|approve)\b/gi },
];

/**
 * Which id-space a ref's identifier lives in.
 *
 * Load-bearing, and the reason is PR #3061's review: refs arrive in two spaces
 * and a lookup that queries one silently resolves nothing for the other. An
 * ask's `ask#N` is its `short_id`; a `minsky://ask/<uuid>` target is its `id`.
 * (Tasks have only one space — `tasks.id` is `text` holding `mt#N`, so the bare
 * and link forms coincide.)
 */
export type IdForm = "short" | "uuid";

/** An entity reference the substrate can resolve. */
export interface EntityRef {
  /** `ask` or `task` — the two kinds this guard resolves without a network call. */
  kind: "ask" | "task";
  /** The ref exactly as it appeared, e.g. `ask#8467` or `mt#2430`. */
  ref: string;
  /** The identifier to look up, interpreted per {@link idForm}. */
  id: string;
  /** Which column {@link id} matches. */
  idForm: IdForm;
  /** Character offset of the ref within the scanned text. */
  at: number;
}

export interface AssertionSignal {
  family: string;
  phrase: string;
  at: number;
}

/** A ref asserted as pending, paired with the phrase that asserted it. */
export interface PendingClaim {
  entity: EntityRef;
  assertion: AssertionSignal;
}

/** What the substrate said about one claimed-pending entity. */
export interface ResolvedClaim extends PendingClaim {
  liveState: string;
  isTerminal: boolean;
  /**
   * The ask's own text declares it resolved while `state` is non-terminal
   * (mt#4375). Independent of {@link isTerminal} — an ask can be one, both, or
   * neither, and the two are kept apart so each class's false-positive rate is
   * separately reviewable in the calibration log.
   */
  declaresResolved: boolean;
  /**
   * Which signal produced the contradiction. `undefined` when there is none.
   */
  contradictionKind?: "terminal-state" | "content-declares-resolved";
}

/**
 * Percent-decode a link target, or `null` when it is malformed.
 *
 * `decodeURIComponent` THROWS a `URIError` on a bad escape (`%ZZ`, a truncated
 * `%2`), and the ref regex admits `%` — so `minsky://task/mt%2`, a mistyped or
 * truncated deeplink, would throw out of a Stop guard on an ordinary message
 * (PR #3061 R3). A scanner reading arbitrary prose must treat that prose as
 * untrusted input: an unparseable target is not a ref, and skipping it is the
 * whole correct behaviour.
 */
function safeDecode(raw: string): string | null {
  try {
    return decodeURIComponent(raw);
  } catch {
    // intentional-swallow: a malformed target is not a ref. The throw carries
    // no information the caller can act on, and letting it escape would turn a
    // typo in a link into a guard failure.
    return null;
  }
}

/**
 * Collect entity refs the substrate can resolve.
 *
 * The UNION of two forms, which is the refinement mt#4199's planning audit
 * recorded: `bare-entity-ref-scan`'s `scanMessage` enumerates refs it flagged or
 * LOGGED for LINKIFICATION, which is not the same population as "every ref in
 * the message" — a correctly-linked ref appears only among its `linkTargets`.
 * So both the bare `ask#N` / `mt#N` forms and the `minsky://` link targets are
 * matched here directly, rather than inheriting one view's blind spot.
 *
 * `mem#N` and `ws#N` are deliberately not collected: neither has a state that
 * can be "awaiting the principal", so a ref to one carries no claim to check.
 */
export function collectEntityRefs(text: string): EntityRef[] {
  const out: EntityRef[] = [];
  const seen = new Set<string>();

  const push = (
    kind: EntityRef["kind"],
    ref: string,
    id: string,
    idForm: IdForm,
    at: number
  ): void => {
    const dedupe = `${kind}:${idForm}:${id}`;
    if (seen.has(dedupe)) return;
    seen.add(dedupe);
    out.push({ kind, ref, id, idForm, at });
  };

  for (const m of text.matchAll(/\bask#(\d+)\b/gi)) {
    push("ask", m[0], m[1] ?? "", "short", m.index ?? 0);
  }
  for (const m of text.matchAll(/\bmt#(\d+)\b/gi)) {
    push("task", m[0], `mt#${m[1] ?? ""}`, "short", m.index ?? 0);
  }
  // Link targets. An ask's carries its UUID, a DIFFERENT column from the short
  // id above — so it is tagged and resolved separately. A task's decodes back
  // to `mt#N`, which is what `tasks.id` already holds, so it is the same space.
  for (const m of text.matchAll(/minsky:\/\/(ask|task)\/([A-Za-z0-9%#._-]+)/gi)) {
    const kind = (m[1] ?? "").toLowerCase() === "ask" ? "ask" : "task";
    const raw = safeDecode(m[2] ?? "");
    if (raw === null) continue;
    push(kind, m[0], raw, kind === "ask" ? "uuid" : "short", m.index ?? 0);
  }

  return out;
}

/** Every pending-assertion phrase in the text, with its offset. */
export function collectAssertions(text: string): AssertionSignal[] {
  const out: AssertionSignal[] = [];
  for (const { family, re } of PENDING_ASSERTION_PATTERNS) {
    for (const m of text.matchAll(re)) {
      out.push({ family, phrase: m[0], at: m.index ?? 0 });
    }
  }
  return out;
}

/**
 * Pair each entity ref with a nearby pending-assertion phrase.
 *
 * Pure and IO-free — this is the gate that decides whether the substrate read
 * happens at all. Exported for tests.
 */
export function findPendingClaims(finalMessage: string): PendingClaim[] {
  const tail = finalMessage.slice(-TAIL_WINDOW_CHARS);
  const prose = elideQuotedAndCodeContexts(tail);

  const assertions = collectAssertions(prose);
  if (assertions.length === 0) return [];

  const refs = collectEntityRefs(prose);
  if (refs.length === 0) return [];

  const claims: PendingClaim[] = [];
  for (const entity of refs) {
    let nearest: AssertionSignal | undefined;
    let nearestDistance = Number.POSITIVE_INFINITY;
    for (const assertion of assertions) {
      const distance = Math.abs(assertion.at - entity.at);
      if (distance <= PROXIMITY_CHARS && distance < nearestDistance) {
        nearest = assertion;
        nearestDistance = distance;
      }
    }
    if (nearest) claims.push({ entity, assertion: nearest });
  }
  return claims;
}

/**
 * Rung 2. Nominate claims Rung 1's phrase set could not recognise.
 *
 * Runs ONLY when Rung 1 found nothing and the tail carries a resolvable ref.
 * That ordering is the cost discipline: `collectEntityRefs` is pure string work,
 * so a turn mentioning no task or ask still reaches no IO at all.
 *
 * **This does change the guard's cost profile, deliberately.** mt#4199's gate
 * was "phrase AND ref"; a turn carrying a ref with no pending-assertion phrase
 * did zero IO. It now reaches one batched embedding call. That is what climbing
 * to Rung 2 costs, and it is the trade ADR-024 authorises once paraphrase misses
 * recur — which they did, measured, twice in one turn. The call is bounded by
 * {@link NOMINATION_TIMEOUT_MS} and degrades rather than throwing, so the
 * worst case is a slower Stop, never a failed one.
 *
 * Returns synthesized {@link PendingClaim}s so the downstream state check sees
 * one shape regardless of which rung produced the claim. The synthesized
 * `assertion.family` carries the nominated family, which is what routes the
 * claim to its state check — peer-activity for `recommend-start`, tool-call
 * inspection for `past-tense-claim`.
 */
export interface NominationOutcome {
  claims: PendingClaim[];
  /** Present when the stage could not run; the reason is carried to calibration. */
  degradedReason?: string;
  /** Highest score per nominated family, for the calibration record. */
  scores: { family: string; score: number }[];
}

/** Nomination is bounded well under the Stop hook's own budget. */
export const NOMINATION_TIMEOUT_MS = 2000;

export async function nominatePendingClaims(
  finalMessage: string,
  deps?: { resolve: typeof resolveNominationDeps; run: typeof nominate }
): Promise<NominationOutcome> {
  const disabled = process.env[NOMINATION_DISABLE_ENV_VAR];
  if (disabled === "1" || disabled?.toLowerCase() === "true") {
    return { claims: [], degradedReason: "rung2-disabled", scores: [] };
  }

  const tail = finalMessage.slice(-TAIL_WINDOW_CHARS);
  const prose = elideQuotedAndCodeContexts(tail);

  // The cheap gate, unchanged in spirit: no ref, nothing to be wrong about.
  const refs = collectEntityRefs(prose);
  if (refs.length === 0) return { claims: [], scores: [] };

  const resolve = deps?.resolve ?? resolveNominationDeps;
  const run = deps?.run ?? nominate;

  const nominationDeps = await resolve();
  if (nominationDeps === null) {
    return { claims: [], degradedReason: "nomination-deps-unavailable", scores: [] };
  }

  const result = await run(prose, NOMINATION_EXEMPLARS, nominationDeps, {
    timeoutMs: NOMINATION_TIMEOUT_MS,
  });
  if (result.degraded) {
    return {
      claims: [],
      degradedReason: result.degradedReason
        ? `nomination-degraded: ${result.degradedReason}${result.degradedDetail ? ` (${result.degradedDetail})` : ""}`
        : "nomination-degraded",
      scores: [],
    };
  }
  if (result.nominations.length === 0) return { claims: [], scores: [] };

  // Pair every nominated family with every ref in the tail. Unlike Rung 1 there
  // is no proximity filter: a nominated SEGMENT is a sentence, and the ref it
  // concerns is routinely in an adjacent sentence ("2. Start mt#4556 — its arms
  // are unmeasurable without it"). Proximity is what Rung 1 uses to bound a
  // phrase's reach; the semantic stage already bounds itself by meaning.
  const claims: PendingClaim[] = [];
  for (const nomination of result.nominations) {
    for (const entity of refs) {
      claims.push({
        entity,
        assertion: {
          family: nomination.family,
          phrase: nomination.segment,
          at: entity.at,
        },
      });
    }
  }

  return {
    claims,
    scores: result.nominations.map((n) => ({ family: n.family, score: n.score })),
  };
}

/** What the substrate returned for one ref, plus the key that identifies the ENTITY. */
export interface ResolvedState {
  /** The entity's live state string, verbatim from the row. */
  state: string;
  /**
   * A stable per-entity key, so the same entity named in two id-forms collapses
   * to one claim. For an ask this is its uuid regardless of which form was
   * matched; for a task, its id.
   */
  identity: string;
  /**
   * The ask's own title and question, when the row carried them (mt#4375).
   *
   * Optional because only the ASK query selects them; a task row has no
   * equivalent and leaves both absent. Not optional because the columns are
   * nullable — both are `.notNull()` in `ask-schema.ts`.
   */
  title?: string;
  question?: string;
}

/** The key a ref resolves under. Both id-spaces coexist, so the form is part of it. */
export function refKey(entity: EntityRef): string {
  return `${entity.kind}:${entity.idForm}:${entity.id}`;
}

/**
 * Decide, for each claim, whether the substrate's answer contradicts it.
 *
 * Split out of the query deliberately (the `/implement-task` §6 testable-design
 * checkpoint): the state maps are the only thing the classification depends on,
 * so keeping it pure lets the whole terminal-vs-open decision — the half that
 * actually produces findings — be tested by handing it two maps, rather than by
 * patching a database connection the guard reaches itself.
 *
 * A ref the substrate does not know is NOT a finding and is dropped here. It is
 * most often a uuid-form link or an id from another backend; treating an
 * unresolved row as terminal would invent a contradiction out of a lookup miss.
 */
export function classifyResolved(
  claims: PendingClaim[],
  states: ReadonlyMap<string, ResolvedState>
): ResolvedClaim[] {
  const out: ResolvedClaim[] = [];
  const seenIdentities = new Set<string>();
  for (const claim of claims) {
    const resolved = states.get(refKey(claim.entity));
    if (resolved === undefined) continue;
    // One ENTITY, one claim — even when the message names it twice in two
    // id-forms (PR #3061 review). Deduping on the ref would have recorded
    // `ask#8467` and its `minsky://ask/<uuid>` link as two independent
    // findings about the same ask, which is exactly what a well-linked
    // message produces.
    if (seenIdentities.has(resolved.identity)) continue;
    seenIdentities.add(resolved.identity);
    const isTerminal =
      claim.entity.kind === "ask"
        ? TERMINAL_ASK_STATES.includes(resolved.state.toLowerCase())
        : TERMINAL_TASK_STATUSES_FOR_SCAN.includes(resolved.state.toUpperCase());
    // mt#4375: an ask can be finished without its state column saying so.
    // `stale-suspended-close` NEVER auto-closes a non-commit-auth
    // `authorization.approve` ask — by design (mt#3215) — so "the body says
    // RESOLVED, the state says suspended" is a permanent population, not a
    // transient lag. Only checked when the state is NOT already terminal, so
    // the two classes stay disjoint and each is separately reviewable.
    const declaresResolved =
      claim.entity.kind === "ask" &&
      !isTerminal &&
      declaresResolution(resolved.title, resolved.question);
    const contradictionKind = isTerminal
      ? "terminal-state"
      : declaresResolved
        ? "content-declares-resolved"
        : undefined;
    out.push({
      ...claim,
      liveState: resolved.state,
      isTerminal,
      declaresResolved,
      ...(contradictionKind ? { contradictionKind } : {}),
    });
  }
  return out;
}

/** Outcome of the substrate read: resolved rows, or the reason there are none. */
export interface LookupResult {
  resolved: ResolvedClaim[];
  failed?: string;
}

/**
 * Read each claimed entity's live state.
 *
 * Bounded and fail-OPEN, following `duplicate-signature-scan`: every failure
 * becomes a `failed` string rather than a throw, so an infrastructure problem
 * produces a recorded skip and never a spurious fire. A guard that cannot read
 * the substrate knows nothing, and must say so rather than guess.
 *
 * Scope note: asks and tasks only. A PR's state lives on GitHub, so resolving
 * one would put a network round-trip inside a Stop hook — deliberately deferred
 * rather than smuggled in; see the spec's Out-of-scope list.
 */
export async function lookupLiveStates(claims: PendingClaim[]): Promise<LookupResult> {
  if (claims.length === 0) return { resolved: [] };

  let timer: ReturnType<typeof setTimeout> | undefined;
  const TIMED_OUT = Symbol("stale-state-assertion-lookup-timeout");
  const deadline = new Promise<typeof TIMED_OUT>((resolve) => {
    timer = setTimeout(() => resolve(TIMED_OUT), LOOKUP_TIMEOUT_MS);
  });
  // Rejection sink: runLookup converts every failure to a value, but an
  // after-deadline rejection would otherwise surface as unhandled.
  const lookup = runLookup(claims).catch(
    (err): LookupResult => ({
      resolved: [],
      failed: `lookup rejected: ${err instanceof Error ? err.message : String(err)}`,
    })
  );

  try {
    const outcome = await Promise.race([lookup, deadline]);
    if (outcome === TIMED_OUT) {
      return { resolved: [], failed: `lookup exceeded the ${LOOKUP_TIMEOUT_MS}ms deadline` };
    }
    return outcome;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Narrow one driver row to the two string columns this scan reads.
 *
 * A driver result is external input at a trust boundary, so it is narrowed by a
 * runtime guard rather than asserted into shape — the same discipline
 * `duplicate-signature-scan` states: a blanket `as unknown as Row[]` would make
 * a driver or schema change surface as an undefined field deep in the loop
 * instead of here, where it becomes a recorded skip.
 */
function isStateRow(row: unknown, keyColumn: string): row is Record<string, string> {
  if (typeof row !== "object" || row === null) return false;
  const rec = row as Record<string, unknown>;
  return typeof rec[keyColumn] === "string";
}

/** The un-raced lookup body. Never rejects — converts every failure to a value. */
async function runLookup(claims: PendingClaim[]): Promise<LookupResult> {
  try {
    const bootstrap = await ensureHookDomainBootstrap();
    if (!bootstrap.ok)
      return { resolved: [], failed: `domain bootstrap failed: ${bootstrap.error}` };

    const { resolvePersistenceProviderOrError } = await import(
      "../../packages/domain/src/persistence/factory"
    );
    const resolution = await resolvePersistenceProviderOrError();
    if (!resolution.ok) {
      return { resolved: [], failed: describeProviderResolutionFailure(resolution) };
    }
    const provider = resolution.provider;
    if (!provider.capabilities.sql || typeof provider.getDatabaseConnection !== "function") {
      return { resolved: [], failed: `provider ${provider.constructor.name} is not SQL-capable` };
    }
    const db = await (provider as SqlCapablePersistenceProvider).getDatabaseConnection();
    if (!db) return { resolved: [], failed: "no database connection" };

    const { sql } = await import("drizzle-orm");
    const states = new Map<string, ResolvedState>();

    // Two id-spaces for asks, queried in ONE statement rather than two so a
    // message carrying both forms costs the same round-trip as either alone.
    // The row returns BOTH columns, which is what lets each matched ref key
    // into the map under its own form while sharing one identity.
    const askShortIds = claims
      .filter((c) => c.entity.kind === "ask" && c.entity.idForm === "short")
      .map((c) => c.entity.id);
    const askUuids = claims
      .filter((c) => c.entity.kind === "ask" && c.entity.idForm === "uuid")
      .map((c) => c.entity.id);
    const taskIds = claims.filter((c) => c.entity.kind === "task").map((c) => c.entity.id);

    if (askShortIds.length > 0 || askUuids.length > 0) {
      // `::text` on both sides so a malformed ref fails to MATCH rather than
      // erroring the statement out — a uuid-shaped string compared against a
      // uuid column would otherwise raise on a bad cast.
      const shortClause =
        askShortIds.length > 0 ? sql`short_id::text in ${askShortIds}` : sql`false`;
      const uuidClause = askUuids.length > 0 ? sql`id::text in ${askUuids}` : sql`false`;
      const rows = await db.execute(sql`
        select id::text as id, short_id::text as short_id, state::text as state,
               title::text as title, question::text as question
        from asks
        where ${shortClause} or ${uuidClause}
      `);
      for (const row of Array.isArray(rows) ? rows : []) {
        if (!isStateRow(row, "id")) continue;
        const identity = row["id"] ?? "";
        const state = row["state"] ?? "";
        const shortId = row["short_id"];
        // mt#4375: read defensively rather than asserting the shape. Both columns
        // are `.notNull()` in `ask-schema.ts` (:135, :138), so this is NOT about
        // nullability — it is the trust-boundary discipline `isStateRow`'s own
        // docblock states: a driver result is external input, and a driver or
        // schema change should surface as a missing declaration here rather than
        // as an `undefined` reaching `declaresResolution` deeper in.
        const title = typeof row["title"] === "string" ? row["title"] : undefined;
        const question = typeof row["question"] === "string" ? row["question"] : undefined;
        const resolvedRow: ResolvedState = { state, identity, title, question };
        if (typeof shortId === "string" && shortId.length > 0) {
          states.set(`ask:short:${shortId}`, resolvedRow);
        }
        states.set(`ask:uuid:${identity}`, resolvedRow);
      }
    }

    if (taskIds.length > 0) {
      // One space only: `tasks.id` is `text` holding `mt#N` (full-schema.sql),
      // so the bare ref and the decoded `minsky://task/mt%23N` target are the
      // same string. Verified against the schema rather than assumed — PR #3061
      // review asserted these were uuids, and they are not.
      const rows = await db.execute(sql`
        select id::text as id, status::text as status
        from tasks
        where id::text in ${taskIds}
      `);
      for (const row of Array.isArray(rows) ? rows : []) {
        if (!isStateRow(row, "id")) continue;
        const identity = row["id"] ?? "";
        states.set(`task:short:${identity}`, { state: row["status"] ?? "", identity });
      }
    }

    return { resolved: classifyResolved(claims, states) };
  } catch (err: unknown) {
    return {
      resolved: [],
      failed: `lookup threw: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/**
 * Guard-dispatcher entry point (GuardModule contract).
 *
 * Record-only by design — returns a `calibration` payload and never an
 * `additionalContext`, per ADR-024's Rung-1 posture. The stream records
 * SUPPRESSED gate-hits beside fired ones (`fired: false` plus a reason) so the
 * false-positive AND miss rates are both measurable before any enforcement
 * posture is chosen.
 */
export async function run(
  input: StopHookInput,
  _ctx: DispatchContext,
  storeDir?: string
): Promise<GuardOutcome | null> {
  const overrideVal = process.env[OVERRIDE_ENV_VAR];
  const isOverride =
    overrideVal === "1" ||
    overrideVal?.toLowerCase() === "true" ||
    overrideVal?.toLowerCase() === "yes";
  if (isOverride) {
    return {
      auditLines: [
        `[turn-end-stale-state-assertion] OVERRIDE: ack=${overrideVal} session=${input.session_id ?? "unknown"} ts=${new Date().toISOString()}\n`,
      ],
    };
  }

  const finalMessage = input.last_assistant_message ?? "";
  if (finalMessage.length === 0) return null;

  // The cheap gate. No IO past this point unless it hits.
  const claims = findPendingClaims(finalMessage);
  if (claims.length === 0) return null;

  const sessionId = input.session_id ?? "unknown";
  // Dedup on the claimed refs, not the turn: an advisory continuation re-enters
  // Stop with the same message, and one claim should draw one record.
  const key = flagKey(
    claims.map((c) => `${c.entity.kind}:${c.entity.id}`).join("|"),
    "stale-state-assertion",
    ""
  );
  const flagged = readFlagged(sessionId, storeDir);
  if (flagged.has(key)) return null;
  flagged.add(key);
  writeFlagged(sessionId, flagged, storeDir);

  const lookup = await lookupLiveStates(claims);
  // mt#4375: two independent contradiction signals — the state column, and the
  // ask's own text declaring itself resolved while that column lags. Each row
  // carries `contradictionKind`, so the calibration stream keeps the classes
  // separable rather than pooling their false-positive rates.
  const contradicted = lookup.resolved.filter((r) => r.isTerminal || r.declaresResolved);

  const suppressionReasons: string[] = [];
  if (lookup.failed) suppressionReasons.push(`lookup-unavailable: ${lookup.failed}`);
  if (!lookup.failed && lookup.resolved.length === 0) {
    suppressionReasons.push("no-claimed-ref-resolved");
  }
  if (contradicted.length === 0 && lookup.resolved.length > 0) {
    suppressionReasons.push("all-claimed-refs-still-open");
  }

  return {
    calibration: {
      source: "live",
      channel: "stop",
      timestamp: new Date().toISOString(),
      session_id: input.session_id,
      stop_hook_active: input.stop_hook_active === true,
      fired: contradicted.length > 0,
      claims: claims.map((c) => ({
        ref: c.entity.ref,
        kind: c.entity.kind,
        assertionFamily: c.assertion.family,
        assertionPhrase: c.assertion.phrase,
      })),
      contradicted: contradicted.map((r) => ({
        ref: r.entity.ref,
        assertedPending: r.assertion.phrase,
        liveState: r.liveState,
      })),
      resolvedCount: lookup.resolved.length,
      final_message_tail: safeTruncate(finalMessage, CALIBRATION_TAIL_CHARS, "tail"),
      suppressionReasons,
    },
  };
}
