/**
 * Drizzle schema for reviewer_convergence_metrics table.
 *
 * Owned by the reviewer service. No imports from src/.
 * Cross-table joins with Minsky-side tables are done by table-name prefix.
 */

import { pgTable, uuid, text, integer, timestamp, index } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Stores per-review convergence metrics emitted by the reviewer service.
 *
 * Each row corresponds to one review (one invocation of runReview).
 * Together, rows for the same (pr_owner, pr_repo, pr_number) form the
 * convergence trajectory for that PR.
 */
export const convergenceMetricsTable = pgTable(
  "reviewer_convergence_metrics",
  {
    /** Surrogate PK generated by Postgres. */
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),

    /** GitHub repository owner (org or user login). */
    prOwner: text("pr_owner").notNull(),

    /** GitHub repository name. */
    prRepo: text("pr_repo").notNull(),

    /** Pull request number within the repository. */
    prNumber: integer("pr_number").notNull(),

    /** Git SHA of the PR head commit at review time. */
    headSha: text("head_sha").notNull(),

    /**
     * 0-indexed iteration count at time of review.
     * 0 = first review, 1 = first re-review, etc.
     */
    iterationIndex: integer("iteration_index").notNull(),

    /** Sum of BLOCKING findings across all prior reviews for this PR. */
    priorBlockerCount: integer("prior_blocker_count").notNull(),

    /** Count of BLOCKING findings in the current review body. */
    newBlockerCount: integer("new_blocker_count").notNull(),

    /** Best-effort count of findings acknowledged-as-addressed in the review body. */
    acknowledgedAddressedCount: integer("acknowledged_addressed_count").notNull(),

    /** Row insertion timestamp (UTC). */
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    /** Trajectory lookup: all reviews for a PR in order. */
    byPrIteration: index("idx_rcm_pr_iteration").on(
      table.prOwner,
      table.prRepo,
      table.prNumber,
      table.iterationIndex
    ),

    /** Time-window queries (dashboards, cleanup). */
    byCreatedAt: index("idx_rcm_created_at").on(table.createdAt),
  })
);

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

export type ConvergenceMetricRecord = typeof convergenceMetricsTable.$inferSelect;
export type ConvergenceMetricInsert = typeof convergenceMetricsTable.$inferInsert;
