/**
 * Drizzle schema for reviewer_inflight_reviews table.
 *
 * Owned by the reviewer service. No imports from src/.
 *
 * Records in-flight review markers for the sweeper-vs-webhook double-trigger
 * race elimination (mt#1907). A marker is acquired at runReview entry and
 * released at runReview exit. The UNIQUE constraint on (owner, repo,
 * pr_number, head_sha) combined with INSERT ... ON CONFLICT DO NOTHING is
 * the concurrency primitive: exactly one caller acquires the marker.
 *
 * TTL semantics: the expires_at column is set to acquired_at + TTL (default
 * 5 min). Stale markers (expires_at < now()) are pruned at the top of each
 * sweep cycle so a crashed runReview doesn't permanently block retriggering.
 */

import { pgTable, uuid, text, integer, timestamp, index, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * One row per in-flight review for a specific (owner, repo, pr_number, head_sha) tuple.
 *
 * The UNIQUE constraint ensures exactly one caller holds the marker at a time.
 * Callers use INSERT ... ON CONFLICT (owner, repo, pr_number, head_sha) DO NOTHING
 * RETURNING id to acquire; an empty RETURNING means another caller won.
 */
export const inflightReviewsTable = pgTable(
  "reviewer_inflight_reviews",
  {
    /** Surrogate PK generated by Postgres. */
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),

    /** GitHub repository owner (org or user login). */
    owner: text("owner").notNull(),

    /** GitHub repository name. */
    repo: text("repo").notNull(),

    /** Pull request number within the repository. */
    prNumber: integer("pr_number").notNull(),

    /** Git SHA of the PR head commit at acquisition time. */
    headSha: text("head_sha").notNull(),

    /**
     * Which code path acquired the marker.
     * 'webhook' for the primary webhook handler, 'sweeper' for sweeper retriggers.
     */
    acquiredBy: text("acquired_by").notNull(),

    /**
     * GitHub delivery ID (or synthesized sweeper delivery ID) for audit linkage.
     * Webhook handlers pass the X-GitHub-Delivery header; the sweeper uses
     * "sweeper-{timestamp}".
     */
    deliveryId: text("delivery_id").notNull(),

    /** Timestamp when the marker was acquired (UTC). */
    acquiredAt: timestamp("acquired_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),

    /**
     * Timestamp when the marker expires (UTC).
     * Set to acquired_at + TTL (default 5 min) at insert time.
     * Stale markers (expires_at < now()) are pruned at the top of each sweep cycle.
     */
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    /**
     * The concurrency primitive: at most one marker per (owner, repo, pr_number, head_sha).
     * INSERT ... ON CONFLICT DO NOTHING on this constraint is the acquire operation.
     */
    uniqPrHead: uniqueIndex("uniq_pr_head").on(
      table.owner,
      table.repo,
      table.prNumber,
      table.headSha
    ),

    /** TTL sweep and GC: find expired markers quickly. */
    byExpiresAt: index("idx_rir_expires_at").on(table.expiresAt),
  })
);

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

export type InflightReviewRecord = typeof inflightReviewsTable.$inferSelect;
export type InflightReviewInsert = typeof inflightReviewsTable.$inferInsert;
