/**
 * Drizzle schema for reviewer_submission_failures table (mt#2350).
 *
 * Owned by the reviewer service. No imports from src/.
 *
 * Records non-retryable (4xx) GitHub review-submission failures so the sweeper
 * can apply a circuit breaker: a 422 ("Line could not be resolved", self-review
 * constraint, etc.) is a CLIENT error, not a transient miss, and must not be
 * retriggered indefinitely. Each row tracks the consecutive-failure count for a
 * specific (owner, repo, pr_number, head_sha); when the count reaches the
 * threshold the circuit opens and the sweeper stops retriggering that PR at that
 * HEAD, emitting a one-shot operator alert.
 *
 * Why a durable table rather than in-memory sweeper state: sweeper-initiated
 * retriggers call runReview directly (not via the webhook handler), so their
 * submission failures are not otherwise persisted; and the reviewer process
 * restarts frequently (deploy churn), which would reset an in-memory counter and
 * defeat the breaker exactly as the system stabilizes. Durable state survives
 * restarts and is operator-queryable.
 *
 * A successful submission on the same (PR, head_sha) clears the row, so a
 * recovered HEAD re-opens the path.
 */

import {
  pgTable,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * One row per (owner, repo, pr_number, head_sha) that has hit at least one
 * non-retryable submission failure. The UNIQUE constraint enables an upsert
 * (INSERT ... ON CONFLICT DO UPDATE) that increments consecutive_count.
 */
export const submissionFailuresTable = pgTable(
  "reviewer_submission_failures",
  {
    /** Surrogate PK generated by Postgres. */
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),

    /** GitHub repository owner (org or user login). */
    owner: text("owner").notNull(),

    /** GitHub repository name. */
    repo: text("repo").notNull(),

    /** Pull request number within the repository. */
    prNumber: integer("pr_number").notNull(),

    /** Git SHA of the PR head commit at failure time. */
    headSha: text("head_sha").notNull(),

    /**
     * Classification of the most recent failure (e.g. "non_retryable_4xx").
     * Stored for operator triage and for the alert payload.
     */
    errorClass: text("error_class").notNull(),

    /** HTTP status of the most recent failure (e.g. 422), when known. */
    lastStatus: integer("last_status"),

    /** Human-readable message of the most recent failure (truncated). */
    lastMessage: text("last_message"),

    /** Count of consecutive non-retryable failures at this (PR, head_sha). */
    consecutiveCount: integer("consecutive_count").notNull().default(1),

    /** True once consecutive_count reaches the circuit-breaker threshold. */
    circuitOpen: boolean("circuit_open").notNull().default(false),

    /**
     * True once the one-shot operator alert has been emitted for this open
     * circuit, so the sweeper does not re-alert every cycle.
     */
    alerted: boolean("alerted").notNull().default(false),

    /** Timestamp of the first failure recorded for this row (UTC). */
    firstFailureAt: timestamp("first_failure_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),

    /** Timestamp of the most recent failure recorded for this row (UTC). */
    lastFailureAt: timestamp("last_failure_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),
  },
  (table) => ({
    /** Upsert key: at most one row per (owner, repo, pr_number, head_sha). */
    uniqSubmissionFailurePrHead: uniqueIndex("uniq_submission_failure_pr_head").on(
      table.owner,
      table.repo,
      table.prNumber,
      table.headSha
    ),

    /** Fast lookup of open circuits during the sweep cycle. */
    byCircuitOpen: index("idx_rsf_circuit_open").on(table.circuitOpen),
  })
);

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

export type SubmissionFailureRecord = typeof submissionFailuresTable.$inferSelect;
export type SubmissionFailureInsert = typeof submissionFailuresTable.$inferInsert;
