/**
 * Drizzle schema for reviewer_webhook_events table.
 *
 * Owned by the reviewer service. No imports from src/.
 *
 * Records every incoming webhook the reviewer service receives, including
 * the full processing outcome as the request progresses through the pipeline.
 * This enables forensic investigation of missed reviews without relying on
 * aged-out GitHub App delivery history or Railway log retention limits.
 *
 * See mt#1372 for the forward-instrumentation rescope and
 * docs/incidents/reviewer-webhook-investigation.md for the post-mortem flow.
 */

import { pgTable, uuid, text, jsonb, timestamp, index, pgEnum } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// ---------------------------------------------------------------------------
// Processing outcome enum
// ---------------------------------------------------------------------------

/**
 * Processing stages for a webhook event.
 *
 * The outcome column tracks the furthest stage reached. On failure the column
 * stores the failure-stage variant (e.g. "failed_at_tier_resolve") so an
 * investigator can pinpoint exactly where processing stopped.
 *
 * - received:           Webhook arrived and signature was verified.
 * - tier_resolved:      Tier routing decision was made (skip or review).
 * - reviewer_called:    runReview was dispatched (detached promise started).
 * - review_submitted:   runReview completed with status "reviewed".
 * - skipped:            Webhook was intentionally skipped (draft, tier=skip, etc.).
 * - failed_at_signature:     Signature verification failed.
 * - failed_at_tier_resolve:  Tier routing threw / panicked.
 * - failed_at_reviewer:      runReview threw or returned non-reviewed status.
 */
export const webhookOutcomeEnum = pgEnum("webhook_outcome", [
  "received",
  "tier_resolved",
  "reviewer_called",
  "review_submitted",
  "skipped",
  "failed_at_signature",
  "failed_at_tier_resolve",
  "failed_at_reviewer",
]);

export type WebhookOutcome = (typeof webhookOutcomeEnum.enumValues)[number];

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * One row per incoming GitHub webhook delivery.
 *
 * Delivery ID is unique per GitHub delivery (re-deliveries share the same
 * delivery ID). UPSERT semantics are used on insert to handle re-deliveries
 * idempotently — a re-delivered webhook refreshes the row rather than
 * creating a duplicate.
 */
export const webhookEventsTable = pgTable(
  "reviewer_webhook_events",
  {
    /** Surrogate PK generated by Postgres. */
    id: uuid("id")
      .default(sql`gen_random_uuid()`)
      .primaryKey(),

    /**
     * GitHub X-GitHub-Delivery header value.
     * Unique per GitHub delivery (re-deliveries reuse the same ID).
     * Used as the idempotency key for UPSERT on re-delivery.
     */
    deliveryId: text("delivery_id").notNull().unique(),

    /**
     * GitHub X-GitHub-Event header value (e.g. "pull_request", "push").
     */
    eventType: text("event_type").notNull(),

    /**
     * Subset of HTTP headers relevant for forensic investigation.
     * Stored as JSONB. Includes: x-github-delivery, x-github-event,
     * x-hub-signature-256 (truncated to 12 chars for privacy), user-agent.
     */
    headers: jsonb("headers").notNull(),

    /**
     * The parsed JSON body of the webhook payload.
     * Stored as JSONB for queryability (e.g. WHERE body->>'action' = 'synchronize').
     * Falls back to { raw: "<body-text>" } when the body is not valid JSON.
     */
    body: jsonb("body").notNull(),

    /**
     * The furthest processing stage reached for this delivery.
     * Updated as the webhook progresses through the pipeline.
     */
    outcome: webhookOutcomeEnum("outcome").notNull().default("received"),

    /**
     * Error details when the outcome is a failure variant.
     * Null when processing succeeded or is still in progress.
     * Stored as JSONB to allow structured error context (message, stage, etc.).
     */
    errorDetails: jsonb("error_details"),

    /**
     * Timestamp when the row was first inserted (UTC).
     * Used for retention pruning: rows older than MINSKY_REVIEWER_WEBHOOK_EVENT_RETENTION_DAYS
     * (default: 90) are pruned by the periodic retention job.
     */
    receivedAt: timestamp("received_at", { withTimezone: true })
      .default(sql`now()`)
      .notNull(),

    /**
     * Timestamp when the final outcome was recorded (UTC).
     * Null until the pipeline reaches a terminal stage (submitted, skipped, or failed).
     */
    processedAt: timestamp("processed_at", { withTimezone: true }),
  },
  (table) => ({
    /** Primary forensic lookup: find a delivery by its GitHub delivery ID. */
    byDeliveryId: index("idx_rwe_delivery_id").on(table.deliveryId),

    /** Time-window queries (dashboards, retention pruning). */
    byReceivedAt: index("idx_rwe_received_at").on(table.receivedAt),

    /** Failure investigation: find all failed deliveries. */
    byOutcome: index("idx_rwe_outcome").on(table.outcome),
  })
);

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

export type WebhookEventRecord = typeof webhookEventsTable.$inferSelect;
export type WebhookEventInsert = typeof webhookEventsTable.$inferInsert;
