version: 1

# Task Backend Configuration - GitHub Issues backend auto-detects repository from git remote
backend: "github-issues"
    
# SessionDB Configuration
sessiondb:
  backend: "json"
  json:
    baseDir: "~/.local/state/minsky"
