version: 1

# Task Backend Configuration - GitHub Issues backend will error out  
backend: "github-issues"

# Override AI config to avoid validation errors from main workspace
ai:
  defaultProvider: "openai"
  providers:
    openai:
      enabled: true
      model: "gpt-4"
    
# SessionDB Configuration  
sessiondb:
  backend: "json"
  json:
    baseDir: "~/.local/state/minsky"
