version: 1
backend: markdown

# AI Provider Configuration for Testing
ai:
  defaultProvider: morph
  providers:
    morph:
      enabled: true
      apiKey: "test-morph-key-placeholder"  # This will be replaced with real key in environment
      baseUrl: "https://api.morphllm.com/v1"
      model: "morph-v3-large"
    
    # Keep OpenAI as fallback for testing
    openai:
      enabled: false  # Disabled for now to focus on Morph testing
      apiKey: "test-openai-key-placeholder"
      model: "gpt-4"

sessiondb:
  backend: sqlite
