/**
 * AGENTS.md Compile Target
 *
 * Compiles rules into a monolithic AGENTS.md file using section mapping and
 * always-apply rule collection.
 */

import { join } from "path";
import * as fs from "fs/promises";
import { classifyRuleType, RuleType } from "../../rule-classifier";
import type { Rule } from "../../types";
import type { CompileTarget, CompileResult, TargetOptions } from "../types";
import { evaluateSizeBudget } from "../../../compile/size-budget";
import { DEFAULT_AGENTS_MD_SIZE_BUDGET } from "../../../compile/agents-md-size-budget";

// `DEFAULT_AGENTS_MD_SIZE_BUDGET` is imported (not declared here) so both
// this legacy target and the new pipeline's `agents-md.ts` share one
// threshold and cannot silently re-diverge (mt#3076 — see
// `agents-md-size-budget.ts` for the full rationale, including why the
// thresholds were raised well above the mt#2802 originals).
export { DEFAULT_AGENTS_MD_SIZE_BUDGET };

/**
 * Default section mapping for AGENTS.md target
 */
// mt#2868: "Minsky Workflow" section and the "pr-preparation-workflow" entry
// removed — both ids were orphan .cursor/rules/*.mdc files with no
// .minsky/rules/ source (minsky-workflow, minsky-workflow-orchestrator,
// pr-preparation-workflow). Their content is superseded by the skill chain
// (/implement-task, /prepare-pr) and preserved in git history.
const DEFAULT_AGENTS_MD_SECTIONS: Record<string, string[]> = {
  "Build & Test": ["bun_over_node", "tests"],
  "Code Style": ["comments", "constants-management", "ensure-ascii-code-symbols"],
  Architecture: ["domain-oriented-modules", "architecture"],
  Testing: ["testing-standards", "test-infrastructure", "testing-boundaries"],
  "Git & PR Workflow": ["pr-description-guidelines"],
  Boundaries: ["operational-safety-dry-run-first", "terminal-command-best-practices"],
};

/**
 * Build compiled content from rules and section mapping
 */
function buildContent(
  allRules: Rule[],
  sectionMapping: Record<string, string[]>
): { content: string; rulesIncluded: string[]; rulesSkipped: string[] } {
  // Build a lookup map by rule ID
  const ruleMap = new Map<string, Rule>();
  for (const rule of allRules) {
    ruleMap.set(rule.id, rule);
  }

  // Build set of all explicitly mapped rule IDs
  const mappedRuleIds = new Set<string>();
  for (const ruleIds of Object.values(sectionMapping)) {
    for (const id of ruleIds) {
      mappedRuleIds.add(id);
    }
  }

  // Track inclusion
  const rulesIncluded: string[] = [];

  // Collect rules by section
  const sectionContents: Array<{ sectionName: string; rules: Rule[] }> = [];

  for (const [sectionName, ruleIds] of Object.entries(sectionMapping)) {
    const sectionRules: Rule[] = [];
    for (const ruleId of ruleIds) {
      const rule = ruleMap.get(ruleId);
      if (rule) {
        sectionRules.push(rule);
        rulesIncluded.push(ruleId);
      }
      // If rule not found, silently skip
    }
    if (sectionRules.length > 0) {
      sectionContents.push({ sectionName, rules: sectionRules });
    }
  }

  // Collect alwaysApply rules not already in a section
  const generalRules: Rule[] = [];
  for (const rule of allRules) {
    if (!mappedRuleIds.has(rule.id)) {
      const ruleType = classifyRuleType(rule);
      if (ruleType === RuleType.ALWAYS_APPLY) {
        generalRules.push(rule);
        rulesIncluded.push(rule.id);
      }
    }
  }

  // Track skipped rules (those not included)
  const rulesSkipped: string[] = [];
  for (const rule of allRules) {
    if (!rulesIncluded.includes(rule.id)) {
      rulesSkipped.push(rule.id);
    }
  }

  // Build the output string
  const lines: string[] = [];

  lines.push("<!-- Generated by minsky rules compile. Do not edit directly. -->");
  lines.push("");
  lines.push("# Project Instructions");
  lines.push("");

  for (const { sectionName, rules } of sectionContents) {
    lines.push(`## ${sectionName}`);
    lines.push("");
    for (const rule of rules) {
      const content = rule.content.trim();
      if (content) {
        lines.push(content);
        lines.push("");
      }
    }
  }

  if (generalRules.length > 0) {
    lines.push("## General");
    lines.push("");
    for (const rule of generalRules) {
      const content = rule.content.trim();
      if (content) {
        lines.push(content);
        lines.push("");
      }
    }
  }

  const content = lines.join("\n");

  return { content, rulesIncluded, rulesSkipped };
}

/**
 * AGENTS.md compile target implementation
 */
export const agentsMdTarget: CompileTarget = {
  id: "agents.md",
  displayName: "AGENTS.md",

  defaultOutputPath(workspacePath: string): string {
    return join(workspacePath, "AGENTS.md");
  },

  listOutputFiles(_rules: Rule[], options: TargetOptions, workspacePath: string): string[] {
    return [options.outputPath || this.defaultOutputPath(workspacePath)];
  },

  async compile(
    rules: Rule[],
    options: TargetOptions,
    workspacePath: string
  ): Promise<CompileResult> {
    const outputPath = options.outputPath || this.defaultOutputPath(workspacePath);

    // Use default section mapping (can be extended via options in future)
    const sectionMapping = DEFAULT_AGENTS_MD_SECTIONS;

    const { content, rulesIncluded, rulesSkipped } = buildContent(rules, sectionMapping);

    // Evaluate BEFORE writing — same ordering rationale as claude-md.ts
    // (evaluation must describe the exact emitted content; reviewer R1).
    const sizeEvaluation = evaluateSizeBudget({
      sizeChars: content.length,
      rules,
      includedIds: rulesIncluded,
      defaultBudget: DEFAULT_AGENTS_MD_SIZE_BUDGET,
      override: options.sizeBudget,
    });

    await fs.writeFile(outputPath, content, "utf-8");

    return {
      target: this.id,
      filesWritten: [outputPath],
      rulesIncluded,
      rulesSkipped,
      sizeChars: sizeEvaluation.sizeChars,
      sizeBudget: sizeEvaluation.budget,
      sizeBudgetStatus: sizeEvaluation.status,
      topContributors: sizeEvaluation.topContributors,
      ruleContentChars: sizeEvaluation.ruleContentChars,
    };
  },
};

// Export helpers for testing
export { buildContent, DEFAULT_AGENTS_MD_SECTIONS };
