/**
 * CLAUDE.md Compile Target
 *
 * Compiles rules into a CLAUDE.md file. By default, only includes ALWAYS_APPLY rules.
 *
 * The `memory-usage` rule (id: "memory-usage", tag: "memory") is always-apply by default,
 * but is suppressed when `memoryLoadingMode` is `"legacy"`. This allows a soft-transition
 * window where operators can fall back to MEMORY.md preamble loading.
 */

import { join } from "path";
import * as fs from "fs/promises";
import { classifyRuleType, RuleType } from "../../rule-classifier";
import type { Rule } from "../../types";
import type { CompileTarget, CompileResult, TargetOptions } from "../types";
import {
  evaluateSizeBudget,
  DEFAULT_PER_RULE_CEILING_CHARS,
  type SizeBudget,
} from "../../../compile/size-budget";

/** The canonical rule ID for the memory-usage directive. */
const MEMORY_USAGE_RULE_ID = "memory-usage";

/**
 * Default size budget for CLAUDE.md (mt#2802).
 *
 * Grounded in the 2026-07-15 planning calibration: `failChars` sits with
 * margin under the ~150k harness advisory threshold Claude Code applies for
 * 1M-context models; `warnChars` sits ~13% above the post-mt#1876/mt#1877
 * baseline (~101.7k chars) so it fires after a few rule additions, not
 * immediately (observed growth increment: ~3.3k/rule-addition, mt#2801).
 *
 * `failChars` raised 140k -> 145k on 2026-07-22 (mt#3061), operator-decided.
 * The corpus reached 141,178 chars that day and the fail gate began blocking
 * EVERY rule commit — including size-REDUCING ones, which is how it surfaced:
 * mt#3061 is a net -14 change and could not land. Blocking the changes that
 * shrink the corpus is the one outcome the gate should never produce.
 *
 * This is explicitly the second of the two dispositions mt#3052 sanctions
 * ("trim toward 115K, or raise the threshold with a recorded rationale") and
 * is NOT a substitute for the trim. `warnChars` is deliberately left at 115k
 * so the standing warning keeps firing on every compile — the corpus is still
 * ~23% over where it should be (141,178 vs the 115,000 warn line), and mt#3052
 * still owns bringing it down.
 *
 * The ~150k harness advisory remains the real ceiling: this leaves ~5k of
 * headroom, which is roughly ONE more rule addition. The next change to hit
 * this gate should trim rather than raise again.
 */
export const DEFAULT_CLAUDE_MD_SIZE_BUDGET: SizeBudget = {
  warnChars: 115_000,
  failChars: 145_000,
};

/**
 * Build CLAUDE.md content from always-apply rules.
 *
 * @param allRules - All rules available from the rule service
 * @param options - Optional target options; `memoryLoadingMode` controls memory directive emission
 */
function buildClaudeMdContent(
  allRules: Rule[],
  options?: Pick<TargetOptions, "memoryLoadingMode">
): {
  content: string;
  rulesIncluded: string[];
  rulesSkipped: string[];
} {
  const rulesIncluded: string[] = [];
  const rulesSkipped: string[] = [];

  const memoryLoadingMode = options?.memoryLoadingMode ?? "on_demand";

  // Filter to only ALWAYS_APPLY rules by default
  const alwaysApplyRules: Rule[] = [];
  for (const rule of allRules) {
    const ruleType = classifyRuleType(rule);
    if (ruleType === RuleType.ALWAYS_APPLY) {
      // In legacy mode, suppress the memory-usage directive so the MEMORY.md preamble takes effect
      if (memoryLoadingMode === "legacy" && rule.id === MEMORY_USAGE_RULE_ID) {
        rulesSkipped.push(rule.id);
        continue;
      }
      alwaysApplyRules.push(rule);
      rulesIncluded.push(rule.id);
    } else {
      rulesSkipped.push(rule.id);
    }
  }

  const lines: string[] = [];

  lines.push("<!-- Generated by minsky rules compile. Do not edit directly. -->");
  lines.push("");
  lines.push("# Project Instructions");
  lines.push("");

  for (const rule of alwaysApplyRules) {
    const content = rule.content.trim();
    if (content) {
      lines.push(content);
      lines.push("");
    }
  }

  const content = lines.join("\n");

  return { content, rulesIncluded, rulesSkipped };
}

/**
 * CLAUDE.md compile target implementation
 */
export const claudeMdTarget: CompileTarget = {
  id: "claude.md",
  displayName: "CLAUDE.md",

  defaultOutputPath(workspacePath: string): string {
    return join(workspacePath, "CLAUDE.md");
  },

  listOutputFiles(_rules: Rule[], options: TargetOptions, workspacePath: string): string[] {
    return [options.outputPath || this.defaultOutputPath(workspacePath)];
  },

  async compile(
    rules: Rule[],
    options: TargetOptions,
    workspacePath: string
  ): Promise<CompileResult> {
    const outputPath = options.outputPath || this.defaultOutputPath(workspacePath);

    const { content, rulesIncluded, rulesSkipped } = buildClaudeMdContent(rules, options);

    // Evaluate BEFORE writing so the reported evaluation always describes the
    // exact content string being emitted, and a failed/partial write can't
    // yield an evaluation that doesn't match what's on disk (reviewer R1).
    const sizeEvaluation = evaluateSizeBudget({
      sizeChars: content.length,
      rules,
      includedIds: rulesIncluded,
      defaultBudget: DEFAULT_CLAUDE_MD_SIZE_BUDGET,
      override: options.sizeBudget,
      // mt#2874: per-rule 15K ceiling — claude.md only, per the spec's scope.
      perRuleCeiling: DEFAULT_PER_RULE_CEILING_CHARS,
    });

    await fs.writeFile(outputPath, content, "utf-8");

    return {
      target: this.id,
      filesWritten: [outputPath],
      rulesIncluded,
      rulesSkipped,
      sizeChars: sizeEvaluation.sizeChars,
      sizeBudget: sizeEvaluation.budget,
      sizeBudgetStatus: sizeEvaluation.status,
      topContributors: sizeEvaluation.topContributors,
      ruleContentChars: sizeEvaluation.ruleContentChars,
      perRuleViolations: sizeEvaluation.perRuleViolations,
    };
  },
};

// Export helpers for testing
export { buildClaudeMdContent };
