/**
 * Rules CRUD Operations
 *
 * Functions for listing, getting, creating, updating, generating, and compiling rules.
 */

import nodeFs from "fs/promises";
import path from "path";
import { RuleService, type RuleFormat, type RuleServiceFs } from "../../rules";
import { createRuleTemplateService } from "../rule-template-service";
import { type RuleGenerationConfig } from "../template-system";
import { readContentFromFileIfExists, parseGlobs } from "../../utils/rules-helpers";
import type { CompileService } from "../compile/compile-service";
import type {
  ListRulesOptions,
  ListRulesResult,
  CompileRulesOptions,
  CompileRulesResult,
  CompileRulesTargetResult,
  GetRuleOptions,
  GetRuleResult,
  GenerateRulesOptions,
  GenerateRulesResult,
  CreateRuleOptions,
  CreateRuleResult,
  UpdateRuleOptions,
  UpdateRuleResult,
} from "./types";

// ─── List Rules ──────────────────────────────────────────────────────────────

/**
 * List rules with optional time-range filtering.
 * Time filtering uses file modification time as a proxy for updatedAt.
 */
export async function listRulesFiltered(options: ListRulesOptions): Promise<ListRulesResult> {
  const ruleService = new RuleService(options.workspacePath);

  const rules = await ruleService.listRules({
    format: options.format,
    tag: options.tag,
    debug: options.debug,
  });

  // Optional time filtering using file modification time as proxy
  type RuleWithUpdatedAt = (typeof rules)[0] & { updatedAt?: Date };
  let filtered: RuleWithUpdatedAt[] = rules;
  try {
    const { parseTime, filterByTimeRange } = await import(
      "../../../../../src/utils/result-handling/filters"
    );
    const sinceTs = parseTime(options.since);
    const untilTs = parseTime(options.until);
    if (sinceTs !== null || untilTs !== null) {
      const withUpdatedAt = await Promise.all(
        rules.map(async (rule): Promise<RuleWithUpdatedAt> => {
          try {
            const stat = await nodeFs.stat(rule.path);
            return { ...rule, updatedAt: new Date(stat.mtimeMs) };
          } catch {
            return { ...rule };
          }
        })
      );
      filtered = filterByTimeRange(withUpdatedAt, sinceTs, untilTs);
    }
  } catch {
    // ignore filtering errors
  }

  // Transform rules to exclude content field for better usability
  const rulesWithoutContent = filtered.map(({ content, ...rule }) => rule);

  return { success: true, rules: rulesWithoutContent };
}

// ─── Compile Rules ───────────────────────────────────────────────────────────

/**
 * Generated-banner header emitted by the legacy `rules compile` targets
 * (agents.md, claude.md) on their first output line. Used only to detect
 * whether a target's output already exists on disk for bare-invocation
 * target-probing (mt#2803) — intentionally duplicated from
 * `runRulesCompileCheck`'s `COMPILE_HEADER` constant (src/hooks/pre-commit.ts)
 * rather than imported: that file already imports from `@minsky/domain`, so
 * an import in the other direction would be circular. Keep the two literals
 * in sync if the banner text ever changes.
 */
const LEGACY_COMPILE_HEADER = "<!-- Generated by minsky rules compile.";

/**
 * Probe which legacy `rules compile` targets already have generated output on
 * disk, mirroring `runRulesCompileCheck`'s target-detection logic
 * (src/hooks/pre-commit.ts). Drives the bare (no `--target`) invocation's
 * default target set (mt#2803):
 *
 * - "agents.md": AGENTS.md exists and starts with the generated banner
 * - "claude.md": CLAUDE.md exists and starts with the generated banner
 * - "cursor-rules": .cursor/rules/ exists with at least one .mdc file
 *
 * Returns an empty array when none exist (fresh repo) — callers fall back to
 * the single "agents.md" default in that case, matching pre-mt#2803 behavior
 * for init flows. Exported for unit testing.
 */
export async function probeLegacyCompileTargets(
  workspacePath: string,
  fs: RuleServiceFs
): Promise<string[]> {
  const targets: string[] = [];

  try {
    const agentsContent = await fs.readFile(path.join(workspacePath, "AGENTS.md"), "utf-8");
    if (String(agentsContent).startsWith(LEGACY_COMPILE_HEADER)) {
      targets.push("agents.md");
    }
  } catch {
    // File doesn't exist or isn't readable — skip
  }

  try {
    const claudeContent = await fs.readFile(path.join(workspacePath, "CLAUDE.md"), "utf-8");
    if (String(claudeContent).startsWith(LEGACY_COMPILE_HEADER)) {
      targets.push("claude.md");
    }
  } catch {
    // File doesn't exist or isn't readable — skip
  }

  try {
    const entries = await fs.readdir(path.join(workspacePath, ".cursor", "rules"));
    if (entries.some((e) => e.endsWith(".mdc"))) {
      targets.push("cursor-rules");
    }
  } catch {
    // Directory doesn't exist — skip
  }

  return targets;
}

/**
 * Compile exactly one target. Holds the full check-mode / regular-mode logic
 * previously inlined directly in `compileRules` — extracted so the bare-
 * invocation multi-target loop (mt#2803) can invoke it once per probed
 * target while `compileRules` itself stays a thin dispatcher.
 */
async function compileSingleTarget(
  targetId: string,
  options: CompileRulesOptions,
  ruleService: RuleService,
  compileService: CompileService,
  fs: RuleServiceFs
): Promise<CompileRulesResult> {
  // For check mode, do a dry-run first to get the compiled content, then compare on disk
  if (options.check) {
    const dryResult = await compileService.compile(ruleService, targetId, {
      workspacePath: options.workspacePath,
      outputPath: options.output,
      dryRun: true,
      memoryLoadingMode: options.memoryLoadingMode,
      sizeBudget: options.sizeBudget,
    });

    // Get the registered target so we can call listOutputFiles (generalized target map)
    const target = compileService.getTarget(targetId);
    if (!target) {
      throw new Error(`Unknown compile target: "${targetId}"`);
    }

    // Get the rule set once — used for listOutputFiles and cursor-rules per-file content
    let allRules = await ruleService.listRules({});

    // For cursor-rules, exclude rules whose .cursor/rules/<id>.mdc file is owned by the
    // cursor-rules-ts target (TS-sourced rules in .minsky/rules/<name>/rule.ts subdirs).
    // .cursor/rules/ is a shared output directory — the legacy check should not try to
    // re-serialize or orphan-flag files generated by the TS-first pipeline.
    if (targetId === "cursor-rules") {
      const tsSrcDir = path.join(options.workspacePath, ".minsky", "rules");
      const tsOwnedIds = new Set<string>();
      try {
        const ruleDirs = await fs.readdir(tsSrcDir);
        for (const dirEntry of ruleDirs) {
          const ruleTsPath = path.join(tsSrcDir, dirEntry, "rule.ts");
          try {
            await fs.access(ruleTsPath);
            tsOwnedIds.add(dirEntry);
          } catch {
            // No rule.ts — not a TS-sourced rule dir
          }
        }
      } catch {
        // .minsky/rules/ doesn't exist — skip
      }
      if (tsOwnedIds.size > 0) {
        allRules = allRules.filter((r) => !tsOwnedIds.has(r.id));
      }
    }

    // Determine which files this target would write
    const expectedFiles = target.listOutputFiles(
      allRules,
      { outputPath: options.output },
      options.workspacePath
    );

    // Check every expected output file for staleness
    let staleFile: string | undefined;

    // For cursor-rules, build the per-file content map once outside the loop
    let cursorFilesMap: Map<string, string> | undefined;
    if (targetId === "cursor-rules") {
      const { buildCursorRulesContent } = await import("../compile/targets/cursor-rules");
      const outputDir = options.output || target.defaultOutputPath(options.workspacePath);
      const { files } = buildCursorRulesContent(allRules, outputDir);
      cursorFilesMap = new Map(files.map((f) => [f.path, f.content]));
    }

    for (const filePath of expectedFiles) {
      let existingContent: string;
      try {
        existingContent = String(await fs.readFile(filePath, "utf-8"));
      } catch {
        // File doesn't exist — stale
        staleFile = filePath;
        break;
      }

      // For single-file targets, dryResult.content holds the full content.
      // For cursor-rules (multi-file), use the pre-built per-file content map.
      let expectedContent: string | undefined;
      if (targetId === "cursor-rules") {
        expectedContent = cursorFilesMap?.get(filePath);
      } else {
        expectedContent = dryResult.content;
      }

      if (expectedContent === undefined || existingContent !== expectedContent) {
        staleFile = filePath;
        break;
      }
    }

    // For cursor-rules, also detect orphan .mdc files: files in the output dir that
    // the current compile would NOT produce (stale removals).
    if (!staleFile && targetId === "cursor-rules") {
      const outputDir = options.output || target.defaultOutputPath(options.workspacePath);
      try {
        const entries = await fs.readdir(outputDir);
        const expectedSet = new Set(expectedFiles.map((f) => path.basename(f)));

        // Also include files owned by the cursor-rules-ts target (TS-sourced rules in
        // .minsky/rules/<name>/rule.ts subdirs). .cursor/rules/ is a shared output
        // directory — these files should not be flagged as orphans by the legacy check.
        const tsSrcDir = path.join(options.workspacePath, ".minsky", "rules");
        try {
          const ruleDirs = await fs.readdir(tsSrcDir);
          for (const dirEntry of ruleDirs) {
            const ruleTsPath = path.join(tsSrcDir, dirEntry, "rule.ts");
            try {
              await fs.access(ruleTsPath);
              expectedSet.add(`${dirEntry}.mdc`);
            } catch {
              // No rule.ts — not a TS-sourced rule dir
            }
          }
        } catch {
          // .minsky/rules/ doesn't exist or not readable — skip TS-source discovery
        }

        for (const entry of entries) {
          if (entry.endsWith(".mdc") && !expectedSet.has(entry)) {
            staleFile = path.join(outputDir, entry);
            break;
          }
        }
      } catch {
        // Directory doesn't exist — already handled above via expectedFiles check
      }
    }

    const isStale = staleFile !== undefined;
    return {
      success: true,
      target: targetId,
      check: true,
      stale: isStale,
      staleFile: staleFile,
      rulesIncluded: dryResult.rulesIncluded,
      rulesSkipped: dryResult.rulesSkipped,
      sizeChars: dryResult.sizeChars,
      sizeBudget: dryResult.sizeBudget,
      sizeBudgetStatus: dryResult.sizeBudgetStatus,
      topContributors: dryResult.topContributors,
      ruleContentChars: dryResult.ruleContentChars,
    };
  }

  const result = await compileService.compile(ruleService, targetId, {
    workspacePath: options.workspacePath,
    outputPath: options.output,
    dryRun: options.dryRun || false,
    memoryLoadingMode: options.memoryLoadingMode,
    sizeBudget: options.sizeBudget,
  });

  if (options.dryRun) {
    return {
      success: true,
      target: targetId,
      dryRun: true,
      content: result.content,
      filesWritten: result.filesWritten,
      rulesIncluded: result.rulesIncluded,
      rulesSkipped: result.rulesSkipped,
      sizeChars: result.sizeChars,
      sizeBudget: result.sizeBudget,
      sizeBudgetStatus: result.sizeBudgetStatus,
      topContributors: result.topContributors,
      ruleContentChars: result.ruleContentChars,
    };
  }

  return {
    success: true,
    target: targetId,
    dryRun: false,
    filesWritten: result.filesWritten,
    rulesIncluded: result.rulesIncluded,
    rulesSkipped: result.rulesSkipped,
    sizeChars: result.sizeChars,
    sizeBudget: result.sizeBudget,
    sizeBudgetStatus: result.sizeBudgetStatus,
    topContributors: result.topContributors,
    ruleContentChars: result.ruleContentChars,
  };
}

/**
 * Compile rules into a monolithic file, with optional check (staleness) mode.
 *
 * With an explicit `options.target`, compiles exactly that one target
 * (unchanged behavior). On a bare invocation (no `target`), probes which
 * targets already have generated output on disk (mt#2803,
 * {@link probeLegacyCompileTargets}) and compiles every one of them so a
 * partial regen is never silently reported as success — mirroring
 * `runRulesCompileCheck`'s target-detection logic. When no target has
 * existing output (fresh repo), falls back to the single "agents.md"
 * default so `minsky init` flows keep working.
 *
 * When the probe resolves to more than one target, the top-level result
 * fields (`filesWritten`, `rulesIncluded`, `rulesSkipped`) are the
 * concatenation across targets, `success`/`stale` are aggregated (AND / OR
 * respectively), and the new `targets` field carries the full per-target
 * breakdown. Single-target invocations (explicit `--target`, or a bare
 * invocation that probes to exactly one target) return the classic
 * single-target shape unchanged — `targets` is only populated in the
 * multi-target case.
 *
 * `deps` exists so tests can inject an in-memory fs (and optionally a pre-built
 * RuleService) without touching the real filesystem. `fs` uses the same
 * RuleServiceFs shape so a single mock can flow into both this function and
 * any internally-constructed RuleService.
 */
export async function compileRules(
  options: CompileRulesOptions,
  deps?: {
    fs?: RuleServiceFs;
    ruleService?: RuleService;
  }
): Promise<CompileRulesResult> {
  const { createCompileService } = await import("../compile/compile-service");

  const fs: RuleServiceFs = deps?.fs ?? (nodeFs as RuleServiceFs);
  const ruleService =
    deps?.ruleService ??
    new RuleService(options.workspacePath, {
      fsPromises: deps?.fs,
    });
  const compileService = createCompileService();

  if (options.target) {
    return compileSingleTarget(options.target, options, ruleService, compileService, fs);
  }

  // mt#2803: bare invocation — regenerate every applicable target instead of
  // silently compiling only the single legacy default.
  const probedTargets = await probeLegacyCompileTargets(options.workspacePath, fs);
  const targetIds = probedTargets.length > 0 ? probedTargets : ["agents.md"];

  const [onlyTargetId] = targetIds;
  if (targetIds.length === 1 && onlyTargetId) {
    return compileSingleTarget(onlyTargetId, options, ruleService, compileService, fs);
  }

  const targets: CompileRulesTargetResult[] = [];
  const filesWritten: string[] = [];
  const rulesIncluded: string[] = [];
  const rulesSkipped: string[] = [];
  let overallSuccess = true;
  let anyStale = false;

  for (const targetId of targetIds) {
    const single = await compileSingleTarget(targetId, options, ruleService, compileService, fs);
    targets.push({ target: targetId, ...single });
    if (!single.success) overallSuccess = false;
    if (single.stale) anyStale = true;
    if (single.filesWritten) filesWritten.push(...single.filesWritten);
    if (single.rulesIncluded) rulesIncluded.push(...single.rulesIncluded);
    if (single.rulesSkipped) rulesSkipped.push(...single.rulesSkipped);
  }

  return {
    success: overallSuccess,
    target: targetIds.join(", "),
    check: options.check,
    stale: options.check ? anyStale : undefined,
    dryRun: options.dryRun,
    filesWritten,
    rulesIncluded,
    rulesSkipped,
    targets,
  };
}

// ─── Get Rule ────────────────────────────────────────────────────────────────

/**
 * Get a specific rule by ID.
 */
export async function getRule(options: GetRuleOptions): Promise<GetRuleResult> {
  const ruleService = new RuleService(options.workspacePath);
  const rule = await ruleService.getRule(options.id, {
    format: options.format,
    debug: options.debug,
  });
  return { success: true, rule };
}

// ─── Generate Rules ──────────────────────────────────────────────────────────

/**
 * Generate rules from templates.
 */
export async function generateRules(options: GenerateRulesOptions): Promise<GenerateRulesResult> {
  const ruleTemplateService = createRuleTemplateService(options.workspacePath);
  await ruleTemplateService.registerDefaultTemplates();

  const config: RuleGenerationConfig = {
    interface: (options.interface || "cli") as "cli" | "mcp" | "hybrid",
    mcpEnabled: options.interface === "mcp" || options.interface === "hybrid",
    mcpTransport: (options.mcpTransport || "stdio") as "stdio" | "http",
    preferMcp: options.preferMcp || false,
    ruleFormat: (options.format || "minsky") as RuleFormat,
    outputDir:
      options.outputDir ||
      (options.format === "cursor"
        ? ".cursor/rules"
        : options.format === "generic"
          ? ".ai/rules"
          : ".minsky/rules"),
  };

  const selectedRules = options.rules ? options.rules.split(",").map((t) => t.trim()) : undefined;
  const dryRun = options.dryRun || false;
  const overwrite = options.overwrite || false;

  const result = await ruleTemplateService.generateRules({
    config,
    selectedRules,
    dryRun,
    overwrite,
  });
  return {
    success: result.success,
    rules: result.rules,
    errors: result.errors,
    generated: result.rules.length,
  };
}

// ─── Create Rule ─────────────────────────────────────────────────────────────

/**
 * Create a new rule.
 */
export async function createRule(options: CreateRuleOptions): Promise<CreateRuleResult> {
  const ruleService = new RuleService(options.workspacePath);
  const content = await readContentFromFileIfExists(options.content);
  const globs = parseGlobs(options.globs);
  const tags = options.tags ? options.tags.split(",").map((tag: string) => tag.trim()) : undefined;

  const meta = {
    name: options.name || options.id,
    description: options.description,
    globs,
    tags,
  };

  const rule = await ruleService.createRule(options.id, content, meta, {
    format: options.format,
    overwrite: options.overwrite,
  });

  return { success: true, rule };
}

// ─── Update Rule ─────────────────────────────────────────────────────────────

/**
 * Update an existing rule.
 */
export async function updateRule(options: UpdateRuleOptions): Promise<UpdateRuleResult> {
  const ruleService = new RuleService(options.workspacePath);
  const content = options.content ? await readContentFromFileIfExists(options.content) : undefined;
  const globs = options.globs ? parseGlobs(options.globs) : undefined;
  const tags = options.tags ? options.tags.split(",").map((tag: string) => tag.trim()) : undefined;

  const meta: Record<string, unknown> = {};
  if (options.name !== undefined) meta.name = options.name;
  if (options.description !== undefined) meta.description = options.description;
  if (globs !== undefined) meta.globs = globs;
  if (tags !== undefined) meta.tags = tags;

  const rule = await ruleService.updateRule(
    options.id,
    {
      content,
      meta: Object.keys(meta).length > 0 ? meta : undefined,
    },
    { format: options.format, debug: options.debug }
  );

  return { success: true, rule };
}
