/**
 * Unit tests for legacy-pipeline bare-invocation behavior across the mt#3058
 * cutover.
 *
 * Originally (mt#2803) these covered `probeLegacyCompileTargets` banner-based
 * detection and `compileRules`'s multi-target bare-invocation dispatch. The
 * mt#3058 cutover moved the three legacy targets (agents.md / claude.md /
 * claude-rules) to the new `compile` pipeline, so:
 *   - `probeLegacyCompileTargets` now ALWAYS returns [] — even when the
 *     generated banners are present on disk (the new pipeline emits the
 *     identical banner, so banner-detection cannot distinguish ownership).
 *   - a bare `compileRules` is a NO-OP (it must not fall back to writing
 *     AGENTS.md — that fallback was the dual-write the cutover removes).
 *   - explicit `--target agents.md|claude.md|claude-rules` still compiles,
 *     since it bypasses the probe (removal of the legacy command is mt#2996).
 */
/* eslint-disable custom/no-real-fs-in-tests -- the legacy compile targets
 * (agents-md.ts, claude-md.ts) hardcode `import * as fs from "fs/promises"`
 * internally with no injectable fs seam for the WRITE path (unlike the new
 * compile-pipeline targets, which do accept an injectable MinskyCompileFsDeps
 * — see compile.test.ts, which uses a fully in-memory fake). Testing the
 * bare-invocation behavior end-to-end therefore requires a real scratch
 * directory; mkdtemp() under the OS tmpdir + afterEach cleanup avoids the
 * race-condition/parallel-test concerns the rule guards against. */

import { describe, it, expect, afterEach } from "bun:test";
import { mkdtemp, mkdir, writeFile, readFile, rm, access } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";
import realFs from "fs/promises";
import { compileRules, probeLegacyCompileTargets } from "./crud-operations";
import type { RuleServiceFs } from "../../rules";

const GENERATED_BANNER = "<!-- Generated by minsky rules compile. Do not edit directly. -->";

async function makeScratchDir(): Promise<string> {
  return mkdtemp(join(tmpdir(), "mt3058-crud-ops-"));
}

let scratchDirs: string[] = [];

afterEach(async () => {
  await Promise.all(scratchDirs.map((dir) => rm(dir, { recursive: true, force: true })));
  scratchDirs = [];
});

async function withScratchDir(): Promise<string> {
  const dir = await makeScratchDir();
  scratchDirs.push(dir);
  return dir;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

describe("probeLegacyCompileTargets (mt#3058: retired, always returns [])", () => {
  it("returns an empty array for a fresh repo with no generated outputs", async () => {
    const workspacePath = await withScratchDir();
    const targets = await probeLegacyCompileTargets(workspacePath, realFs as RuleServiceFs);
    expect(targets).toEqual([]);
  });

  it("returns [] even when AGENTS.md carries the generated banner (cutover: banner no longer implies legacy ownership)", async () => {
    const workspacePath = await withScratchDir();
    await writeFile(join(workspacePath, "AGENTS.md"), `${GENERATED_BANNER}\ncontent\n`, "utf-8");
    const targets = await probeLegacyCompileTargets(workspacePath, realFs as RuleServiceFs);
    expect(targets).toEqual([]);
  });

  it("returns [] even when CLAUDE.md carries the generated banner", async () => {
    const workspacePath = await withScratchDir();
    await writeFile(join(workspacePath, "CLAUDE.md"), `${GENERATED_BANNER}\ncontent\n`, "utf-8");
    const targets = await probeLegacyCompileTargets(workspacePath, realFs as RuleServiceFs);
    expect(targets).toEqual([]);
  });

  it("returns [] even when ALL THREE former targets' outputs are present on disk", async () => {
    const workspacePath = await withScratchDir();
    await writeFile(join(workspacePath, "AGENTS.md"), `${GENERATED_BANNER}\ncontent\n`, "utf-8");
    await writeFile(join(workspacePath, "CLAUDE.md"), `${GENERATED_BANNER}\ncontent\n`, "utf-8");
    await mkdir(join(workspacePath, ".claude", "rules"), { recursive: true });
    await writeFile(
      join(workspacePath, ".claude", "rules", "some-rule.md"),
      `---\npaths: ['**/*.ts']\n---\n${GENERATED_BANNER}\n\ncontent\n`,
      "utf-8"
    );
    const targets = await probeLegacyCompileTargets(workspacePath, realFs as RuleServiceFs);
    expect(targets).toEqual([]);
  });
});

describe("compileRules — bare invocation is a no-op post-cutover (mt#3058)", () => {
  it("regenerates NOTHING on a fresh repo (no fallback to a default agents.md write)", async () => {
    const workspacePath = await withScratchDir();

    const result = await compileRules({ workspacePath });

    expect(result.success).toBe(true);
    expect(result.target).toBe("");
    expect(result.targets).toEqual([]);
    expect(result.filesWritten).toEqual([]);

    // The critical cutover assertion: no legacy AGENTS.md write happened.
    expect(await fileExists(join(workspacePath, "AGENTS.md"))).toBe(false);
  });

  it("leaves existing banner-carrying AGENTS.md / CLAUDE.md untouched (no dual-write)", async () => {
    const workspacePath = await withScratchDir();
    const staleBody = `${GENERATED_BANNER}\nSTALE PLACEHOLDER BODY\n`;
    await writeFile(join(workspacePath, "AGENTS.md"), staleBody, "utf-8");
    await writeFile(join(workspacePath, "CLAUDE.md"), staleBody, "utf-8");

    const result = await compileRules({ workspacePath });

    expect(result.success).toBe(true);
    expect(result.targets).toEqual([]);
    expect(result.filesWritten).toEqual([]);

    // Legacy no longer owns these — the bare invocation must NOT rewrite them.
    expect(await readFile(join(workspacePath, "AGENTS.md"), "utf-8")).toBe(staleBody);
    expect(await readFile(join(workspacePath, "CLAUDE.md"), "utf-8")).toBe(staleBody);
  });

  it("bare --check reports nothing stale (no targets probed)", async () => {
    const workspacePath = await withScratchDir();
    const staleBody = `${GENERATED_BANNER}\nSTALE PLACEHOLDER BODY\n`;
    await writeFile(join(workspacePath, "AGENTS.md"), staleBody, "utf-8");
    await writeFile(join(workspacePath, "CLAUDE.md"), staleBody, "utf-8");

    const result = await compileRules({ workspacePath, check: true });

    expect(result.success).toBe(true);
    expect(result.stale).toBe(false);
    expect(result.targets).toEqual([]);
    // No side effects.
    expect(await readFile(join(workspacePath, "AGENTS.md"), "utf-8")).toBe(staleBody);
    expect(await readFile(join(workspacePath, "CLAUDE.md"), "utf-8")).toBe(staleBody);
  });
});

describe("compileRules — explicit --target still works until mt#2996 (mt#3058)", () => {
  it("explicit --target agents.md compiles exactly that target, ignoring other outputs", async () => {
    const workspacePath = await withScratchDir();
    const staleBody = `${GENERATED_BANNER}\nSTALE PLACEHOLDER BODY\n`;
    await writeFile(join(workspacePath, "AGENTS.md"), staleBody, "utf-8");
    await writeFile(join(workspacePath, "CLAUDE.md"), staleBody, "utf-8");

    const result = await compileRules({ workspacePath, target: "agents.md" });

    expect(result.success).toBe(true);
    expect(result.target).toBe("agents.md");
    expect(result.targets).toBeUndefined();

    // AGENTS.md was rewritten by the explicit target...
    const agentsContent = await readFile(join(workspacePath, "AGENTS.md"), "utf-8");
    expect(agentsContent.startsWith(GENERATED_BANNER)).toBe(true);
    expect(agentsContent).not.toContain("STALE PLACEHOLDER BODY");
    // ...but CLAUDE.md was left untouched.
    expect(await readFile(join(workspacePath, "CLAUDE.md"), "utf-8")).toBe(staleBody);
  });

  it("--check flags an orphaned claude-rules .md file as stale (mt#2868, explicit target)", async () => {
    // No rule corpus exists in this scratch dir, so buildClaudeRulesContent
    // resolves to zero expected files — a pre-existing generated .md file
    // is therefore an orphan (the source rule lost eligibility or its
    // selection config disabled it since the file was written).
    const workspacePath = await withScratchDir();
    await mkdir(join(workspacePath, ".claude", "rules"), { recursive: true });
    await writeFile(
      join(workspacePath, ".claude", "rules", "orphaned-rule.md"),
      `---\npaths: ['**/*.ts']\n---\n${GENERATED_BANNER}\n\nstale content\n`,
      "utf-8"
    );

    const result = await compileRules({ workspacePath, check: true, target: "claude-rules" });

    expect(result.check).toBe(true);
    expect(result.stale).toBe(true);
  });

  it("--check does not flag a hand-authored (bannerless) .md file in .claude/rules/ as stale", async () => {
    const workspacePath = await withScratchDir();
    await mkdir(join(workspacePath, ".claude", "rules"), { recursive: true });
    await writeFile(
      join(workspacePath, ".claude", "rules", "hand-authored.md"),
      "---\npaths: ['**/*.ts']\n---\n# Hand-authored, not generated\n",
      "utf-8"
    );

    const result = await compileRules({ workspacePath, check: true, target: "claude-rules" });

    expect(result.check).toBe(true);
    expect(result.stale).toBe(false);
  });
});
