#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/duplicate-signature-tokens.ts

// Signature-token extraction and duplicate-check-record parsing (mt#3722).
//
// The functional core of the duplicate-signature scan: two pure functions over
// spec text, with no IO, no domain imports, and no clock. The SQL scan that
// consumes them lives in ./duplicate-signature-scan.ts, which is the imperative
// shell — the split is `testing-standards.mdc §Testable Design`, and it is what
// lets every rule below be tested against real spec prose without a database.
//
// ## Why this exists
//
// `require-duplicate-check-record.ts` (mt#3673) enforces that a duplicate check
// was PERFORMED and RECORDED. It deliberately does not check whether the
// record's verdicts are TRUE — see its own comment, which assigns search
// QUALITY to the skill and the reviewer. mt#3719 (R4 in mem#819) is the case
// that shows the gap: the record was present, named five candidates, and
// reconciled each as confirm-orthogonal, all written from candidate TITLES. The
// actual duplicate — mt#3575 — was never named at all, because its title
// ("The test suite is not order-independent...") says nothing about the new
// task's subject while its SPEC names `GET /api/sweeps` three times.
//
// So the check that would have caught it cannot be scoped to the record's named
// candidates: a check scoped to what the agent chose to write down is defeated
// by omission, and omission is this family's actual failure mode. It has to
// reach tasks the record does not mention.
//
// ## Why exact substring, not similarity
//
// mem#819 measured the embedding path against this exact class: the advisory
// guard's threshold is 0.65 while real duplicates land at 1.03-1.11, one of them
// ranked BELOW an unrelated task. Raising the threshold to reach them surfaces
// the whole active corpus. mt#450 owns that metric question and this module
// deliberately does not wait on it — `GET /api/sweeps` is a literal string
// present in both documents, and finding it needs no metric at all.

/**
 * A token extracted from a task's title/spec, distinctive enough that its
 * appearance in ANOTHER task's spec is evidence the two are about the same
 * thing.
 */
export interface SignatureToken {
  /** The literal text to search for. Never normalized — matching is exact. */
  text: string;
  /** Which rule produced it. Recorded in the calibration log so the FP review
   *  can size each rule's contribution separately rather than the whole scan's. */
  rule: "route" | "path" | "identifier";
}

// A FOURTH rule — cited task refs (`mt#3575`) — was implemented and then
// REMOVED before ship, on measurement rather than taste. Replaying mt#3719
// against the live corpus, it contributed 4 of 9 matches and every one was a
// false positive: mt#3711, mt#2841, mt#2607 and mt#3627 each merely LIST the
// cited id among unrelated tasks. That is the common shape here — duplicate-check
// records, "related tasks" sections, and burndown tables all enumerate ids, so a
// shared citation carries no subject overlap. Kept out rather than shipped for
// the calibration log to rediscover; `TASK_REF_RE` below survives because
// parseDuplicateCheckRecord still needs it.

/**
 * Minimum token length. Below this a token is too likely to collide by
 * accident — `db`, `id`, `run` are all real backticked spans in this corpus.
 * Route tokens are exempt: `GET /api/x` is distinctive at 10 chars and the
 * rule's own shape already bounds it.
 */
export const MIN_TOKEN_LENGTH = 8;

/**
 * Cap on tokens carried into the scan, highest-value rule first. A bound on the
 * SQL the shell issues, not a claim that later tokens are worthless — the scan
 * logs how many were dropped so the cap never reads as full coverage.
 */
export const MAX_TOKENS = 12;

/**
 * A path so common that its presence says nothing about subject overlap. These
 * are not a stoplist of BAD tokens — the scan's match-count ceiling
 * (`MAX_TASKS_PER_TOKEN` in the shell) already drops anything ubiquitous
 * self-calibratingly, which is why this list stays tiny and does not need
 * maintenance as the repo grows. It exists only to avoid spending SQL round
 * trips on tokens whose ubiquity is known up front.
 */
const KNOWN_UBIQUITOUS = new Set([
  "CLAUDE.md",
  "package.json",
  "bunfig.toml",
  "tsconfig.json",
  "eslint.config.js",
  "packages/domain",
  "src/adapters",
]);

/** `GET /api/sweeps`, `POST /check-runs` — an HTTP verb plus a route path. */
const ROUTE_RE = /\b(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\s+(\/[\w\-./:{}]+)/g;

/** A source path with a recognized extension: `src/cockpit/routes/sweeps.ts`. */
const PATH_RE = /\b[\w@][\w\-./]*\/[\w\-.]+\.(?:ts|tsx|js|jsx|mjs|cjs|md|mdc|json|ya?ml|sql|sh)\b/g;

/** Content of a backticked span, which is where this corpus puts identifiers. */
const BACKTICK_RE = /`([^`\n]{1,120})`/g;

/** `mt#3575` — a task id cited inside prose. */
const TASK_REF_RE = /\bmt#\d{1,6}\b/g;

/**
 * Does a backticked span look like a code identifier rather than prose?
 *
 * Requires an identifier shape with an internal case change or separator —
 * `startTranscriptSweepBackstop`, `getTranscriptCoverage`, `task_specs`,
 * `MAX_TOKENS`. A single lowercase word (`degraded`, `spec`) is prose in a
 * backtick and is rejected: it collides across unrelated specs constantly.
 */
function looksLikeIdentifier(span: string): boolean {
  if (!/^[A-Za-z_$][\w$]*$/.test(span)) return false;
  // (Callers strip a trailing call suffix first — see stripCallSuffix.)
  const hasInternalCaseChange = /[a-z][A-Z]/.test(span);
  const hasSeparator = span.includes("_");
  const isScreamingCase = /^[A-Z][A-Z0-9_]{3,}$/.test(span);
  return hasInternalCaseChange || hasSeparator || isScreamingCase;
}

/** Strip a trailing `:123` line-number suffix so a path token still matches a
 *  citation of the same file at a different line. */
function stripLineSuffix(path: string): string {
  return path.replace(/:\d+(?::\d+)?$/, "");
}

/**
 * Strip a trailing call suffix: `mountSweepRoutes(app)` -> `mountSweepRoutes`.
 *
 * This corpus cites functions in call form far more often than bare, so without
 * it the identifier rule misses most of what it exists to catch — measured on
 * mt#3719's own spec, where `mountSweepRoutes(app)`, `getTranscriptCoverage()`
 * and `makeHarness()` were all dropped.
 */
function stripCallSuffix(span: string): string {
  return span.replace(/\([^)]*\)$/, "");
}

function push(out: Map<string, SignatureToken>, text: string, rule: SignatureToken["rule"]): void {
  const trimmed = text.trim();
  if (!trimmed || KNOWN_UBIQUITOUS.has(trimmed)) return;
  // A route token carries its own shape constraint — an HTTP verb plus a path —
  // so it is exempt from the length floor, which exists only to stop SHAPELESS
  // short tokens colliding.
  if (rule !== "route" && trimmed.length < MIN_TOKEN_LENGTH) return;
  if (!out.has(trimmed)) out.set(trimmed, { text: trimmed, rule });
}

/**
 * Extract signature tokens from a new task's title and spec.
 *
 * Ordered by rule precedence — route, path, identifier — so that truncating at
 * {@link MAX_TOKENS} drops the weakest evidence first rather than whatever the
 * text happened to mention last.
 */
export function extractSignatureTokens(title: string, spec: string): SignatureToken[] {
  const haystack = `${title}\n${spec}`;
  const routes = new Map<string, SignatureToken>();
  const paths = new Map<string, SignatureToken>();
  const identifiers = new Map<string, SignatureToken>();

  for (const m of haystack.matchAll(ROUTE_RE)) {
    push(routes, `${m[1]} ${m[2]}`, "route");
  }
  for (const m of haystack.matchAll(PATH_RE)) {
    push(paths, stripLineSuffix(m[0] ?? ""), "path");
  }
  for (const m of haystack.matchAll(BACKTICK_RE)) {
    // A backticked span may itself BE a path or route; those rules already ran
    // over the raw text, so only identifier-shaped spans are new here.
    const span = stripCallSuffix((m[1] ?? "").trim());
    if (looksLikeIdentifier(span)) push(identifiers, span, "identifier");
  }
  return [...routes.values(), ...paths.values(), ...identifiers.values()].slice(0, MAX_TOKENS);
}

/** How a duplicate-check record reconciled one named candidate. */
export type Reconciliation = "subsume" | "supersede" | "confirm-orthogonal" | "unlabeled";

/**
 * Parse the `Duplicate check:` record into the candidates it names and how each
 * was reconciled.
 *
 * Deliberately permissive about FORM. The record is hand-authored markdown and
 * the presence guard (mt#3673) accepts several shapes; this parser's job is to
 * recover which task ids the author considered and what verb sat nearest each
 * one, not to police the grammar. A candidate whose verb cannot be determined
 * is `"unlabeled"`, which the shell treats exactly like `confirm-orthogonal` —
 * an unreconciled mention is not a concession of overlap.
 */
export function parseDuplicateCheckRecord(spec: string): Map<string, Reconciliation> {
  const out = new Map<string, Reconciliation>();
  if (typeof spec !== "string") return out;

  const start = spec.search(/^[ \t]*(?:[-*+][ \t]+)?(?:\*\*)?duplicate check(?:\*\*)?[ \t]*:/im);
  if (start === -1) return out;
  const region = spec.slice(start);

  // Each task ref takes the verb from the window of text FOLLOWING it, up to
  // the next task ref — which is how these records are actually written:
  // "mt#3609 (confirm-orthogonal: same class, different module), mt#3538 (...)".
  const refs = [...region.matchAll(TASK_REF_RE)];
  for (let i = 0; i < refs.length; i++) {
    const ref = refs[i];
    if (!ref) continue;
    const id = ref[0];
    const from = (ref.index ?? 0) + id.length;
    const next = refs[i + 1];
    const to = next?.index ?? region.length;
    const window = region.slice(from, to).toLowerCase();
    let verdict: Reconciliation = "unlabeled";
    if (/\bsubsum/.test(window)) verdict = "subsume";
    else if (/\bsupersed/.test(window)) verdict = "supersede";
    else if (/\bconfirm[- ]orthogonal|\borthogonal\b/.test(window)) verdict = "confirm-orthogonal";
    // First verdict for an id wins — a later bare mention must not downgrade an
    // explicit earlier reconciliation.
    if (!out.has(id) || out.get(id) === "unlabeled") out.set(id, verdict);
  }
  return out;
}

/**
 * Does this reconciliation already concede the overlap?
 *
 * `subsume` and `supersede` do — the author has said the two tasks are the same
 * work and named which one wins, so a token match confirms rather than
 * contradicts them. `confirm-orthogonal` and `unlabeled` do not: those assert
 * (or leave implied) that the scopes do not overlap, which a token match in the
 * candidate's own spec is evidence against.
 */
export function concedesOverlap(r: Reconciliation | undefined): boolean {
  return r === "subsume" || r === "supersede";
}
