#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/entity-linkify.ts

// Pure text transform for the terminal deeplink linkifier (mt#2565).
//
// Everything here is `(text, state) -> (text, state)` with no fs, no clock, no
// env — the functional-core / imperative-shell split ADR-036 prescribes. The
// shell (`linkify-message-display.ts`) reads stdin, carries the fence state
// across deltas, and writes the hook envelope.
//
// WHAT IS REWRITTEN
//   `mt#NNNN` -> [mt#NNNN](minsky://task/mt%23NNNN)
//   `PR #N`   -> [PR #N](minsky://changeset/N)
//   `ask#N` / `mem#N` / `ws#N` -> [<label>](minsky://<type>/<uuid>), and ONLY
//     when the caller supplies a map containing that id (mt#3914)
//
// The first two targets are DERIVABLE from the visible label by pure string
// transform, which is why they were the v1 scope. The short ids are not: ADR-029
// makes the full UUID the sole deeplink target for those types, so linkifying
// one needs a short-id -> UUID resolution. That resolution stays OUT of this
// module and out of the hot path — the caller passes an already-resolved map,
// produced out-of-band by a sweep (ADR-028 D7(5)). This module never does IO.
//
// A short id absent from the map stays bare, which is the pre-mt#3914 behavior
// for every short id. The invariant that matters is narrower than "link them":
// a WRONG target is worse than a missing one, so an unmapped id is never
// guessed at and the short id is never itself used as a target.
//
// WHAT IS LEFT ALONE
//   - anything inside a fenced code block, including a fence that OPENED in an
//     earlier delta (the reason this module is stateful at all)
//   - inline code spans, blockquote lines, existing markdown links, and URLs
//   - a trailing partial line, unless the message is ending (`final`), so a ref
//     split across two deltas can never be rewritten from half a match
//
// The degradation direction is always "leave it bare": a ref this module
// declines to touch renders exactly as the model wrote it.
//
// @see .minsky/hooks/linkify-message-display.ts — the imperative shell
// @see src/cockpit/web/lib/entity-codec.ts — the shared codec (no second one)
// @see mt#2565 — this task; mt#3459 — the decision this implements

import { entityToMinskyUri } from "../../src/cockpit/web/lib/entity-codec";

/** Cross-delta state: the only thing a delta cannot determine on its own. */
export interface FenceState {
  inFence: boolean;
}

/**
 * What a rewrite pass actually did, by ref class (mt#4145).
 *
 * This exists so the display path can prove it RAN — the whole point of the
 * channel is that a hook which silently stops looks exactly like a hook with
 * nothing to do. Counting here rather than in the hook keeps it inside the scan
 * that is already walking the text, so it adds no traversal.
 *
 * `shortIdUnresolved` is deliberately NOT a link count: it records short-id refs
 * seen in unprotected prose that stayed BARE because the map could not resolve
 * them. Its normal value is small and non-zero (a just-minted id the out-of-band
 * refresh has not picked up); a sustained spike is the signature of an absent or
 * stale map, which otherwise degrades silently.
 */
export interface LinkifyCounts {
  task: number;
  changeset: number;
  ask: number;
  memory: number;
  session: number;
  shortIdUnresolved: number;
}

export function emptyCounts(): LinkifyCounts {
  return { task: 0, changeset: 0, ask: 0, memory: 0, session: 0, shortIdUnresolved: 0 };
}

/** Sum `b` into `a` in place. Used to accumulate a message's deltas. */
export function addCounts(a: LinkifyCounts, b: LinkifyCounts): LinkifyCounts {
  a.task += b.task;
  a.changeset += b.changeset;
  a.ask += b.ask;
  a.memory += b.memory;
  a.session += b.session;
  a.shortIdUnresolved += b.shortIdUnresolved;
  return a;
}

/** True when nothing at all was rewritten — "ran, had nothing to do". */
export function countsAreEmpty(c: LinkifyCounts): boolean {
  return (
    c.task === 0 &&
    c.changeset === 0 &&
    c.ask === 0 &&
    c.memory === 0 &&
    c.session === 0 &&
    c.shortIdUnresolved === 0
  );
}

export interface LinkifyResult {
  text: string;
  state: FenceState;
  /** What this delta rewrote. Always present; all-zero means "nothing to do". */
  counts: LinkifyCounts;
}

/** A line that opens or closes a fenced code block (``` or ~~~, up to 3 spaces of indent). */
const FENCE_LINE = /^[ \t]{0,3}(?:`{3,}|~{3,})/;

/** A blockquote line — quoted text the assistant is showing, not asserting. */
const BLOCKQUOTE_LINE = /^[ \t]{0,3}>/;

/**
 * Spans whose interior must never be rewritten, matched in one alternation so a
 * single left-to-right scan can skip them:
 *   1. inline code spans
 *   2. existing inline markdown links — covers both the label and the target, so
 *      an already-linked ref is never double-linked. An image (`![alt](url)`)
 *      matches this branch too: the `!` sits outside the span and carries no ref.
 *   3. reference-style links (`[label][ref]`) and their definitions
 *      (`[ref]: target`). Rewriting a label there would emit
 *      `[[mt#N](minsky://…)][ref]`, which renders as literal brackets — a
 *      corruption rather than a missed link, which is why the branch is worth
 *      carrying even though the form is rare in assistant output (PR #2763 R1).
 *   4. angle-bracket autolinks
 *   5. bare URLs, including `minsky://` ones written without markdown
 */
const PROTECTED_SPAN =
  /`+[^`\n]*`+|\[[^\]\n]*\]\([^)\n]*\)|\[[^\]\n]*\]\[[^\]\n]*\]|^[ \t]{0,3}\[[^\]\n]+\]:[^\n]*|<[^>\s]+>|\b[a-z][a-z0-9+.-]*:\/\/\S+/gim;

const TASK_REF = /\bmt#(\d+)\b/g;
const PR_REF = /\bPR #(\d+)\b/g;
const SHORT_ID_REF = /\b(ask|mem|ws)#(\d+)\b/g;

/**
 * Short-id prefix -> the `minsky://` URI type. `ws` maps to `session`, matching
 * the URI-type table in `cockpit-deeplinks.mdc`: the workspace deeplink type is
 * `session`, deliberately NOT renamed by ADR-022 stage 1.
 */
const SHORT_ID_TYPES = { ask: "ask", mem: "memory", ws: "session" } as const;

export type ShortIdKind = (typeof SHORT_ID_TYPES)[keyof typeof SHORT_ID_TYPES];

/**
 * Resolved short-id -> UUID lookup, keyed by URI type then by the id's NUMERIC
 * part (`"7415"`, not `"ask#7415"`) so a lookup is one property read with no
 * string building in the hot path.
 *
 * Supplied by the caller; this module neither builds nor refreshes it.
 */
export type ShortIdMap = Partial<Record<ShortIdKind, Record<string, string>>>;

/**
 * The `ask`/`mem`/`ws` prefix -> URI-type mapping, exported so a consumer does
 * not re-hand-write it (mt#3960). `mem` -> `memory` and `ws` -> `session` are
 * both non-obvious, and a second copy that drifts would silently look up the
 * wrong family.
 */
export function shortIdPrefixToKind(prefix: string): ShortIdKind | undefined {
  return SHORT_ID_TYPES[prefix.toLowerCase() as keyof typeof SHORT_ID_TYPES];
}

/**
 * Resolve a short id against the map, or `undefined` if it does not resolve.
 *
 * THE predicate for "will the display path link this ref" — deliberately one
 * function rather than a condition written twice (PR #2839 R1). `replaceRefs`
 * below uses it to decide whether to rewrite, and `bare-entity-ref-scan` uses
 * it to decide whether warning about a bare ref is warranted. Those two must
 * agree exactly: if the scanner is more permissive it suppresses a warning
 * about a ref that stays bare — a silent miss, the one direction an advisory
 * guard must never fail in.
 *
 * A present-but-empty or non-string entry is NOT a resolution: a malformed
 * cache must degrade to "bare", never to "linked to nothing".
 */
export function resolveShortId(
  shortIdMap: ShortIdMap | undefined,
  kind: ShortIdKind,
  num: string
): string | undefined {
  const uuid = shortIdMap?.[kind]?.[num];
  if (typeof uuid !== "string" || uuid === "") return undefined;
  return uuid;
}

/**
 * Rewrite every task/PR/short-id reference in a span already known to be unprotected.
 *
 * `counts`, when supplied, is MUTATED in place rather than returned (mt#4145).
 * This runs per unprotected span of every line of every streaming delta on the
 * harness's hottest event, so the accumulator is threaded down instead of
 * allocating and merging a record at each level.
 */
function replaceRefs(text: string, shortIdMap?: ShortIdMap, counts?: LinkifyCounts): string {
  const withDerivable = text
    .replace(TASK_REF, (_match, num: string) => {
      const id = `mt#${num}`;
      if (counts) counts.task += 1;
      return `[${id}](${entityToMinskyUri("task", id)})`;
    })
    .replace(PR_REF, (_match, num: string) => {
      if (counts) counts.changeset += 1;
      return `[PR #${num}](${entityToMinskyUri("changeset", num)})`;
    });

  if (!shortIdMap) {
    // No map means every short id stays bare. Still COUNT them when an
    // accumulator is present: "the map was absent" and "there were no short ids"
    // are the two readings of a zero here, and AT4 turns on telling them apart.
    // Guarded on `counts` so the ordinary map-present path never pays this scan.
    if (counts) {
      SHORT_ID_REF.lastIndex = 0;
      while (SHORT_ID_REF.exec(withDerivable) !== null) counts.shortIdUnresolved += 1;
    }
    return withDerivable;
  }

  return withDerivable.replace(SHORT_ID_REF, (match, prefix: string, num: string) => {
    const kind = shortIdPrefixToKind(prefix);
    if (kind === undefined) return match;
    // Unmapped stays bare — see the header: a wrong target is worse than none,
    // and the short id itself is not a legal target (ADR-029). The condition
    // lives in `resolveShortId` so the bare-ref scanner can share it verbatim.
    const uuid = resolveShortId(shortIdMap, kind, num);
    if (uuid === undefined) {
      if (counts) counts.shortIdUnresolved += 1;
      return match;
    }
    if (counts) counts[kind] += 1;
    return `[${match}](${entityToMinskyUri(kind, uuid)})`;
  });
}

/**
 * Rewrite one line, skipping protected spans. Every occurrence is linked, not
 * just the first: the one-link-per-entity ration mt#3459 retired was an
 * authoring economy, and at the display surface a repeat costs the reader
 * nothing.
 */
export function linkifyLine(line: string, shortIdMap?: ShortIdMap, counts?: LinkifyCounts): string {
  let out = "";
  let cursor = 0;
  PROTECTED_SPAN.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = PROTECTED_SPAN.exec(line)) !== null) {
    out += replaceRefs(line.slice(cursor, match.index), shortIdMap, counts);
    out += match[0];
    cursor = match.index + match[0].length;
  }
  return out + replaceRefs(line.slice(cursor), shortIdMap, counts);
}

/**
 * Rewrite one streaming delta.
 *
 * `state` carries the fence flag from the previous delta of the SAME message;
 * pass `{ inFence: false }` at the start of a message. The returned state is
 * what the next delta of that message must receive.
 *
 * `final` marks the message's last flush, which is the only delta whose trailing
 * segment is known to be a complete line.
 */
export function linkifyDelta(
  delta: string,
  state: FenceState,
  options: { final?: boolean; shortIdMap?: ShortIdMap } = {}
): LinkifyResult {
  const segments = delta.split("\n");
  // `split` always yields one more segment than there are newlines, so the last
  // segment is the text AFTER the final newline — empty when the delta ends on
  // one, which per the hook's contract ("batches of newly completed lines") is
  // the ordinary case.
  const trailing = segments.pop() ?? "";
  let inFence = state.inFence;
  const rewritten: string[] = [];
  const counts = emptyCounts();

  for (const line of segments) {
    if (FENCE_LINE.test(line)) {
      inFence = !inFence;
      rewritten.push(line);
      continue;
    }
    if (inFence || BLOCKQUOTE_LINE.test(line)) {
      rewritten.push(line);
      continue;
    }
    rewritten.push(linkifyLine(line, options.shortIdMap, counts));
  }

  let trailingOut = trailing;
  if (trailing.length > 0 && options.final === true) {
    if (FENCE_LINE.test(trailing)) {
      inFence = !inFence;
    } else if (!inFence && !BLOCKQUOTE_LINE.test(trailing)) {
      trailingOut = linkifyLine(trailing, options.shortIdMap, counts);
    }
  }

  rewritten.push(trailingOut);
  return { text: rewritten.join("\n"), state: { inFence }, counts };
}
