#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/record-turn-anchor.ts

// Stop-event RECORDER: persist the just-completed turn's anchor (mt#3490, ADR-031).
//
// Not a detector. It emits no advisory, denies nothing, and writes no
// calibration record — it exists so that prompt-time guards can STOP inferring
// the turn boundary from prompt positions in a possibly-lagging transcript.
// ADR-031 §Decision assigns the four sub-operations of "detect the just-completed
// turn" to their best sources; this guard owns the two that belong at `Stop`:
//
//   (1) locate the turn window  -> the tail needs no second bounding prompt here
//   (2) capture the final TEXT  -> `last_assistant_message`, the vendor's own
//                                  documented recommendation
//
// Sub-operations (3) reading tool calls and (4) injecting guidance deliberately
// stay at `UserPromptSubmit`, where the transcript has had strictly MORE time to
// flush and where the principal's attention model is unchanged. Do not move them
// here — ADR-031 rejects that as options (b) and (d), the latter on a live
// unfixed defect (mt#2005) plus an attention-model change that would need
// principal ratification.
//
// WHY THIS IS SAFE TO MISS. `StopFailure` runs INSTEAD of `Stop` when a turn
// ends on an API error, and its output is ignored — so some turns will record no
// anchor at all, by design. That is not a gap: prompt-time resolution falls back
// to mt#3280's `resolveCompletedTurn`, i.e. to exactly today's behaviour. This
// mechanism can fail to IMPROVE a turn; it cannot lose one.
//
// @see .minsky/hooks/turn-anchor-store.ts — the store this writes
// @see .minsky/hooks/transcript.ts `resolveCompletedTurnFromAnchor` — the reader
// @see docs/architecture/adr-031-guidance-detector-lifecycle-event.md
// @see mt#3490 — originating task

import type { StopHookInput } from "./types";
import type { DispatchContext, GuardOutcome } from "./registry";

/**
 * `StopHookInput` plus the Stop-only field this recorder exists to capture.
 *
 * Declared locally for the same reason `turn-end-retro-scan.ts` declares it
 * locally: `last_assistant_message` is delivered on `Stop`/`SubagentStop` only,
 * so widening the shared `StopHookInput` would advertise it to every consumer
 * of that type regardless of event.
 */
interface StopHookInputWithFinalMessage extends StopHookInput {
  /**
   * Claude's final response text for the completed turn. Per hooks.md this is
   * the source hooks needing the final assistant text SHOULD use, rather than
   * parsing `transcript_path` — which "isn't guaranteed to include the final
   * message at Stop time on all versions."
   */
  last_assistant_message?: string;
}
import { extractFinalTurn } from "./transcript";
import { turnKeyFor } from "./turn-end-scan-store";
import { writeAnchor } from "./turn-anchor-store";

/**
 * Record the completed turn's boundary key + final assistant text.
 *
 * `storeDir` is injectable for tests — the same seam `turn-end-retro-scan.run`
 * exposes. Tests pass a temp dir rather than patching the store module, which
 * ADR-036 bans outright.
 *
 * Always returns `null`: a recorder contributes no context and makes no
 * decision, so it must never occupy any of the Stop injection budget.
 */
export async function run(
  input: StopHookInputWithFinalMessage,
  ctx: DispatchContext,
  storeDir?: string
): Promise<GuardOutcome | null> {
  const sessionId = input.session_id;
  if (!sessionId) return null;

  // `extractFinalTurn` returns the bounding prompt line precisely so callers can
  // key the turn stably across a later prompt-time re-scan — its own doc comment
  // says so. This is that caller.
  const { openingPrompt } = extractFinalTurn(ctx.transcriptLines);
  if (!openingPrompt) return null;

  const turnKey = turnKeyFor(openingPrompt);
  // `turnKeyFor` yields this sentinel when no opening prompt exists. `openingPrompt`
  // is non-null here so it should not occur — but writing it would persist a key
  // that names no line, which the reader must then refuse. Drop it at the source.
  if (turnKey === "session-start") return null;

  writeAnchor(
    sessionId,
    { turnKey, lastAssistantMessage: input.last_assistant_message ?? "" },
    storeDir
  );

  return null;
}
