#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/require-duplicate-check-record.ts

// PreToolUse guard: deny `mcp__minsky__tasks_create` when the spec carries no
// duplicate-check record (mt#3673).
//
// mt#3585 added Step 1a to `/create-task` — search the task graph, then record
// either the named candidates with a reconciliation, or the literal line
// `Duplicate check: no candidates found.`, in the spec's `## Context`. Its exit
// gate checks that record is present. But that check lives INSIDE the skill: a
// direct `tasks_create` call never enters `/create-task`, so neither the search
// nor its gate runs, and the create succeeds with no signal that nothing looked.
//
// That is the same bypass shape the repo already learned once — per
// `hook-observers.mdc §Turn-end-unwalked-task`, mt#2689's chain-walk fix "lived
// in `/create-task`'s exit step and was bypassed by calling the tool directly,"
// which is why that detector was rebuilt keyed on tool-call state. This guard
// moves the requirement to the boundary every path crosses.
//
// WHY A PRESENCE CHECK AND NOT A SIMILARITY CHECK. The adjacent
// `parallel-work-guard-standalone.ts` (mt#2813) already asks "does a similar
// task exist?" and provably cannot answer it: its threshold is
// STANDALONE_DUP_MAX_DISTANCE = 0.65 while real duplicates measure ~1.03-1.05,
// one of them ranked BELOW an unrelated task (mem#819's measured table; mt#450
// owns the metric question). So this guard does not judge WHETHER a duplicate
// exists — it checks whether the agent LOOKED. That is a deterministic test on
// text the agent itself authored, which is why it ships denying rather than
// calibration-first: ADR-024's ladder governs trigger-phrase guidance hooks with
// recall/precision axes, and a literal-form presence check has neither.
//
// Fail-open: any error allows the call. Override: MINSKY_SKIP_DUPLICATE_RECORD=1.
//
// @see docs/architecture/adr-028-guard-hook-dispatcher-consolidation.md — D1/D2
// @see .minsky/hooks/parallel-work-guard-standalone.ts — the advisory similarity sibling
// @see .claude/skills/create-task/SKILL.md — Step 1a, the authoring-side requirement

import { readInput } from "./types";
import type { ToolHookInput, HookOutput } from "./types";
import type { DispatchContext, GuardOutcome } from "./registry";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Override env var: set to "1"/"true"/"yes" to create without the record. */
export const OVERRIDE_ENV_VAR = "MINSKY_SKIP_DUPLICATE_RECORD";

/**
 * The literal line `/create-task` Step 1a prescribes when the search found
 * nothing. Exported so the skill-text drift test can assert the compiled
 * SKILL.md still tells agents to write exactly what this guard accepts —
 * the two live in different languages (prose vs TypeScript) and cannot share
 * a constant by import, so a test is the only thing holding them together.
 */
export const NO_CANDIDATES_LINE = "Duplicate check: no candidates found.";

/**
 * Matches a duplicate-check record in a spec.
 *
 * Both accepted forms open the same way — the no-candidates line above, and a
 * named-candidates record with its reconciliation — so the presence test is on
 * the `Duplicate check:` label at the start of a line. Leading list markers and
 * bold decoration are tolerated because specs are hand-authored markdown and
 * `- **Duplicate check:** ...` is a natural way to write it.
 *
 * Deliberately NOT checked: whether a named-candidates record actually names a
 * real task, or whether its reconciliation verb is one of
 * subsume/supersede/confirm-orthogonal. Both would require judgment and would
 * introduce a false-positive class this guard is specifically designed not to
 * have. The gate's job is to make "never looked" impossible to do silently; the
 * QUALITY of the search is the skill's job and the reviewer's.
 */
export function hasDuplicateCheckRecord(spec: string | null | undefined): boolean {
  if (typeof spec !== "string" || spec.trim() === "") return false;
  return /^[ \t]*(?:[-*+][ \t]+)?(?:\*\*)?duplicate check(?:\*\*)?[ \t]*:/im.test(spec);
}

/** The denial text. Names both accepted forms so the fix is unambiguous. */
export function buildDenialReason(): string {
  return (
    `tasks_create denied: the spec carries no duplicate-check record (mt#3673).\n\n` +
    `Run \`tasks_search\` on this task's subject FIRST, then record the result in the ` +
    `spec's \`## Context\` in one of two forms:\n` +
    `  1. Named candidates + reconciliation — e.g. "Duplicate check: mt#1234 covers the ` +
    `same surface; confirm-orthogonal because ...".\n` +
    `  2. The literal line — "${NO_CANDIDATES_LINE}"\n\n` +
    `Read the candidate TITLES, not the similarity scores: at the distances that ` +
    `separate real duplicates the scores do not discriminate (mem#819), so a clean ` +
    `search result is weak evidence on its own.\n\n` +
    `Override (audit-logged): ${OVERRIDE_ENV_VAR}=1`
  );
}

// ---------------------------------------------------------------------------
// Dispatcher entry point (ADR-028 D1/D2)
// ---------------------------------------------------------------------------

/**
 * Pure-function entry point invoked in-process by `./dispatch-pretooluse.ts`.
 * Returns `null` for silent allow, matching the dispatcher's contract.
 */
export function run(input: ToolHookInput, _ctx: DispatchContext): GuardOutcome | null {
  const overrideVal = process.env[OVERRIDE_ENV_VAR];
  const isOverride =
    overrideVal === "1" ||
    overrideVal?.toLowerCase() === "true" ||
    overrideVal?.toLowerCase() === "yes";

  if (isOverride) {
    return {
      auditLines: [
        `[require-duplicate-check-record] OVERRIDE: ack=${overrideVal} session=${
          input.session_id ?? "unknown"
        } ts=${new Date().toISOString()}\n`,
      ],
    };
  }

  const spec = input.tool_input?.["spec"];
  if (hasDuplicateCheckRecord(typeof spec === "string" ? spec : undefined)) return null;
  return { deny: { reason: buildDenialReason() } };
}

// ---------------------------------------------------------------------------
// Standalone CLI entry point (fail-open: any error allows the call)
// ---------------------------------------------------------------------------

if (import.meta.main) {
  try {
    const input = await readInput<ToolHookInput>();
    const outcome = run(input, {} as DispatchContext);

    if (outcome?.auditLines) {
      // STDERR, not stdout (PR #2612 R1). ADR-028 D1 reserves a PreToolUse
      // hook's stdout for the single JSON object, and mt#3625 measured that
      // anything else there makes Claude Code discard the hook's ENTIRE output
      // — silently and destructively. The override path emits no JSON today, so
      // this is defensive rather than a live bug; putting diagnostics on stdout
      // is exactly the coupling that broke the dispatcher for months.
      for (const line of outcome.auditLines) process.stderr.write(line);
    } else if (outcome?.deny) {
      const output: HookOutput = {
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason: outcome.deny.reason,
        },
      };
      process.stdout.write(`${JSON.stringify(output)}\n`);
    }
    process.exit(0);
  } catch (err) {
    process.stderr.write(
      `[require-duplicate-check-record] fail-open: ${
        err instanceof Error ? err.message : String(err)
      }\n`
    );
    process.exit(0);
  }
}
