#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/turn-anchor-store.ts

// Cross-event store for the just-completed turn's ANCHOR (mt#3490, ADR-031).
//
// ADR-031's decision is "anchor at `Stop`; detect and inject at
// `UserPromptSubmit`". This is the persistence half: the `Stop`-side recorder
// (`record-turn-anchor.ts`) writes the turn's stable boundary key plus the
// event's `last_assistant_message`, and prompt-time window resolution reads it
// back instead of RE-DERIVING the boundary from prompt positions in a file the
// vendor documents as possibly-lagging.
//
// Why a store rather than a computation: six of the seven fixes in this area
// (mt#2255, mt#2357, mt#2824, mt#3003, mt#3273, mt#3280) were spent correcting
// that re-derivation. `Stop` is the one moment the boundary is unambiguous —
// the turn is the transcript's tail, needing no second bounding prompt — so
// recording it there removes the inference rather than patching it again.
//
// Turn identity: the turn's OPENING real-prompt line (`uuid`, falling back to
// `timestamp`), via `turnKeyFor` from `./turn-end-scan-store` — deliberately
// the SAME key function that store already uses, so the two cross-event stores
// cannot disagree about what "this turn" means. At Stop time that line is the
// transcript's LAST real prompt; at the next prompt-time read it is the
// SECOND-TO-LAST — the same physical line either way, which is what makes the
// key stable across the two events.
//
// Layout: one small JSON file per session under
// `~/.local/state/minsky/turn-anchor/<session_id>.json` — mirrors
// `turn-end-scan-store.ts`'s per-session-file pattern, which sidesteps the
// read-modify-write race a shared file would have between concurrent sessions.
//
// BOUNDED BY CONSTRUCTION: exactly one anchor per session, overwritten on each
// `Stop`. Unlike the flagged-key SET in `turn-end-scan-store`, this file does
// not accumulate entries as a conversation runs long — a 500-turn conversation
// leaves the same single record a 2-turn one does.
//
// All reads FAIL OPEN (unreadable/absent/malformed store = no anchor), which is
// the property that makes ADR-031's degradation claim hold: absence of an
// anchor is indistinguishable from today's behaviour, because the caller then
// falls back to mt#3280's `resolveCompletedTurn`. A failed write logs to stderr
// and is non-fatal for the same reason — a missed anchor costs one turn's
// precision, never a missed scan.
//
// @see .minsky/hooks/record-turn-anchor.ts — the Stop-event writer
// @see .minsky/hooks/transcript.ts `resolveCompletedTurnFromAnchor` — the reader
// @see docs/architecture/adr-031-guidance-detector-lifecycle-event.md
// @see mt#3490 — originating task

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const DEFAULT_STORE_DIR = join(homedir(), ".local", "state", "minsky", "turn-anchor");

/**
 * The `Stop`-recorded boundary of one completed turn.
 *
 * `lastAssistantMessage` is the vendor's own recommended source for the final
 * assistant text (hooks.md: "hooks that need the final assistant text of the
 * current turn should use `last_assistant_message` on Stop ... rather than
 * reading the transcript"). It is stored alongside the key rather than in a
 * second file so one read answers both questions a prompt-time consumer has.
 */
export interface RecordedTurnAnchor {
  /** The opening real-prompt line's `uuid` (falling back to `timestamp`). */
  turnKey: string;
  /**
   * The `Stop` event's `last_assistant_message`. Empty string when the event
   * carried none — distinguishable from "no anchor recorded", which is
   * `undefined` from {@link readAnchor}.
   */
  lastAssistantMessage: string;
}

function storePath(sessionId: string, dir: string): string {
  // session_id is a UUID in practice; sanitize defensively for path safety.
  const safe = sessionId.replace(/[^A-Za-z0-9_-]/g, "_");
  return join(dir, `${safe}.json`);
}

/**
 * Read the recorded anchor for a session, or `undefined` when none is
 * readable. Fails open on every error path — see the module header for why
 * that is load-bearing rather than merely defensive.
 */
export function readAnchor(
  sessionId: string,
  dir: string = DEFAULT_STORE_DIR
): RecordedTurnAnchor | undefined {
  try {
    const raw = readFileSync(storePath(sessionId, dir), "utf8");
    const parsed = JSON.parse(raw) as Partial<RecordedTurnAnchor>;
    if (typeof parsed.turnKey !== "string" || parsed.turnKey.length === 0) return undefined;
    return {
      turnKey: parsed.turnKey,
      lastAssistantMessage:
        typeof parsed.lastAssistantMessage === "string" ? parsed.lastAssistantMessage : "",
    };
  } catch {
    // intentional-swallow: fail-open — absent/unreadable/malformed store means
    // "no anchor", and the caller falls back to resolveCompletedTurn.
    return undefined;
  }
}

/** Persist a session's anchor, replacing any prior one. A failed write logs and is non-fatal. */
export function writeAnchor(
  sessionId: string,
  anchor: RecordedTurnAnchor,
  dir: string = DEFAULT_STORE_DIR
): void {
  try {
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(storePath(sessionId, dir), JSON.stringify(anchor), "utf8");
  } catch (err) {
    process.stderr.write(
      `[turn-anchor-store] write failed: ${err instanceof Error ? err.message : String(err)}\n`
    );
  }
}

/** Remove a session's anchor file (canary/test hygiene). Never throws. */
export function clearAnchor(sessionId: string, dir: string = DEFAULT_STORE_DIR): void {
  try {
    rmSync(storePath(sessionId, dir), { force: true });
  } catch {
    // intentional-swallow: best-effort cleanup only.
  }
}
