#!/usr/bin/env bun
// Generated by minsky compile. Do not edit directly.
// Source: .minsky/hooks/typecheck-on-stop.ts

// Stop AND SubagentStop hook: full type check on all project roots edited during this turn.
//
// This is the correctness/truthfulness gate — Claude cannot stop with
// type errors. Exit 2 forces Claude to continue and fix the errors.
//
// Consolidates: typecheck-on-stop.sh, typecheck-on-subagent-stop.sh, typecheck-tracked-roots.sh

import { existsSync, readFileSync, unlinkSync } from "fs";
import { readInput, execSync, resolveTsgoBinary } from "./types";
import type { StopHookInput } from "./types";

const input = await readInput<StopHookInput>();

const sessionId = input.session_id ?? "default";
const agentId = input.agent_id;
// Determine state file: keyed by session_id and (if subagent) agent_id
const stateFile = agentId
  ? `/tmp/claude-typecheck-roots-${sessionId}-${agentId}.txt`
  : `/tmp/claude-typecheck-roots-${sessionId}-main.txt`;

// Collect unique project roots from state file
let roots: string[] = [];
if (existsSync(stateFile)) {
  const content = readFileSync(stateFile, "utf-8");
  const lines = content.split("\n").filter(Boolean);
  roots = [...new Set(lines)];
}

// Fallback: if no tracked roots, use cwd or CLAUDE_PROJECT_DIR
if (roots.length === 0) {
  const fallback = input.cwd || process.env.CLAUDE_PROJECT_DIR;
  if (fallback) roots = [fallback];
}

// Per-root timeout: 15s each — prevents one hung check from consuming the entire hook budget
const PER_ROOT_TIMEOUT_MS = 15_000;

// Check each root
let allErrors = "";
let totalCount = 0;
const failedRoots: string[] = [];

for (const root of roots) {
  if (!existsSync(root)) continue;
  if (!existsSync(`${root}/tsconfig.json`)) continue;

  // Use the local tsgo binary directly to avoid bunx package resolution overhead
  // and nested process spawning (bunx → node → native binary).
  //
  // mt#3657 moved the resolution into `./types` (shared with typecheck-on-edit) and DROPPED
  // the `bunx` fallback this site used to carry. That fallback looked harmless and was not:
  // bunx does not resolve the pinned dependency at all — it fetches `@latest`, a compiler
  // three months newer than the pin as measured on 2026-08-04 — so falling back silently
  // reintroduced the drift this whole task exists to remove, on the one path where the local
  // install was already known to be missing. Nothing to run now means skip the root.
  const localBinary = resolveTsgoBinary(root);
  if (!localBinary) continue;

  const result = execSync([localBinary, "--noEmit"], { cwd: root, timeout: PER_ROOT_TIMEOUT_MS });

  if (result.timedOut) {
    // Skip this root — don't block the hook on a hung check
    continue;
  }

  if (result.exitCode !== 0) {
    const output = result.stdout || result.stderr;
    const count = output.split("\n").filter((line) => line.includes("): error TS")).length;
    totalCount += count;
    failedRoots.push(root);
    allErrors = allErrors
      ? `${allErrors}\n\n=== ${root} ===\n${output}`
      : `=== ${root} ===\n${output}`;
  }
}

if (failedRoots.length > 0) {
  const preview = allErrors.split("\n").slice(0, 60).join("\n");
  // Stop hooks use decision/reason schema, NOT hookSpecificOutput
  const output = {
    decision: "block",
    reason: `TypeScript errors must be fixed before completing:\n${preview}\n\nTotal: ${totalCount} error(s). Fix all type errors before returning.`,
  };
  process.stdout.write(JSON.stringify(output));
  process.exit(2);
}

// All checks passed — clean up state file
if (existsSync(stateFile)) {
  unlinkSync(stateFile);
}
process.exit(0);
