import * as path from "path";
import { homedir } from "os";
import { DEFAULT_DEV_PORT } from "@minsky/shared/constants";
import type { FsLike } from "../interfaces/fs-like";
import { createRealFs } from "../interfaces/real-fs";
import { createFileIfNotExists } from "../init/file-system";

/**
 * Abstraction for an MCP client that can be registered with Minsky.
 * Each implementation knows how to generate its config file content
 * and where to write it.
 */
export interface ClientRegistrar {
  name: string;
  generateConfig(transport: string, port?: number, host?: string): string;
  configPath(projectRoot: string): string;
  /**
   * Whether registration should merge the new server entry into an existing
   * config file rather than overwriting the entire file.
   *
   * Clients that own their config file (e.g. Cursor's `.cursor/mcp.json`)
   * set this to false. Clients that share a global config file (e.g. Claude
   * Desktop's `claude_desktop_config.json`) set this to true.
   */
  readonly mergeConfig: boolean;
  /**
   * The format of the config file generated by this registrar.
   * Defaults to "json" for most clients; TOML-based clients (Codex,
   * OpenHands) set this to "toml" so that the merge logic can handle
   * the file without attempting JSON.parse on TOML content.
   */
  readonly configFormat: "json" | "toml";
}

/**
 * Base registrar for clients that use the standard mcpServers JSON format.
 * Subclasses only need to provide name, configPath, and optionally mergeConfig.
 */
export abstract class McpServersJsonRegistrar implements ClientRegistrar {
  abstract readonly name: string;
  abstract configPath(projectRoot: string): string;

  /** Override to true in subclasses that share a global config file. */
  readonly mergeConfig: boolean = false;
  readonly configFormat: "json" | "toml" = "json";

  generateConfig(transport: string, port?: number, host?: string): string {
    const resolvedPort = port || DEFAULT_DEV_PORT;
    const resolvedHost = host || "localhost";

    const args = ["mcp", "start"];
    if (transport === "sse") {
      args.push("--sse", "--port", String(resolvedPort), "--host", resolvedHost);
    } else if (transport === "httpStream") {
      args.push("--http-stream", "--port", String(resolvedPort), "--host", resolvedHost);
    }
    // stdio and unknown transports: just base args

    return JSON.stringify(
      {
        mcpServers: {
          "minsky-server": {
            command: "minsky",
            args,
          },
        },
      },
      undefined,
      2
    );
  }
}

/**
 * Registrar for the Cursor editor MCP client.
 * Produces `.cursor/mcp.json` content and path.
 */
export class CursorRegistrar extends McpServersJsonRegistrar {
  readonly name = "cursor";

  configPath(projectRoot: string): string {
    return path.join(projectRoot, ".cursor", "mcp.json");
  }
}

/**
 * Registrar for the Claude Desktop MCP client.
 *
 * Claude Desktop uses a global (user-level) config file rather than a
 * per-project one, so registration merges the minsky-server entry into any
 * existing config rather than overwriting it.
 *
 * Config file locations:
 * - macOS:   ~/Library/Application Support/Claude/claude_desktop_config.json
 * - Windows: %APPDATA%\Claude\claude_desktop_config.json
 * - Linux:   ~/.config/Claude/claude_desktop_config.json
 */
export class ClaudeDesktopRegistrar extends McpServersJsonRegistrar {
  readonly name = "claude-desktop";
  override readonly mergeConfig = true;

  configPath(_projectRoot: string): string {
    const home = homedir();
    if (process.platform === "darwin") {
      return path.join(
        home,
        "Library",
        "Application Support",
        "Claude",
        "claude_desktop_config.json"
      );
    } else if (process.platform === "win32") {
      return path.join(
        process.env.APPDATA || path.join(home, "AppData", "Roaming"),
        "Claude",
        "claude_desktop_config.json"
      );
    }
    // Linux
    return path.join(home, ".config", "Claude", "claude_desktop_config.json");
  }
}

/**
 * Default local-daemon MCP endpoint the `claude-code` shim entry connects to
 * (PR #3423 R2).
 *
 * Matches `DEFAULT_DAEMON_URL` in `src/mcp/shim/main.ts` and
 * `DEFAULT_LOCAL_DAEMON_HOST`/`DEFAULT_LOCAL_DAEMON_PORT` (127.0.0.1:48765)
 * in `src/mcp/daemon/local-daemon.ts` — duplicated here rather than
 * imported, since `packages/domain` does not depend on `src/` (same
 * constraint as `detectJsonIndent` above). Not currently configurable from
 * this registrar: `registerWithClient`'s `port`/`host` parameters carry
 * `.minsky/config.yaml`'s `mcp.*` settings for the CURRENT project's own
 * `minsky mcp start`, an unrelated concept from the machine-wide daemon's
 * endpoint, so reusing them here would be a category error, not a feature.
 * An operator who needs a non-default daemon endpoint can point
 * `minsky setup local-http --url <custom>` at the entry afterward, or set
 * `MINSKY_SHIM_DAEMON_URL` in their environment (`main.ts`'s `parseArgs`
 * reads it ahead of `--url`).
 */
const DEFAULT_LOCAL_DAEMON_MCP_URL = "http://127.0.0.1:48765/mcp";

/**
 * Registrar for the Claude Code MCP client.
 *
 * Claude Code resolves MCP servers at three scopes — local (per-project,
 * keyed under `projects.<path>` in `~/.claude.json`), project (`.mcp.json`
 * in the repo, shared via git), and user (a top-level `mcpServers` key in
 * `~/.claude.json`, shared across every project) — per
 * https://code.claude.com/docs/en/mcp. This registrar targets USER scope:
 * an agent opened in a repo Minsky has never initialized has no MCP tools of
 * its own yet and cannot bootstrap onboarding through a per-project-only
 * registration (mt#4700, absorbed into mt#4676).
 *
 * User scope is a single, platform-uniform path — unlike Claude Desktop's
 * OS-specific config directory — so `configPath` does not branch on
 * `process.platform`.
 *
 * `mergeConfig = true` because `~/.claude.json` is Claude Code's own live
 * state file (settings, per-project history, OAuth credentials) — the
 * `registerWithClient` merge path (JSON-parse, splice in `mcpServers`,
 * write back) preserves everything else in the file rather than
 * overwriting it, the same way `ClaudeDesktopRegistrar` does for
 * `claude_desktop_config.json`.
 */
export class ClaudeCodeRegistrar extends McpServersJsonRegistrar {
  readonly name = "claude-code";
  override readonly mergeConfig = true;

  configPath(_projectRoot: string): string {
    return path.join(homedir(), ".claude.json");
  }

  /**
   * Emits the SHIM invocation — `["mcp", "shim", "--url", <daemonUrl>]` —
   * rather than `McpServersJsonRegistrar`'s inherited default, a raw
   * `["mcp", "start", ...]` stdio spawn of the full ~32 MB server (PR #3423
   * R2).
   *
   * The stdio-spawn form is the PRE-ADR-038 topology: one full server
   * process per conversation. `minsky setup local-http`
   * (`src/mcp/setup/local-http-config.ts`) exists specifically to migrate
   * existing entries OFF that form onto the shim, which forwards to a single
   * shared daemon instead. Writing a brand-new user-scope entry in the
   * legacy form would spawn a full server in every conversation the operator
   * opens, and would need migrating again the moment it existed — the exact
   * shape `local-http` was built to retire, authored fresh.
   *
   * Args shape matches `rewriteToShimArgs()`'s output in
   * `local-http-config.ts:291-295` for an entry with no pre-`mcp` prefix
   * (there is none here — this is a fresh entry, not a rewrite).
   *
   * `command: "minsky"` (inherited from `McpServersJsonRegistrar`'s base
   * shape) is load-bearing, not incidental: `mcp shim` is NOT a normal CLI
   * subcommand — `scripts/cli-entry.ts` (the package's `bin`) intercepts
   * `["mcp","shim"]` from argv and imports a separate build artifact,
   * deliberately never entering `src/cli.ts` (that path pulls in tsyringe
   * and the full command registry, and the shim's RSS thinness is
   * load-bearing per mt#3812 / `src/mcp/shim/rss-budget.test.ts`). Only an
   * invocation that goes THROUGH the bin wrapper can reach it — measured in
   * `local-http-config.ts:106-119`: `minsky mcp shim --url …` runs,
   * `bun dist/minsky.js mcp shim --url …` and `bun src/cli.ts mcp shim
   * --url …` both fail with `unknown command 'shim'`. This entry's
   * `command: "minsky"` is exactly the form that resolves to the bin
   * wrapper, so it works — not by luck, but because it uses the one
   * invocation shape that can.
   *
   * `transport`/`port`/`host` are accepted (interface conformance) and
   * ignored: those describe how `minsky mcp start` would bind for THIS
   * project (`.minsky/config.yaml`'s `mcp` section), which has no bearing on
   * a shim entry that talks to the machine-wide daemon over HTTP regardless.
   *
   * Scoped to `ClaudeCodeRegistrar` only — the other seven registrars still
   * emit the stdio-spawn form via the inherited `generateConfig()` /
   * TOML-generator methods. Whether cursor/windsurf/etc. should also move to
   * shim form is a separate decision nobody has made; flipping them here
   * would be exactly that decision, made as a side effect.
   */
  override generateConfig(_transport: string, _port?: number, _host?: string): string {
    return JSON.stringify(
      {
        mcpServers: {
          "minsky-server": {
            command: "minsky",
            args: ["mcp", "shim", "--url", DEFAULT_LOCAL_DAEMON_MCP_URL],
          },
        },
      },
      undefined,
      2
    );
  }
}

/**
 * Registrar for the Windsurf editor MCP client.
 *
 * Windsurf stores MCP config globally at ~/.codeium/windsurf/mcp_config.json,
 * so registration merges into any existing config rather than overwriting.
 */
export class WindsurfRegistrar extends McpServersJsonRegistrar {
  readonly name = "windsurf";
  override readonly mergeConfig = true; // global config, may have other servers

  configPath(_projectRoot: string): string {
    // Windsurf stores config globally at ~/.codeium/windsurf/mcp_config.json
    return path.join(homedir(), ".codeium", "windsurf", "mcp_config.json");
  }
}

/**
 * Registrar for the Junie (JetBrains) MCP client.
 *
 * Junie stores MCP config at the project level: .junie/mcp/mcp.json.
 */
export class JunieRegistrar extends McpServersJsonRegistrar {
  readonly name = "junie";

  configPath(projectRoot: string): string {
    // Junie stores project-level MCP config at .junie/mcp/mcp.json
    return path.join(projectRoot, ".junie", "mcp", "mcp.json");
  }
}

/**
 * Registrar for the VS Code editor MCP client.
 *
 * VS Code uses a "servers" root key (not "mcpServers") in its MCP config.
 * Config file is workspace-scoped at `.vscode/mcp.json`.
 */
export class VSCodeRegistrar implements ClientRegistrar {
  readonly name = "vscode";
  readonly mergeConfig = false; // workspace-scoped, Minsky owns the file
  readonly configFormat: "json" | "toml" = "json";

  generateConfig(transport: string, port?: number, host?: string): string {
    const resolvedPort = port || DEFAULT_DEV_PORT;
    const resolvedHost = host || "localhost";

    const args = ["mcp", "start"];
    if (transport === "sse") {
      args.push("--sse", "--port", String(resolvedPort), "--host", resolvedHost);
    } else if (transport === "httpStream") {
      args.push("--http-stream", "--port", String(resolvedPort), "--host", resolvedHost);
    }

    return JSON.stringify(
      {
        servers: {
          "minsky-server": {
            command: "minsky",
            args,
          },
        },
      },
      undefined,
      2
    );
  }

  configPath(projectRoot: string): string {
    return path.join(projectRoot, ".vscode", "mcp.json");
  }
}

/**
 * Registrar for the Codex MCP client.
 *
 * Codex uses TOML format with [mcp_servers.<name>] sections.
 * Config is project-scoped at .codex/config.toml.
 */
export class CodexRegistrar implements ClientRegistrar {
  readonly name = "codex";
  readonly mergeConfig = true; // Codex config has other settings
  readonly configFormat: "json" | "toml" = "toml";

  generateConfig(transport: string, port?: number, host?: string): string {
    // Codex uses TOML format: [mcp_servers.<name>] with command/args/env
    const resolvedPort = port || DEFAULT_DEV_PORT;
    const resolvedHost = host || "localhost";

    const args = ['"mcp"', '"start"'];
    if (transport === "sse") {
      args.push('"--sse"', `"--port"`, `"${resolvedPort}"`, `"--host"`, `"${resolvedHost}"`);
    } else if (transport === "httpStream") {
      args.push(
        '"--http-stream"',
        `"--port"`,
        `"${resolvedPort}"`,
        `"--host"`,
        `"${resolvedHost}"`
      );
    }

    return `[mcp_servers.minsky-server]\ncommand = "minsky"\nargs = [${args.join(", ")}]\nenv = {}\nenabled = true\n`;
  }

  configPath(projectRoot: string): string {
    // Project-scoped by default
    return path.join(projectRoot, ".codex", "config.toml");
  }
}

/**
 * Registrar for the OpenHands MCP client.
 *
 * OpenHands uses TOML format with [mcp] section containing stdio_servers or shttp_servers.
 * Config is project-scoped at config.toml.
 */
export class OpenHandsRegistrar implements ClientRegistrar {
  readonly name = "openhands";
  readonly mergeConfig = true; // OpenHands config has other settings
  readonly configFormat: "json" | "toml" = "toml";

  generateConfig(transport: string, port?: number, host?: string): string {
    // OpenHands uses [mcp] section with stdio_servers array for stdio,
    // or shttp_servers for HTTP transport
    const resolvedPort = port || DEFAULT_DEV_PORT;
    const resolvedHost = host || "localhost";

    if (transport === "stdio") {
      return `[mcp]\nstdio_servers = [\n  {name = "minsky-server", command = "minsky", args = ["mcp", "start"]}\n]\n`;
    }
    // For HTTP transports, use shttp_servers
    const url = `http://${resolvedHost}:${resolvedPort}/mcp`;
    return `[mcp]\nshttp_servers = [\n  {url = "${url}"}\n]\n`;
  }

  configPath(projectRoot: string): string {
    return path.join(projectRoot, "config.toml");
  }
}

/**
 * Returns the registrar for the given client name.
 * Throws a descriptive error for unrecognized clients.
 */
export function getRegistrar(client: string): ClientRegistrar {
  switch (client) {
    case "cursor":
      return new CursorRegistrar();
    case "claude-desktop":
      return new ClaudeDesktopRegistrar();
    case "claude-code":
      return new ClaudeCodeRegistrar();
    case "vscode":
      return new VSCodeRegistrar();
    case "windsurf":
      return new WindsurfRegistrar();
    case "junie":
      return new JunieRegistrar();
    case "codex":
      return new CodexRegistrar();
    case "openhands":
      return new OpenHandsRegistrar();
    default:
      throw new Error(
        `MCP client "${client}" is not yet supported. Supported clients: cursor, claude-desktop, claude-code, vscode, windsurf, junie, codex, openhands`
      );
  }
}

/**
 * Indentation of an existing JSON document, defaulting to 2.
 *
 * Re-serializing a large, operator-owned config file (`~/.claude.json`,
 * `claude_desktop_config.json`) with the wrong indent rewrites the WHOLE
 * file rather than just the entry being changed — a surprising diff for a
 * file the operator never asked to be reformatted, and for `~/.claude.json`
 * specifically a file that also carries real OAuth credentials and
 * per-project history (PR #3423 R1).
 *
 * Same mechanism as `detectIndent()` in `src/mcp/setup/local-http-config.ts`
 * — duplicated here rather than imported, since `packages/domain` does not
 * depend on `src/` (Clean Architecture: Domain → Adapters, not the reverse).
 *
 * Returns the whitespace VERBATIM for a tab-indented document rather than a
 * width — `JSON.stringify` accepts a string indent as readily as a number,
 * and collapsing tabs to a numeric default would itself reformat every line
 * of a tab-indented config, the exact hazard this function exists to avoid.
 */
export function detectJsonIndent(raw: string): string | number {
  const match = raw.match(/\n(\s+)"/);
  const indent = match?.[1];
  if (indent === undefined) return 2;
  if (indent.includes("\t")) return indent;
  return indent.length;
}

/**
 * Orchestrates registering Minsky as an MCP server with the given client.
 *
 * For clients with mergeConfig=true (e.g. Claude Desktop), reads the existing
 * config, merges the minsky-server entry into mcpServers, and writes it back.
 * For other clients, creates or overwrites the config file outright.
 */
export async function registerWithClient(
  projectRoot: string,
  mcpConfig: { transport: string; port?: number; host?: string },
  client = "cursor",
  fileSystem: FsLike = createRealFs(),
  overwrite = false
): Promise<void> {
  const registrar = getRegistrar(client);
  const newConfigJson = registrar.generateConfig(
    mcpConfig.transport,
    mcpConfig.port,
    mcpConfig.host
  );
  const filePath = registrar.configPath(projectRoot);

  if (registrar.mergeConfig && (await fileSystem.exists(filePath))) {
    const existing = await fileSystem.readFile(filePath, "utf-8");

    if (registrar.configFormat === "toml") {
      // TOML merge: check if minsky-server section already exists
      if (existing.includes("minsky-server")) {
        // Section exists — overwrite the whole file (user explicitly ran register)
        await fileSystem.writeFile(filePath, newConfigJson);
      } else {
        // Append the new section to existing content
        const separator = existing.endsWith("\n") ? "\n" : "\n\n";
        await fileSystem.writeFile(filePath, existing + separator + newConfigJson);
      }
    } else {
      // JSON merge: parse existing, merge mcpServers entries, write back
      const existingParsed = JSON.parse(existing) as Record<string, unknown>;
      const newParsed = JSON.parse(newConfigJson) as {
        mcpServers?: Record<string, unknown>;
        servers?: Record<string, unknown>;
      };

      // Handle both mcpServers (standard) and servers (VS Code) root keys
      const serverKey = newParsed.mcpServers ? "mcpServers" : "servers";
      const newServers = newParsed.mcpServers || newParsed.servers || {};

      const merged = {
        ...existingParsed,
        [serverKey]: {
          ...(existingParsed[serverKey] as Record<string, unknown> | undefined),
          ...newServers,
        },
      };
      // Preserve the existing file's indentation rather than forcing 2 spaces
      // (PR #3423 R1) — a vendor-owned state file re-serialized with a
      // different indent is a whole-file diff for a change the operator
      // never asked for.
      await fileSystem.writeFile(
        filePath,
        JSON.stringify(merged, undefined, detectJsonIndent(existing))
      );
    }
  } else {
    await createFileIfNotExists(filePath, newConfigJson, overwrite, fileSystem);
  }
}
