/**
 * mt#3091 — tests for the Dockerfile bun-build invocation generator/resolver.
 *
 * Mirrors `workspace-copy-detector.test.ts`'s block-templating coverage:
 * rendering, marker preservation, no-op when already fresh, missing-marker
 * error, and multi-line command handling.
 */

import { describe, test, expect } from "bun:test";

import {
  renderBunBuildBlock,
  applyGeneratedBunBuildBlock,
  BUN_BUILD_BLOCK_START,
  BUN_BUILD_BLOCK_END,
} from "./dockerfile-bun-build-detector";

const CANONICAL_COMMAND =
  "bun build --target=bun --outdir=dist --entry-naming minsky.js --sourcemap=external --minify src/cli.ts";

// Shared fixture fragments — factored out to a single definition so ESLint's
// custom/no-magic-string-duplication rule doesn't flag repeated literals
// across test cases.
const FIXTURE_FROM_LINE = "FROM oven/bun:1.2-slim AS base";
const FIXTURE_CMD_LINE = "CMD bun run dist/minsky.js";
const FIXTURE_GENERATED_COMMENT = "# Generated by ...";
const STALE_RUN_LINE =
  "RUN bun build --target=bun --outdir=dist --entry-naming minsky.js src/cli.ts";

function dockerfileWithBlock(runLine: string): string {
  return [
    FIXTURE_FROM_LINE,
    "WORKDIR /app",
    "",
    "# some other content",
    BUN_BUILD_BLOCK_START,
    FIXTURE_GENERATED_COMMENT,
    runLine,
    BUN_BUILD_BLOCK_END,
    "",
    FIXTURE_CMD_LINE,
  ].join("\n");
}

function dockerfileWithRenderedBlock(command: string): string {
  return [
    FIXTURE_FROM_LINE,
    "WORKDIR /app",
    "",
    "# some other content",
    renderBunBuildBlock(command),
    "",
    FIXTURE_CMD_LINE,
  ].join("\n");
}

describe("renderBunBuildBlock", () => {
  test("renders markers + explanatory comment + RUN line", () => {
    const block = renderBunBuildBlock(CANONICAL_COMMAND);
    expect(block.startsWith(BUN_BUILD_BLOCK_START)).toBe(true);
    expect(block.endsWith(BUN_BUILD_BLOCK_END)).toBe(true);
    expect(block).toContain(`RUN ${CANONICAL_COMMAND}`);
  });
});

describe("applyGeneratedBunBuildBlock", () => {
  test("no-op when the Dockerfile's block already matches canonical", () => {
    // Build the "already fresh" fixture from the real renderer, not a
    // hand-rolled comment — the block's comment text is also generated
    // content, so a fixture with different (but RUN-line-matching)
    // comment text would legitimately be flagged as changed.
    const text = dockerfileWithRenderedBlock(CANONICAL_COMMAND);
    const result = applyGeneratedBunBuildBlock(text, CANONICAL_COMMAND);
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.changed).toBe(false);
    expect(result.text).toBe(text);
  });

  test("regenerates a hand-edited RUN line back to canonical", () => {
    const staleText = dockerfileWithBlock(STALE_RUN_LINE);
    const result = applyGeneratedBunBuildBlock(staleText, CANONICAL_COMMAND);
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.changed).toBe(true);
    expect(result.text).toContain(`RUN ${CANONICAL_COMMAND}`);
    expect(result.text).not.toContain(STALE_RUN_LINE);
  });

  test("preserves content outside the marker block untouched", () => {
    const staleText = dockerfileWithBlock("RUN bun build --minify src/cli.ts");
    const result = applyGeneratedBunBuildBlock(staleText, CANONICAL_COMMAND);
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.text).toContain(FIXTURE_FROM_LINE);
    expect(result.text).toContain(FIXTURE_CMD_LINE);
  });

  test("returns an error when the Dockerfile is missing the marker block", () => {
    const text = [FIXTURE_FROM_LINE, "RUN bun build src/cli.ts"].join("\n");
    const result = applyGeneratedBunBuildBlock(text, CANONICAL_COMMAND);
    expect("error" in result).toBe(true);
    if (!("error" in result)) return;
    expect(result.error).toContain("missing the generated bun-build markers");
  });

  test("changes to the canonical command propagate through regeneration", () => {
    const text = dockerfileWithBlock(`RUN ${CANONICAL_COMMAND}`);
    const changedCommand =
      "bun build --target=bun --outdir=dist --entry-naming minsky.js --sourcemap=external --minify --define FOO=1 src/cli.ts";
    const result = applyGeneratedBunBuildBlock(text, changedCommand);
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.changed).toBe(true);
    expect(result.text).toContain(`RUN ${changedCommand}`);
  });

  // Reviewer-bot mt#3091 PR #2305 R1 BLOCKING: a non-global marker regex
  // would only rewrite the FIRST of two blocks (via non-greedy `[\s\S]*?`)
  // and silently leave a second, stale block untouched — not what a future
  // multi-stage Dockerfile (this module's docstring names
  // services/cockpit/Dockerfile's builder+runtime stages as the precedent
  // case) needs. This pins that BOTH blocks are regenerated.
  test("regenerates every block when the Dockerfile carries more than one (multi-stage)", () => {
    const text = [
      FIXTURE_FROM_LINE,
      "# builder stage",
      BUN_BUILD_BLOCK_START,
      FIXTURE_GENERATED_COMMENT,
      STALE_RUN_LINE,
      BUN_BUILD_BLOCK_END,
      "",
      "# runtime stage",
      BUN_BUILD_BLOCK_START,
      FIXTURE_GENERATED_COMMENT,
      STALE_RUN_LINE,
      BUN_BUILD_BLOCK_END,
      "",
      FIXTURE_CMD_LINE,
    ].join("\n");

    const result = applyGeneratedBunBuildBlock(text, CANONICAL_COMMAND);
    expect("error" in result).toBe(false);
    if ("error" in result) return;
    expect(result.changed).toBe(true);
    const occurrences = result.text.split(`RUN ${CANONICAL_COMMAND}`).length - 1;
    expect(occurrences).toBe(2);
    expect(result.text).not.toContain(STALE_RUN_LINE);
  });
});
