# Environment variable mappings for node-config
# Maps environment variables to configuration paths
# node-config automatically maps these to config structure

# Backend selection
backend: "MINSKY_BACKEND"

# Logger configuration
logger:
  mode: "MINSKY_LOG_MODE"
  level: "LOGLEVEL"
  enableAgentLogs: "ENABLE_AGENT_LOGS"

# GitHub credentials (align with custom system expectation)
github:
  token: "GITHUB_TOKEN"

# AI provider credentials (align with custom system expectation)
ai:
  providers:
    openai:
      api_key: "AI_PROVIDERS_OPENAI_API_KEY"
    anthropic:
      api_key: "AI_PROVIDERS_ANTHROPIC_API_KEY"
    google:
      api_key: "AI_PROVIDERS_GOOGLE_API_KEY"
    cohere:
      api_key: "AI_PROVIDERS_COHERE_API_KEY"
    mistral:
      api_key: "AI_PROVIDERS_MISTRAL_API_KEY"

# SessionDB configuration
sessiondb:
  backend: "MINSKY_SESSIONDB_BACKEND"
  sqlite:
    path: "MINSKY_SESSIONDB_SQLITE_PATH"
  postgres:
    connectionString: "MINSKY_SESSIONDB_POSTGRES_URL"
  baseDir: "MINSKY_SESSIONDB_BASE_DIR"
