# Environment variable mappings for node-config
# Maps environment variables to configuration paths
# node-config automatically maps these to config structure

# Backend selection
backend: "MINSKY_BACKEND"

# Logger configuration
logger:
  mode: "MINSKY_LOG_MODE"
  level: "LOGLEVEL"
  enableAgentLogs: "ENABLE_AGENT_LOGS"

# GitHub credentials
github:
  credentials:
    token: "GITHUB_TOKEN"

# AI provider credentials (using standard environment variable names)
ai:
  providers:
    openai:
      credentials:
        api_key: "OPENAI_API_KEY"
    anthropic:
      credentials:
        api_key: "ANTHROPIC_API_KEY"
    google:
      credentials:
        api_key: "GOOGLE_AI_API_KEY"
    cohere:
      credentials:
        api_key: "COHERE_API_KEY"
    mistral:
      credentials:
        api_key: "MISTRAL_API_KEY"

# SessionDB configuration
sessiondb:
  backend: "MINSKY_SESSIONDB_BACKEND"
  sqlite:
    path: "MINSKY_SESSIONDB_SQLITE_PATH"
  postgres:
    connectionString: "MINSKY_SESSIONDB_POSTGRES_URL"
  baseDir: "MINSKY_SESSIONDB_BASE_DIR"
