# Test environment configuration for Minsky
# This file is used when NODE_ENV=test to avoid warnings from node-config

# Use the same defaults as the default configuration for tests
backend: "markdown"

# Backend-specific configurations
backendConfig:
  github-issues: {}
  markdown: {}
  json-file: {}

# Session database configuration for tests - match default.yaml
sessiondb:
  backend: "sqlite"
  baseDir: null
  dbPath: null
  connectionString: null

# Detection rules for tests
detectionRules:
  - condition: "tasks_md_exists"
    backend: "markdown"
  - condition: "json_file_exists"
    backend: "json-file"
  - condition: "always"
    backend: "markdown"

# Logger configuration - match default.yaml
logger:
  mode: "auto"          # "HUMAN" | "STRUCTURED" | "auto"
  level: "info"         # "debug" | "info" | "warn" | "error"
  enableAgentLogs: false # Enable JSON logs in HUMAN mode

# GitHub configuration
github: {}

# AI configuration
ai:
  providers:
    openai:
      enabled: true
      models: []
    anthropic:
      enabled: true
      models: []
    google:
      enabled: true
      models: []
    cohere:
      enabled: true
      models: []
    mistral:
      enabled: true
      models: []
