import {
  pgTable,
  text,
  integer,
  timestamp,
  jsonb,
  boolean,
  primaryKey,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { vector, customType } from "drizzle-orm/pg-core";
import { agentTranscriptsTable } from "./agent-transcripts-schema";

/**
 * Custom tsvector type for Postgres full-text search.
 *
 * Drizzle ORM does not have a built-in tsvector column type. We declare it
 * as a custom type so Drizzle can model the generated column without trying
 * to serialize/deserialize the value from user-space code.
 */
const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector";
  },
});

/**
 * Agent transcript turns table — per-turn rows extracted from agent session transcripts.
 *
 * Each row holds one conversation turn: the user prompt, the assistant response,
 * any tool calls made, timing information, a vector embedding for semantic search,
 * and a generated tsvector column for Postgres FTS.
 *
 * Spawn-boundary turns (where the agent invoked a subagent via the Agent tool) are
 * flagged with is_spawn_boundary = true. Their tool-result payload is excluded from
 * assistant_text, embedding, and fts_text to avoid 2x storage of subagent content.
 *
 * @see mt#1313 — Transcript search: harness-agnostic ingestion
 * @see mt#1324 — Foundation schema migration
 */
export const agentTranscriptTurnsTable = pgTable(
  "agent_transcript_turns",
  {
    agentSessionId: text("agent_session_id")
      .notNull()
      .references(() => agentTranscriptsTable.agentSessionId),

    turnIndex: integer("turn_index").notNull(),

    // Turn content
    userText: text("user_text"),
    /**
     * Who authored `user_text` (mt#4289): `'human'` for genuine operator
     * speech, a harness kind (`compact_summary`, `harness_meta`,
     * `task_notification`, `peer`, `sdk`, …) for content Claude Code generated
     * and recorded on a `user`-role line.
     *
     * Non-null exactly when `user_text` is. Measured against prod 2026-08-19:
     * 8,245 of 18,948 `user_text` rows (43.5%) are harness-generated, and until
     * this column every consumer that branched on `type: "user"` read all of
     * them as the operator speaking.
     *
     * Deliberately `text` and not a boolean or an enum. A boolean would force
     * the next kind into a second column; a Postgres enum would make a new
     * harness kind a migration rather than a row. The vocabulary is partly the
     * HARNESS's, so it must be able to grow without us shipping anything —
     * see `transcripts/user-line-origin.ts`.
     */
    userOrigin: text("user_origin"),
    assistantText: text("assistant_text"),
    toolCalls: jsonb("tool_calls"),

    // Turn timing
    startedAt: timestamp("started_at", { withTimezone: true }),
    endedAt: timestamp("ended_at", { withTimezone: true }),

    // Vector embedding for semantic similarity search
    embedding: vector("embedding", { dimensions: 1536 }),

    // Full-text search column — generated by Postgres from user_text + assistant_text.
    // The GENERATED ALWAYS AS clause is applied in the migration SQL; Drizzle models
    // the column type here for query-building purposes only.
    ftsText: tsvector("fts_text").generatedAlwaysAs(
      sql`to_tsvector('english', coalesce(user_text, '') || ' ' || coalesce(assistant_text, ''))`
    ),

    // Subagent spawn boundary flag — true when this turn invoked a subagent via the Agent tool.
    // The tool-result payload for spawn-boundary turns is excluded from assistantText / embedding / ftsText.
    isSpawnBoundary: boolean("is_spawn_boundary").default(false),
  },
  (table) => [
    primaryKey({ columns: [table.agentSessionId, table.turnIndex] }),
    index("idx_agent_transcript_turns_fts").using("gin", table.ftsText),
    index("idx_agent_transcript_turns_embedding").using(
      "hnsw",
      table.embedding.asc().nullsLast().op("vector_l2_ops")
    ),

    /**
     * The embedding backfill's candidate lookup (mt#4623).
     *
     * `PerTurnEmbeddingPipeline.run()` selects on exactly this predicate, and
     * without an index it is a full sequential scan: measured against
     * production 2026-08-26, `Rows Removed by Filter: 367098` and ~37,500
     * buffers to return 59 rows.
     *
     * PARTIAL on purpose, and the reason is the shape of the data rather than
     * a general preference. Two populations make the full-index version a bad
     * trade: 211,300 of 367,159 rows (57.6%) carry no text at all and can
     * never be candidates, and the real backlog sits near zero — 62 rows when
     * measured. So this index covers tens of rows where a plain
     * `embedding IS NULL` index would cover hundreds of thousands, and it
     * SHRINKS as the backfill drains rather than growing with the table. That
     * matters because this table is written on every transcript ingest.
     *
     * Columns are the primary key, so the optional `agent_session_id`
     * equality the pipeline adds for a single-session run is served by the
     * same index.
     *
     * NOT `.concurrently()`. drizzle's `migrate()` applies each migration
     * inside a transaction (`drizzle-orm/pg-core/dialect.js` —
     * `session.transaction(...)`), and Postgres forbids
     * `CREATE INDEX CONCURRENTLY` there. The build therefore takes ACCESS
     * EXCLUSIVE for its duration; see migration 0111's lock note for the
     * measured window and the row count it was measured at.
     */
    index("idx_agent_transcript_turns_embedding_backlog")
      .on(table.agentSessionId, table.turnIndex)
      .where(
        sql`${table.embedding} IS NULL AND (${table.userText} IS NOT NULL OR ${table.assistantText} IS NOT NULL)`
      ),

    /**
     * The cockpit Messages page's receiver lookup (mt#4874).
     *
     * `user_origin` carries no index of its own, so selecting the delivered
     * peer messages is a parallel sequential scan of the whole table: measured
     * against production 2026-09-02, `Rows Removed by Filter: 197,081` per
     * worker (394,170 total), ~39,000 buffers, 575 ms — to return **12 rows**,
     * on a widget that polls every 60 seconds.
     *
     * PARTIAL for the same reason as the backlog index above, only more so: the
     * predicate matches 12 of 394,170 rows. Unlike that one this does not shrink
     * over time, but it grows only with genuine cross-session traffic, which is
     * inherently low-volume — 12 rows in the corpus to date.
     *
     * Columns are the primary key, so the reader gets the identifiers it needs
     * without a heap fetch.
     *
     * Lock note (the 0068 convention, with this table's own numbers). Plain
     * CREATE INDEX, not CONCURRENTLY, for the reason migration 0111 records for
     * this same table: drizzle's `migrate()` runs each migration inside a
     * transaction, where Postgres forbids CONCURRENTLY. The measured bound is
     * 0111's and it still holds — a partial index scans every heap row to
     * evaluate its predicate, so the build tracks the full scan, and this
     * table's production seq scan is the 575 ms measured above. Sub-second, so
     * the plain form is the right trade.
     *
     * **Those numbers have a shelf life (PR #3562 R1).** They were measured on
     * 2026-09-02 at 394,170 rows here and 411,324 in
     * `agent_tool_call_projection`, and both tables are written on every
     * transcript ingest — so they grow, and the lock window grows with them.
     * Before applying migration 0116 materially later than that date, or before
     * copying this justification into a new index on either table, re-measure
     * rather than inheriting the figure:
     *
     * ```sql
     * EXPLAIN (ANALYZE, BUFFERS) SELECT count(*) FROM agent_transcript_turns;
     * EXPLAIN (ANALYZE, BUFFERS) SELECT count(*) FROM agent_tool_call_projection;
     * ```
     *
     * A full scan an order of magnitude slower than the above means the ACCESS
     * EXCLUSIVE window is no longer negligible: apply in a low-traffic window,
     * or build the index out-of-band with `CREATE INDEX CONCURRENTLY` first.
     * (This note lives here rather than in 0116's own SQL because an applied
     * migration is immutable — drizzle hashes the file, so editing it would
     * re-apply and drift the ledger.)
     */
    index("idx_agent_transcript_turns_peer_origin")
      .on(table.agentSessionId, table.turnIndex)
      .where(sql`${table.userOrigin} = 'peer'`),
  ]
);
