/**
 * Rules CRUD Operations
 *
 * Functions for listing, getting, creating, updating, generating, and compiling rules.
 */

import fs from "fs/promises";
import path from "path";
import { RuleService, type RuleFormat } from "../../rules";
import { createRuleTemplateService } from "../rule-template-service";
import { type RuleGenerationConfig } from "../template-system";
import { readContentFromFileIfExists, parseGlobs } from "../../../utils/rules-helpers";
import type {
  ListRulesOptions,
  ListRulesResult,
  CompileRulesOptions,
  CompileRulesResult,
  GetRuleOptions,
  GetRuleResult,
  GenerateRulesOptions,
  GenerateRulesResult,
  CreateRuleOptions,
  CreateRuleResult,
  UpdateRuleOptions,
  UpdateRuleResult,
} from "./types";

// ─── List Rules ──────────────────────────────────────────────────────────────

/**
 * List rules with optional time-range filtering.
 * Time filtering uses file modification time as a proxy for updatedAt.
 */
export async function listRulesFiltered(options: ListRulesOptions): Promise<ListRulesResult> {
  const ruleService = new RuleService(options.workspacePath);

  const rules = await ruleService.listRules({
    format: options.format,
    tag: options.tag,
    debug: options.debug,
  });

  // Optional time filtering using file modification time as proxy
  type RuleWithUpdatedAt = (typeof rules)[0] & { updatedAt?: Date };
  let filtered: RuleWithUpdatedAt[] = rules;
  try {
    const { parseTime, filterByTimeRange } = await import("../../../utils/result-handling/filters");
    const sinceTs = parseTime(options.since);
    const untilTs = parseTime(options.until);
    if (sinceTs !== null || untilTs !== null) {
      const withUpdatedAt = await Promise.all(
        rules.map(async (rule): Promise<RuleWithUpdatedAt> => {
          try {
            const stat = await fs.stat(rule.path);
            return { ...rule, updatedAt: new Date(stat.mtimeMs) };
          } catch {
            return { ...rule };
          }
        })
      );
      filtered = filterByTimeRange(withUpdatedAt, sinceTs, untilTs);
    }
  } catch {
    // ignore filtering errors
  }

  // Transform rules to exclude content field for better usability
  const rulesWithoutContent = filtered.map(({ content, ...rule }) => rule);

  return { success: true, rules: rulesWithoutContent };
}

// ─── Compile Rules ───────────────────────────────────────────────────────────

/**
 * Compile rules into a monolithic file, with optional check (staleness) mode.
 */
export async function compileRules(options: CompileRulesOptions): Promise<CompileRulesResult> {
  const { createCompileService } = await import("../compile/compile-service");

  const targetId = options.target || "agents.md";
  const ruleService = new RuleService(options.workspacePath);
  const compileService = createCompileService();

  // For check mode, do a dry-run first to get the compiled content, then compare on disk
  if (options.check) {
    const dryResult = await compileService.compile(ruleService, targetId, {
      workspacePath: options.workspacePath,
      outputPath: options.output,
      dryRun: true,
      memoryLoadingMode: options.memoryLoadingMode,
    });

    // Get the registered target so we can call listOutputFiles (generalized target map)
    const target = compileService.getTarget(targetId);
    if (!target) {
      throw new Error(`Unknown compile target: "${targetId}"`);
    }

    // Get the rule set once — used for listOutputFiles and cursor-rules per-file content
    let allRules = await ruleService.listRules({});

    // For cursor-rules, exclude rules whose .cursor/rules/<id>.mdc file is owned by the
    // cursor-rules-ts target (TS-sourced rules in .minsky/rules/<name>/rule.ts subdirs).
    // .cursor/rules/ is a shared output directory — the legacy check should not try to
    // re-serialize or orphan-flag files generated by the TS-first pipeline.
    if (targetId === "cursor-rules") {
      const tsSrcDir = path.join(options.workspacePath, ".minsky", "rules");
      const tsOwnedIds = new Set<string>();
      try {
        const ruleDirs = await fs.readdir(tsSrcDir);
        for (const dirEntry of ruleDirs) {
          const ruleTsPath = path.join(tsSrcDir, dirEntry, "rule.ts");
          try {
            await fs.access(ruleTsPath);
            tsOwnedIds.add(dirEntry);
          } catch {
            // No rule.ts — not a TS-sourced rule dir
          }
        }
      } catch {
        // .minsky/rules/ doesn't exist — skip
      }
      if (tsOwnedIds.size > 0) {
        allRules = allRules.filter((r) => !tsOwnedIds.has(r.id));
      }
    }

    // Determine which files this target would write
    const expectedFiles = target.listOutputFiles(
      allRules,
      { outputPath: options.output },
      options.workspacePath
    );

    // Check every expected output file for staleness
    let staleFile: string | undefined;

    // For cursor-rules, build the per-file content map once outside the loop
    let cursorFilesMap: Map<string, string> | undefined;
    if (targetId === "cursor-rules") {
      const { buildCursorRulesContent } = await import("../compile/targets/cursor-rules");
      const outputDir = options.output || target.defaultOutputPath(options.workspacePath);
      const { files } = buildCursorRulesContent(allRules, outputDir);
      cursorFilesMap = new Map(files.map((f) => [f.path, f.content]));
    }

    for (const filePath of expectedFiles) {
      let existingContent: string;
      try {
        existingContent = String(await fs.readFile(filePath, "utf-8"));
      } catch {
        // File doesn't exist — stale
        staleFile = filePath;
        break;
      }

      // For single-file targets, dryResult.content holds the full content.
      // For cursor-rules (multi-file), use the pre-built per-file content map.
      let expectedContent: string | undefined;
      if (targetId === "cursor-rules") {
        expectedContent = cursorFilesMap?.get(filePath);
      } else {
        expectedContent = dryResult.content;
      }

      if (expectedContent === undefined || existingContent !== expectedContent) {
        staleFile = filePath;
        break;
      }
    }

    // For cursor-rules, also detect orphan .mdc files: files in the output dir that
    // the current compile would NOT produce (stale removals).
    if (!staleFile && targetId === "cursor-rules") {
      const outputDir = options.output || target.defaultOutputPath(options.workspacePath);
      try {
        const entries = await fs.readdir(outputDir);
        const expectedSet = new Set(expectedFiles.map((f) => path.basename(f)));

        // Also include files owned by the cursor-rules-ts target (TS-sourced rules in
        // .minsky/rules/<name>/rule.ts subdirs). .cursor/rules/ is a shared output
        // directory — these files should not be flagged as orphans by the legacy check.
        const tsSrcDir = path.join(options.workspacePath, ".minsky", "rules");
        try {
          const ruleDirs = await fs.readdir(tsSrcDir);
          for (const dirEntry of ruleDirs) {
            const ruleTsPath = path.join(tsSrcDir, dirEntry, "rule.ts");
            try {
              await fs.access(ruleTsPath);
              expectedSet.add(`${dirEntry}.mdc`);
            } catch {
              // No rule.ts — not a TS-sourced rule dir
            }
          }
        } catch {
          // .minsky/rules/ doesn't exist or not readable — skip TS-source discovery
        }

        for (const entry of entries) {
          if (entry.endsWith(".mdc") && !expectedSet.has(entry)) {
            staleFile = path.join(outputDir, entry);
            break;
          }
        }
      } catch {
        // Directory doesn't exist — already handled above via expectedFiles check
      }
    }

    const isStale = staleFile !== undefined;
    return {
      success: true,
      check: true,
      stale: isStale,
      staleFile: staleFile,
      rulesIncluded: dryResult.rulesIncluded,
      rulesSkipped: dryResult.rulesSkipped,
    };
  }

  const result = await compileService.compile(ruleService, targetId, {
    workspacePath: options.workspacePath,
    outputPath: options.output,
    dryRun: options.dryRun || false,
    memoryLoadingMode: options.memoryLoadingMode,
  });

  if (options.dryRun) {
    return {
      success: true,
      dryRun: true,
      content: result.content,
      filesWritten: result.filesWritten,
      rulesIncluded: result.rulesIncluded,
      rulesSkipped: result.rulesSkipped,
    };
  }

  return {
    success: true,
    dryRun: false,
    filesWritten: result.filesWritten,
    rulesIncluded: result.rulesIncluded,
    rulesSkipped: result.rulesSkipped,
  };
}

// ─── Get Rule ────────────────────────────────────────────────────────────────

/**
 * Get a specific rule by ID.
 */
export async function getRule(options: GetRuleOptions): Promise<GetRuleResult> {
  const ruleService = new RuleService(options.workspacePath);
  const rule = await ruleService.getRule(options.id, {
    format: options.format,
    debug: options.debug,
  });
  return { success: true, rule };
}

// ─── Generate Rules ──────────────────────────────────────────────────────────

/**
 * Generate rules from templates.
 */
export async function generateRules(options: GenerateRulesOptions): Promise<GenerateRulesResult> {
  const ruleTemplateService = createRuleTemplateService(options.workspacePath);
  await ruleTemplateService.registerDefaultTemplates();

  const config: RuleGenerationConfig = {
    interface: (options.interface || "cli") as "cli" | "mcp" | "hybrid",
    mcpEnabled: options.interface === "mcp" || options.interface === "hybrid",
    mcpTransport: (options.mcpTransport || "stdio") as "stdio" | "http",
    preferMcp: options.preferMcp || false,
    ruleFormat: (options.format || "minsky") as RuleFormat,
    outputDir:
      options.outputDir ||
      (options.format === "cursor"
        ? ".cursor/rules"
        : options.format === "generic"
          ? ".ai/rules"
          : ".minsky/rules"),
  };

  const selectedRules = options.rules ? options.rules.split(",").map((t) => t.trim()) : undefined;
  const dryRun = options.dryRun || false;
  const overwrite = options.overwrite || false;

  const result = await ruleTemplateService.generateRules({
    config,
    selectedRules,
    dryRun,
    overwrite,
  });
  return {
    success: result.success,
    rules: result.rules,
    errors: result.errors,
    generated: result.rules.length,
  };
}

// ─── Create Rule ─────────────────────────────────────────────────────────────

/**
 * Create a new rule.
 */
export async function createRule(options: CreateRuleOptions): Promise<CreateRuleResult> {
  const ruleService = new RuleService(options.workspacePath);
  const content = await readContentFromFileIfExists(options.content);
  const globs = parseGlobs(options.globs);
  const tags = options.tags ? options.tags.split(",").map((tag: string) => tag.trim()) : undefined;

  const meta = {
    name: options.name || options.id,
    description: options.description,
    globs,
    tags,
  };

  const rule = await ruleService.createRule(options.id, content, meta, {
    format: options.format,
    overwrite: options.overwrite,
  });

  return { success: true, rule };
}

// ─── Update Rule ─────────────────────────────────────────────────────────────

/**
 * Update an existing rule.
 */
export async function updateRule(options: UpdateRuleOptions): Promise<UpdateRuleResult> {
  const ruleService = new RuleService(options.workspacePath);
  const content = options.content ? await readContentFromFileIfExists(options.content) : undefined;
  const globs = options.globs ? parseGlobs(options.globs) : undefined;
  const tags = options.tags ? options.tags.split(",").map((tag: string) => tag.trim()) : undefined;

  const meta: Record<string, unknown> = {};
  if (options.name !== undefined) meta.name = options.name;
  if (options.description !== undefined) meta.description = options.description;
  if (globs !== undefined) meta.globs = globs;
  if (tags !== undefined) meta.tags = tags;

  const rule = await ruleService.updateRule(
    options.id,
    {
      content,
      meta: Object.keys(meta).length > 0 ? meta : undefined,
    },
    { format: options.format, debug: options.debug }
  );

  return { success: true, rule };
}
