/* eslint-disable custom/no-real-fs-in-tests -- this test spawns the REAL dispatcher entrypoint as a subprocess (Bun.spawn); the transcript fixture and CLAUDE_PROJECT_DIR must be real files/directories on disk for that subprocess to read, exactly as the sibling dispatch-userpromptsubmit.phase2b-parity.test.ts is exempted for the same reason */
// e2e canary test — mt#2835.
//
// Every existing UserPromptSubmit test either invokes a guard's `run()`
// directly (in-process, no subprocess) or spawns an INDIVIDUAL guard's own
// standalone CLI entrypoint (`dispatch-userpromptsubmit.phase2b-parity.test.ts`
// invokes e.g. `auto-session-title.ts` alone via `Bun.spawn`). Neither class
// of test ever spawns the REAL `dispatch-userpromptsubmit.ts` entrypoint with
// its full registered guard chain and a real piped-stdin payload — which is
// exactly the configuration that let `auto-session-title.ts`'s ungated
// module-level `main().catch(() => process.exit(0))` kill the whole
// dispatcher process mid-loop, before any guard downstream of it (including
// `inject-current-time`) got to contribute its `additionalContext`, and
// before the dispatcher's own `writeOutputFn` call ever ran. Exit code was
// still 0, so the harness saw a "healthy" hook that silently emitted
// nothing — see mt#2835's spec for the full failure-chain writeup.
//
// This test closes that gap: it spawns the real `dispatch-userpromptsubmit.ts`
// file exactly as Claude Code does (JSON payload piped on stdin, no
// in-process shortcuts) and asserts the consolidated `additionalContext`
// contains `inject-current-time`'s `"Current time:"` marker — proof the
// dispatcher ran ALL matched guards to completion and actually wrote output.
//
// Runs against BOTH the `.minsky/hooks/` SOURCE entrypoint AND the compiled
// `.claude/hooks/` entrypoint Claude Code actually invokes (mt#2835's own
// first success criterion names the literal `.claude/hooks/` path — see PR
// #1948 review R1: the initial version of this test covered only the source
// path). The two must stay in parity via `minsky compile --target
// claude-hooks`; testing both catches a future compile-output drift, not
// just a source-only regression.
//
// `CLAUDE_PROJECT_DIR` (and the spawned process's `cwd`) are set to a fresh
// temp directory for the duration of the call so every guard's
// calibration/state writes (calibration JSONL, skill-staleness baseline,
// mcp-daemon-staleness tracker, etc.) land under an isolated directory
// instead of the real repo's `.minsky/` — this test must never mutate real
// repo state.
//
// @see mt#2835 — this task (root-cause + fix spec)
// @see .minsky/hooks/dispatch-userpromptsubmit.ts — the source entrypoint under test
// @see .claude/hooks/dispatch-userpromptsubmit.ts — the compiled entrypoint under test (generated by `minsky compile --target claude-hooks`; do not hand-edit)
// @see .minsky/hooks/auto-session-title.ts — the guard whose ungated main() caused the death
// @see .minsky/hooks/dispatch-userpromptsubmit.phase2b-parity.test.ts — sibling tests (in-process run() + standalone single-guard CLI; neither exercises the dispatcher's own process with the full chain)
// @see .minsky/hooks/guard-entrypoint-gate.test.ts — the parity check (static scan) for the same regression class

import { describe, test, expect, afterEach } from "bun:test";
import { mkdtempSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import type { HookOutput } from "./types";

const SOURCE_DISPATCHER_PATH = new URL("./dispatch-userpromptsubmit.ts", import.meta.url).pathname;

/**
 * Resolve the compiled `.claude/hooks/dispatch-userpromptsubmit.ts` path
 * from this test file's own location — `.minsky/hooks/` and `.claude/hooks/`
 * are always sibling directories one level under the repo root (mirrors the
 * `minsky compile --target claude-hooks` output layout).
 */
const COMPILED_DISPATCHER_PATH = resolve(
  new URL(".", import.meta.url).pathname,
  "..",
  "..",
  ".claude",
  "hooks",
  "dispatch-userpromptsubmit.ts"
);

const tmpDirs: string[] = [];
function makeTmpDir(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  tmpDirs.push(dir);
  return dir;
}

afterEach(() => {
  while (tmpDirs.length > 0) {
    const dir = tmpDirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

/**
 * Spawn a dispatcher entrypoint at `dispatcherPath`, piping `payload` as JSON
 * on stdin — the exact invocation shape Claude Code uses (see
 * `.claude/settings.json`'s `dispatch-userpromptsubmit.ts` registration).
 * `projectDir` is passed as BOTH the subprocess `cwd` AND the
 * `CLAUDE_PROJECT_DIR` env var so every guard resolves state/calibration
 * paths under the isolated temp directory.
 */
async function invokeDispatcher(
  dispatcherPath: string,
  payload: Record<string, unknown>,
  projectDir: string
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  const proc = Bun.spawn(["bun", "run", dispatcherPath], {
    cwd: projectDir,
    stdin: "pipe",
    stdout: "pipe",
    stderr: "pipe",
    env: { ...process.env, CLAUDE_PROJECT_DIR: projectDir },
  });
  proc.stdin.write(JSON.stringify(payload));
  proc.stdin.end();
  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  const exitCode = await proc.exited;
  return { exitCode, stdout, stderr };
}

describe("dispatch-userpromptsubmit.ts e2e canary (mt#2835)", () => {
  test("sanity: both dispatcher paths under test actually exist on disk", () => {
    // Guards against a silent no-op if either path resolution is wrong (the
    // compiled path in particular is derived via relative directory walking,
    // not a literal sibling import) — a typo there would make the compiled
    // variant below vacuously pass by failing to spawn anything meaningful.
    expect(existsSync(SOURCE_DISPATCHER_PATH)).toBe(true);
    expect(existsSync(COMPILED_DISPATCHER_PATH)).toBe(true);
  });

  test.each([
    ["source (.minsky/hooks/)", SOURCE_DISPATCHER_PATH],
    ["compiled (.claude/hooks/)", COMPILED_DISPATCHER_PATH],
  ])(
    "%s: real entrypoint + real piped stdin emits consolidated additionalContext with inject-current-time's marker",
    async (_label, dispatcherPath) => {
      const projectDir = makeTmpDir("mt2835-dispatcher-e2e-");
      const transcriptPath = join(projectDir, "fixture-transcript.jsonl");

      // Minimal-but-valid transcript: two real user prompts bracketing one
      // assistant turn, no trigger phrases. Keeps the six transcript-reading
      // guidance detectors (substrate-bypass, retrospective-trigger,
      // pre-narration, causal-premise, code-mechanism-assertion,
      // ask-routing-deferral) at their silent/no-match path — this canary is
      // about proving the dispatcher runs the FULL chain to completion, not
      // about exercising any one detector's matching logic (those have their
      // own dedicated test suites).
      const transcriptLines = [
        { type: "user", message: { role: "user", content: "first turn" } },
        { type: "assistant", message: { role: "assistant", content: "ack" } },
        { type: "user", message: { role: "user", content: "second turn" } },
      ];
      writeFileSync(
        transcriptPath,
        `${transcriptLines.map((l) => JSON.stringify(l)).join("\n")}\n`
      );

      const payload = {
        session_id: "mt2835-e2e-canary-session",
        transcript_path: transcriptPath,
        cwd: projectDir,
        hook_event_name: "UserPromptSubmit",
        // Short prompt keeps memory-search on its trivial-prompt (no-network)
        // path — this canary must be fast and deterministic, not exercise
        // memory-search's actual retrieval behavior (covered elsewhere).
        prompt: "hi",
      };

      const result = await invokeDispatcher(dispatcherPath, payload, projectDir);

      expect(result.exitCode).toBe(0);
      // The regression this test guards against: the dispatcher process dying
      // mid-loop (exit 0, but zero stdout) before writeOutputFn ever runs.
      expect(result.stdout.trim().length).toBeGreaterThan(0);

      const parsed = JSON.parse(result.stdout) as HookOutput;
      expect(parsed.hookSpecificOutput?.additionalContext).toBeDefined();
      expect(parsed.hookSpecificOutput?.additionalContext).toContain("Current time:");
    }
  );
});
