#!/usr/bin/env bun
/**
 * Unit tests for knowledge-acquisition-detector.ts
 *
 * Covers the mt#2708 acceptance tests:
 * - fires on research-without-propagation (rung 1 + rung-2-lite keyword overlap)
 * - suppressed when memory_create / `/learn` / tasks_create occurred in the trailing window
 * - suppressed when the research has no keyword overlap with any loaded skill
 * - not-yet-due grace period respected (fewer than TRAILING_WINDOW_TURNS elapsed)
 * - dedupe: an already-logged occurrence never re-fires
 * - silent on first turn and on transcript errors
 * - MANDATORY tool-interleaved transcript fixture (tool_result lines carry role "user" —
 *   memory a3e60471): trigger research tool_use -> tool_result (user-role) -> assistant
 *   text -> real user prompt
 * - the originating incident replayed (2026-06-24 essay session shape: WebSearch on
 *   AI-writing tells with `engineering-writing` loaded, no propagation) produces a match
 *
 * The tool-interleaved + originating-incident tests exercise the REAL `run()` entry point
 * against the REAL `engineering-writing` SKILL.md on disk (via `input.cwd = import.meta.dir`,
 * which `findRepoRoot` resolves to this repo's root) rather than injecting a fake keyword
 * map — the acceptance test's whole point is proving the keyword-overlap gate works against
 * a real skill's real frontmatter, not just a synthetic stand-in. All other scenarios use
 * the pure `detectKnowledgeAcquisition` function with an injected keyword map, per
 * `custom/no-real-fs-in-tests`.
 *
 * @see mt#2708
 */

import { describe, test, expect } from "bun:test";
import {
  detectKnowledgeAcquisition,
  extractFrontmatterDescription,
  extractSkillKeywords,
  INJECTION_ENABLED,
  OVERRIDE_ENV_VAR,
  TRAILING_WINDOW_TURNS,
  RESEARCH_TOOL_NAMES,
  run,
} from "./knowledge-acquisition-detector";
import type { TranscriptLine } from "./transcript";
import type { ClaudeHookInput } from "./types";
import type { DispatchContext } from "./registry";

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

function userPromptLine(text: string): TranscriptLine {
  return { type: "user", message: { role: "user", content: text } };
}

function assistantLine(content: Array<Record<string, unknown>>): TranscriptLine {
  return { type: "assistant", message: { role: "assistant", content } };
}

function toolUseBlock(name: string, input: Record<string, unknown> = {}): Record<string, unknown> {
  return { type: "tool_use", name, input };
}

function textBlock(text: string): Record<string, unknown> {
  return { type: "text", text };
}

/** A tool_result line — Claude Code records these with `role: "user"` (memory a3e60471). */
function toolResultLine(toolUseId: string, resultText: string): TranscriptLine {
  return {
    type: "user",
    message: {
      role: "user",
      content: [
        {
          type: "tool_result",
          tool_use_id: toolUseId,
          content: [{ type: "text", text: resultText }],
        },
      ],
    },
  };
}

function skillLoadLine(skillName: string): TranscriptLine {
  return assistantLine([
    toolUseBlock("Skill", { skill: skillName }),
    textBlock(`Loading ${skillName}.`),
  ]);
}

function fillerTurn(promptText: string, assistantText: string): TranscriptLine[] {
  return [userPromptLine(promptText), assistantLine([textBlock(assistantText)])];
}

const HOOK_EVENT_NAME = "UserPromptSubmit" as const;

function makeCtx(transcriptLines: TranscriptLine[]): DispatchContext {
  return {
    event: HOOK_EVENT_NAME,
    hostCapSec: 15,
    budgets: { overallBudgetMs: 9000, fetchTimeoutMs: 4950, gitTimeoutMs: 1530 },
    transcriptCandidates: ["/mock/transcript.jsonl"],
    transcriptLines,
  };
}

const FAKE_HOOK_INPUT: ClaudeHookInput = {
  session_id: "mt2708-test-session",
  transcript_path: "/mock/transcript.jsonl",
  cwd: "/nonexistent/fake/repo",
  hook_event_name: HOOK_EVENT_NAME,
};

/** The real, on-disk skill this file's originating-incident replay tests exercise. */
const ENGINEERING_WRITING_SKILL = "engineering-writing";

// ---------------------------------------------------------------------------
// extractFrontmatterDescription
// ---------------------------------------------------------------------------

describe("extractFrontmatterDescription", () => {
  test("extracts a block-scalar (>-) description", () => {
    const content = [
      "---",
      "# Generated by minsky compile. Do not edit directly.",
      "name: engineering-writing",
      "description: >-",
      "  Writing engineering essays, position papers, technical blog posts, and",
      "  architecture memos intended for external readers.",
      "user-invocable: true",
      "---",
      "",
      "# Engineering Writing",
    ].join("\n");
    const result = extractFrontmatterDescription(content);
    expect(result).toContain("engineering essays");
    expect(result).toContain("architecture memos");
  });

  test("extracts an inline scalar description", () => {
    const content = [
      "---",
      "name: foo-skill",
      "description: A short inline description.",
      "---",
      "body",
    ].join("\n");
    expect(extractFrontmatterDescription(content)).toBe("A short inline description.");
  });

  test("returns empty string when there is no description key", () => {
    const content = ["---", "name: foo-skill", "user-invocable: true", "---", "body"].join("\n");
    expect(extractFrontmatterDescription(content)).toBe("");
  });

  test("returns empty string when frontmatter is unterminated", () => {
    const content = ["---", "name: foo-skill", "description: never closed"].join("\n");
    expect(extractFrontmatterDescription(content)).toBe("");
  });

  test("returns empty string for content with no leading ---", () => {
    expect(extractFrontmatterDescription("# just a heading\nno frontmatter here")).toBe("");
  });
});

// ---------------------------------------------------------------------------
// extractSkillKeywords
// ---------------------------------------------------------------------------

describe("extractSkillKeywords", () => {
  test("derives keywords from the hyphenated skill name", () => {
    const keywords = extractSkillKeywords(ENGINEERING_WRITING_SKILL, "");
    expect(keywords).toContain("engineering");
    expect(keywords).toContain("writing");
  });

  test("derives distinctive keywords from the description, excluding stopwords", () => {
    const keywords = extractSkillKeywords(
      ENGINEERING_WRITING_SKILL,
      "long-form argumentative prose intended for external readers"
    );
    expect(keywords).toContain("argumentative");
    expect(keywords).toContain("prose");
    // "intended" is a stopword, deliberately excluded.
    expect(keywords).not.toContain("intended");
  });

  test("excludes short words (< 5 chars) from the description", () => {
    const keywords = extractSkillKeywords("foo-bar", "use when doing a task");
    expect(keywords).not.toContain("task");
  });
});

// ---------------------------------------------------------------------------
// detectKnowledgeAcquisition (pure core — injected keyword map, no real fs)
// ---------------------------------------------------------------------------

describe("detectKnowledgeAcquisition", () => {
  const SKILL = ENGINEERING_WRITING_SKILL;
  const KEYWORDS = new Map<string, string[]>([[SKILL, ["argumentative", "prose"]]]);

  /** Builds: skill loaded (turn 0), research call (turn 1), N filler turns, current prompt. */
  function buildLines(opts: {
    researchToolName?: string;
    researchQuery?: string;
    fillerTurns: number;
    propagationToolName?: string;
    propagationInFillerIndex?: number; // 0-based filler-turn index to inject propagation into
    learnSkillInFillerIndex?: number;
  }): TranscriptLine[] {
    const lines: TranscriptLine[] = [
      userPromptLine("please write an essay about AI writing tells"),
      skillLoadLine(SKILL),
      userPromptLine("go ahead and research it"),
      assistantLine([
        toolUseBlock(opts.researchToolName ?? "WebSearch", {
          query: opts.researchQuery ?? "argumentative prose AI writing tells overused phrases",
        }),
      ]),
    ];
    for (let i = 0; i < opts.fillerTurns; i++) {
      const assistantContent: Array<Record<string, unknown>> = [textBlock(`filler turn ${i}`)];
      if (opts.propagationToolName && opts.propagationInFillerIndex === i) {
        assistantContent.unshift(toolUseBlock(opts.propagationToolName, {}));
      }
      if (opts.learnSkillInFillerIndex === i) {
        assistantContent.unshift(toolUseBlock("Skill", { skill: "learn" }));
      }
      lines.push(userPromptLine(`turn ${i + 2}`), assistantLine(assistantContent));
    }
    lines.push(userPromptLine("current turn"));
    return lines;
  }

  test("fires on research-without-propagation once the trailing window elapses", () => {
    const lines = buildLines({ fillerTurns: TRAILING_WINDOW_TURNS });
    const loadedSkills = [SKILL];
    const detection = detectKnowledgeAcquisition(lines, loadedSkills, KEYWORDS, new Set());
    expect(detection).not.toBeNull();
    expect(detection?.result.matched).toBe(true);
    expect(detection?.result.detectionRung).toBe("1+2-lite");
    expect(detection?.result.matchedSkill).toBe(SKILL);
    expect(detection?.result.researchTools).toContain("WebSearch");
    expect(detection?.result.loadedSkills).toEqual([SKILL]);
    expect(detection?.result.hadPropagation).toBe(false);
  });

  test("not yet due: fewer than TRAILING_WINDOW_TURNS elapsed -> null (grace period)", () => {
    // buildLines' trailing "current turn" prompt itself counts as one elapsed
    // turn beyond the filler loop, so `fillerTurns: TRAILING_WINDOW_TURNS - 2`
    // yields elapsed = TRAILING_WINDOW_TURNS - 1 (just under the bar).
    const lines = buildLines({ fillerTurns: TRAILING_WINDOW_TURNS - 2 });
    const detection = detectKnowledgeAcquisition(lines, [SKILL], KEYWORDS, new Set());
    expect(detection).toBeNull();
  });

  test("suppressed (true negative): memory_create in the trailing window", () => {
    const lines = buildLines({
      fillerTurns: TRAILING_WINDOW_TURNS,
      propagationToolName: "mcp__minsky__memory_create",
      propagationInFillerIndex: 1,
    });
    const detection = detectKnowledgeAcquisition(lines, [SKILL], KEYWORDS, new Set());
    expect(detection).toBeNull();
  });

  test("suppressed (true negative): tasks_create in the trailing window", () => {
    const lines = buildLines({
      fillerTurns: TRAILING_WINDOW_TURNS,
      propagationToolName: "mcp__minsky__tasks_create",
      propagationInFillerIndex: 2,
    });
    const detection = detectKnowledgeAcquisition(lines, [SKILL], KEYWORDS, new Set());
    expect(detection).toBeNull();
  });

  test("suppressed (true negative): a `/learn` Skill invocation in the trailing window", () => {
    const lines = buildLines({
      fillerTurns: TRAILING_WINDOW_TURNS,
      learnSkillInFillerIndex: 0,
    });
    const detection = detectKnowledgeAcquisition(lines, [SKILL], KEYWORDS, new Set());
    expect(detection).toBeNull();
  });

  test("suppressed: no keyword overlap with any loaded skill -> null", () => {
    const lines = buildLines({
      fillerTurns: TRAILING_WINDOW_TURNS,
      researchQuery: "how does the bun test runner handle timeouts",
    });
    const detection = detectKnowledgeAcquisition(lines, [SKILL], KEYWORDS, new Set());
    expect(detection).toBeNull();
  });

  test("dedupe: an already-logged occurrence never re-fires", () => {
    const lines = buildLines({ fillerTurns: TRAILING_WINDOW_TURNS });
    // Research WebSearch tool_use is the 4th line (index 3) in buildLines' fixed prefix.
    const dedupeKey = "3:WebSearch";
    const detection = detectKnowledgeAcquisition(lines, [SKILL], KEYWORDS, new Set([dedupeKey]));
    expect(detection).toBeNull();
  });

  test("no research tool calls at all -> null", () => {
    const lines: TranscriptLine[] = [
      userPromptLine("first"),
      skillLoadLine(SKILL),
      userPromptLine("second"),
    ];
    expect(detectKnowledgeAcquisition(lines, [SKILL], KEYWORDS, new Set())).toBeNull();
  });

  test("no loaded skills -> null (rung 1's session-level filter)", () => {
    const lines = buildLines({ fillerTurns: TRAILING_WINDOW_TURNS });
    expect(detectKnowledgeAcquisition(lines, [], KEYWORDS, new Set())).toBeNull();
  });

  test("RESEARCH_TOOL_NAMES covers WebSearch, WebFetch, and the knowledge tools", () => {
    expect(RESEARCH_TOOL_NAMES).toContain("WebSearch");
    expect(RESEARCH_TOOL_NAMES).toContain("WebFetch");
    expect(RESEARCH_TOOL_NAMES).toContain("mcp__minsky__knowledge_fetch");
    expect(RESEARCH_TOOL_NAMES).toContain("mcp__minsky__knowledge_search");
  });
});

// ---------------------------------------------------------------------------
// run() (dispatcher-compatible) — silent-path + override tests (fake cwd is fine;
// these all return before any fs read happens)
// ---------------------------------------------------------------------------

describe("run() (dispatcher-compatible) — silent paths", () => {
  test("no transcript_path -> null", () => {
    const input: ClaudeHookInput = { ...FAKE_HOOK_INPUT, transcript_path: undefined };
    expect(run(input, makeCtx([]))).toBeNull();
  });

  test("empty transcriptLines -> null", () => {
    expect(run(FAKE_HOOK_INPUT, makeCtx([]))).toBeNull();
  });

  test("first turn (fewer than 2 real prompts) -> null (silent)", () => {
    const lines = [skillLoadLine(ENGINEERING_WRITING_SKILL), userPromptLine("only prompt")];
    expect(run(FAKE_HOOK_INPUT, makeCtx(lines))).toBeNull();
  });

  test("no loaded skills, even with research + enough elapsed turns -> null", () => {
    const lines: TranscriptLine[] = [
      userPromptLine("turn 1"),
      assistantLine([toolUseBlock("WebSearch", { query: "something" })]),
    ];
    for (let i = 0; i < TRAILING_WINDOW_TURNS; i++) {
      lines.push(...fillerTurn(`turn ${i + 2}`, "filler"));
    }
    lines.push(userPromptLine("current"));
    expect(run(FAKE_HOOK_INPUT, makeCtx(lines))).toBeNull();
  });

  test("override env var suppresses detection and returns an audit line", () => {
    process.env[OVERRIDE_ENV_VAR] = "1";
    try {
      const lines = [skillLoadLine(ENGINEERING_WRITING_SKILL), userPromptLine("second")];
      const outcome = run(FAKE_HOOK_INPUT, makeCtx(lines));
      expect(outcome?.calibration).toBeUndefined();
      expect(outcome?.auditLines?.[0]).toContain("OVERRIDE");
    } finally {
      delete process.env[OVERRIDE_ENV_VAR];
    }
  });

  test("INJECTION_ENABLED is false (calibration-only, v1)", () => {
    expect(INJECTION_ENABLED).toBe(false);
  });

  test("OVERRIDE_ENV_VAR exports the correct env var name", () => {
    expect(OVERRIDE_ENV_VAR).toBe("MINSKY_ACK_KNOWLEDGE_ACQUISITION");
  });
});

// ---------------------------------------------------------------------------
// run() against the REAL engineering-writing skill file on disk (mt#2708
// acceptance test: "the originating incident replayed... produces a match"
// AND the MANDATORY tool-interleaved transcript fixture — memory a3e60471:
// tool_result lines carry role "user", which silently killed three sibling
// hooks. This detector's whole signal is tool calls interleaved with text.
// ---------------------------------------------------------------------------

describe("run() against the real engineering-writing skill (mt#2708 originating-incident replay)", () => {
  // input.cwd = import.meta.dir (this file's own directory, `.minsky/hooks/`) —
  // findRepoRoot walks up from a REAL on-disk path to the real repo root, so
  // readSkillDescription reads the REAL `.claude/skills/engineering-writing/SKILL.md`.
  // A distinctive, never-reused session_id keeps the dedupe read (a real,
  // read-only fs access against `.minsky/knowledge-acquisition-calibration.jsonl`)
  // from ever colliding with a genuine prior record.
  const REAL_REPO_INPUT: ClaudeHookInput = {
    session_id: "mt2708-unittest-originating-incident-do-not-reuse",
    transcript_path: "/mock/transcript.jsonl",
    cwd: import.meta.dir,
    hook_event_name: HOOK_EVENT_NAME,
  };

  test("tool-interleaved fixture (research -> tool_result[user-role] -> assistant text -> real prompt) produces a match", () => {
    const lines: TranscriptLine[] = [
      // Turn 0: skill loaded.
      userPromptLine("please write an essay about AI writing tells"),
      skillLoadLine(ENGINEERING_WRITING_SKILL),
      // Turn 1: research call, tool_result interleaved (the mandatory shape),
      // then assistant follow-up TEXT in the SAME turn.
      userPromptLine("go ahead and research it"),
      assistantLine([
        toolUseBlock("WebSearch", {
          query: "argumentative prose AI writing tells overused phrases",
        }),
      ]),
      toolResultLine("toolu_mt2708_1", "Common AI tells: em dashes, tricolons, hedging phrases."),
      assistantLine([textBlock("Found several AI-writing tells to avoid in the essay.")]),
    ];
    // TRAILING_WINDOW_TURNS filler turns so the grace period has elapsed.
    for (let i = 0; i < TRAILING_WINDOW_TURNS; i++) {
      lines.push(...fillerTurn(`turn ${i + 3}`, `continuing the draft (${i})`));
    }
    lines.push(userPromptLine("current turn (triggers the hook)"));

    const outcome = run(REAL_REPO_INPUT, makeCtx(lines));

    expect(outcome?.calibration).toBeDefined();
    expect(outcome?.calibration?.matchedSkill).toBe(ENGINEERING_WRITING_SKILL);
    expect(outcome?.calibration?.detectionRung).toBe("1+2-lite");
    expect(outcome?.calibration?.hadPropagation).toBe(false);
    expect(Array.isArray(outcome?.calibration?.researchTools)).toBe(true);
    expect(outcome?.calibration?.researchTools).toContain("WebSearch");
    expect(outcome?.additionalContext).toBeUndefined();
  });
});
