/**
 * Unit tests for the new-pipeline agents.md compile target (mt#2992).
 *
 * Two layers: `buildContent()` pure-function tests (ported from the legacy
 * target's test suite) and `agentsMdTarget` end-to-end tests using an
 * injected fake fs + `.mdc` fixtures.
 */

import { describe, it, expect } from "bun:test";
import {
  makeAgentsMdTarget,
  buildContent,
  DEFAULT_AGENTS_MD_SIZE_BUDGET,
  DEFAULT_AGENTS_MD_SECTIONS,
} from "./agents-md";
import type { Rule } from "../../rules/types";
import type { MinskyCompileFsDeps } from "../types";

const ALWAYS_APPLY_CONTENT = "Always apply content";
const MANUAL_RULE_CONTENT = "Manual rule content";
const GLOB_RULE_CONTENT = "Glob rule content";
const PROJECT_INSTRUCTIONS_HEADER = "# Project Instructions";

function makeRule(id: string, content: string, opts: Partial<Rule> = {}): Rule {
  return {
    id,
    content,
    format: "minsky",
    path: `/fake/.minsky/rules/${id}.mdc`,
    alwaysApply: false,
    ...opts,
  };
}

describe("agents.md target (new pipeline): buildContent()", () => {
  describe("basic compilation", () => {
    it("output starts with the generation comment", () => {
      const { content } = buildContent([], {});
      expect(content).toContain(
        "<!-- Generated by minsky rules compile. Do not edit directly. -->"
      );
      expect(content.startsWith("<!-- Generated by minsky rules compile.")).toBe(true);
    });

    it("output has # Project Instructions header", () => {
      const { content } = buildContent([], {});
      expect(content).toContain(PROJECT_INSTRUCTIONS_HEADER);
    });

    it("section headers appear in order matching the mapping", () => {
      const sectionMapping = {
        "Section A": ["rule-a"],
        "Section B": ["rule-b"],
        "Section C": ["rule-c"],
      };
      const rules = [
        makeRule("rule-a", "Content of A"),
        makeRule("rule-b", "Content of B"),
        makeRule("rule-c", "Content of C"),
      ];

      const { content } = buildContent(rules, sectionMapping);

      const posA = content.indexOf("## Section A");
      const posB = content.indexOf("## Section B");
      const posC = content.indexOf("## Section C");

      expect(posA).toBeGreaterThan(-1);
      expect(posB).toBeGreaterThan(-1);
      expect(posC).toBeGreaterThan(-1);
      expect(posA).toBeLessThan(posB);
      expect(posB).toBeLessThan(posC);
    });
  });

  describe("always-apply collection into General section", () => {
    it("alwaysApply rules not in section mapping go into ## General", () => {
      const sectionMapping = { "Build & Test": ["mapped-rule"] };
      const rules = [
        makeRule("mapped-rule", "Mapped rule content"),
        makeRule("unmapped-always", ALWAYS_APPLY_CONTENT, { alwaysApply: true }),
      ];

      const { content } = buildContent(rules, sectionMapping);

      expect(content).toContain("## General");
      expect(content).toContain(ALWAYS_APPLY_CONTENT);
      expect(content.indexOf(ALWAYS_APPLY_CONTENT)).toBeGreaterThan(content.indexOf("## General"));
    });

    it("non-alwaysApply rules not in section mapping are skipped", () => {
      const sectionMapping = { "Build & Test": ["mapped-rule"] };
      const rules = [
        makeRule("mapped-rule", "Mapped rule content"),
        makeRule("unmapped-manual", MANUAL_RULE_CONTENT),
        makeRule("unmapped-glob", GLOB_RULE_CONTENT, { globs: ["**/*.ts"] }),
      ];

      const { content } = buildContent(rules, sectionMapping);

      expect(content).not.toContain("## General");
      expect(content).not.toContain(MANUAL_RULE_CONTENT);
      expect(content).not.toContain(GLOB_RULE_CONTENT);
    });
  });

  describe("missing rules handled gracefully", () => {
    it("silently skips rule IDs in mapping that do not exist", () => {
      const sectionMapping = { "Build & Test": ["existing-rule", "nonexistent-rule"] };
      const rules = [makeRule("existing-rule", "Existing content")];

      const { content } = buildContent(rules, sectionMapping);
      expect(content).toContain("Existing content");
    });

    it("section is omitted entirely if all its rules are missing", () => {
      const sectionMapping = {
        "Build & Test": ["nonexistent-1", "nonexistent-2"],
        Architecture: ["real-rule"],
      };
      const rules = [makeRule("real-rule", "Real content")];

      const { content } = buildContent(rules, sectionMapping);

      expect(content).not.toContain("## Build & Test");
      expect(content).toContain("## Architecture");
    });
  });

  describe("rulesIncluded and rulesSkipped tracking", () => {
    it("alwaysApply rules in General are NOT in rulesSkipped", () => {
      const sectionMapping: Record<string, string[]> = {};
      const rules = [
        makeRule("always-rule", "Always content", { alwaysApply: true }),
        makeRule("manual-rule", "Manual content"),
      ];

      const { rulesSkipped } = buildContent(rules, sectionMapping);

      expect(rulesSkipped).not.toContain("always-rule");
      expect(rulesSkipped).toContain("manual-rule");
    });
  });
});

describe("agents.md target (new pipeline): DEFAULT_AGENTS_MD_SIZE_BUDGET", () => {
  it("matches the legacy target's grounded defaults: warn=160000, fail=200000", () => {
    expect(DEFAULT_AGENTS_MD_SIZE_BUDGET).toEqual({ warnChars: 160_000, failChars: 200_000 });
  });

  it("fail sits strictly above warn", () => {
    expect(DEFAULT_AGENTS_MD_SIZE_BUDGET.failChars).toBeGreaterThan(
      DEFAULT_AGENTS_MD_SIZE_BUDGET.warnChars
    );
  });
});

describe("agents.md target (new pipeline): DEFAULT_AGENTS_MD_SECTIONS", () => {
  it("does not include the mt#2868-removed orphan Minsky Workflow section", () => {
    expect(DEFAULT_AGENTS_MD_SECTIONS["Minsky Workflow"]).toBeUndefined();
  });
});

// ─── Target-level (fake fs, real .mdc source parsing) ──────────────────────

type FileMap = Record<string, string>;

function makeFakeFs(files: FileMap): MinskyCompileFsDeps {
  const written: FileMap = {};
  return {
    async readFile(path: string): Promise<string> {
      // `written` takes precedence over the initial `files` fixture.
      const content = written[path] ?? files[path];
      if (content === undefined) {
        throw Object.assign(new Error(`ENOENT: ${path}`), { code: "ENOENT" });
      }
      return content;
    },
    async writeFile(path: string, data: string): Promise<void> {
      written[path] = data;
    },
    async mkdir(): Promise<undefined> {
      return undefined;
    },
    async readdir(path: string): Promise<string[]> {
      const prefix = path.endsWith("/") ? path : `${path}/`;
      const names = new Set<string>();
      for (const key of [...Object.keys(files), ...Object.keys(written)]) {
        if (key.startsWith(prefix)) {
          const rest = key.slice(prefix.length);
          const segment = rest.split("/")[0];
          if (segment !== undefined) names.add(segment);
        }
      }
      return Array.from(names);
    },
    async access(path: string): Promise<void> {
      if (files[path] === undefined && written[path] === undefined) {
        throw Object.assign(new Error(`ENOENT: ${path}`), { code: "ENOENT" });
      }
    },
    async chmod(): Promise<void> {},
  };
}

const WORKSPACE = "/workspace";

function ruleMdcPath(name: string): string {
  return `${WORKSPACE}/.minsky/rules/${name}.mdc`;
}

describe("agentsMdTarget (end-to-end via fake fs + .mdc sources)", () => {
  it("listOutputFiles returns single path at <workspace>/AGENTS.md", async () => {
    const target = makeAgentsMdTarget();
    const files = await target.listOutputFiles({}, WORKSPACE, makeFakeFs({}));
    expect(files).toEqual([`${WORKSPACE}/AGENTS.md`]);
  });

  it("respects a custom outputPath override", async () => {
    const target = makeAgentsMdTarget();
    const files = await target.listOutputFiles(
      { outputPath: "/custom/AGENTS.md" },
      WORKSPACE,
      makeFakeFs({})
    );
    expect(files).toEqual(["/custom/AGENTS.md"]);
  });

  it("maps a bun_over_node .mdc source into its Build & Test section end-to-end", async () => {
    const fakeFs = makeFakeFs({
      [ruleMdcPath("bun_over_node")]:
        "---\ndescription: Use bun\nalwaysApply: true\n---\nAlways use bun, not node.\n",
    });
    const target = makeAgentsMdTarget();

    const result = await target.compile({ dryRun: true }, WORKSPACE, fakeFs);

    expect(result.definitionsIncluded).toEqual(["bun_over_node"]);
    expect(result.content).toContain("## Build & Test");
    expect(result.content).toContain("Always use bun, not node.");
    expect((result as unknown as { sizeChars: number }).sizeChars).toBe(result.content?.length);
  });

  it("writes AGENTS.md when not a dry run", async () => {
    const fakeFs = makeFakeFs({
      [ruleMdcPath("some-rule")]:
        "---\ndescription: Some always rule\nalwaysApply: true\n---\nSome rule body.\n",
    });
    const target = makeAgentsMdTarget();

    const result = await target.compile({}, WORKSPACE, fakeFs);
    expect(result.filesWritten).toEqual([`${WORKSPACE}/AGENTS.md`]);

    const written = await fakeFs.readFile(`${WORKSPACE}/AGENTS.md`, "utf-8");
    expect(written).toContain("Some rule body.");
  });
});
