/**
 * Unit tests for the new-pipeline claude.md compile target (mt#2992).
 *
 * Two layers: `buildClaudeMdContent()` pure-function tests (ported from the
 * legacy target's test suite, operating on the same legacy-`Rule`-shaped
 * fixtures `loadAdaptedRules` produces), and `claudeMdTarget` end-to-end
 * tests using an injected fake fs + `.mdc` fixtures (mirroring the
 * `cursor-rules-ts.test.ts` pattern already established in this directory).
 */

import { describe, it, expect } from "bun:test";
import {
  makeClaudeMdTarget,
  buildClaudeMdContent,
  DEFAULT_CLAUDE_MD_SIZE_BUDGET,
} from "./claude-md";
import type { Rule } from "../../rules/types";
import type { MinskyCompileFsDeps } from "../types";

const ALWAYS_APPLY_CONTENT = "Always apply content";
const MANUAL_RULE_CONTENT = "Manual rule content";
const GLOB_RULE_CONTENT = "Glob rule content";
const PROJECT_INSTRUCTIONS_HEADER = "# Project Instructions";

/** Create a minimal legacy-shaped Rule fixture for the pure-function tests. */
function makeRule(id: string, content: string, opts: Partial<Rule> = {}): Rule {
  return {
    id,
    content,
    format: "minsky",
    path: `/fake/.minsky/rules/${id}.mdc`,
    alwaysApply: false,
    ...opts,
  };
}

describe("claude.md target (new pipeline): buildClaudeMdContent()", () => {
  describe("basic compilation", () => {
    it("output starts with the generation comment", () => {
      const { content } = buildClaudeMdContent([]);
      expect(content).toContain(
        "<!-- Generated by minsky rules compile. Do not edit directly. -->"
      );
      expect(content.startsWith("<!-- Generated by minsky rules compile.")).toBe(true);
    });

    it("output has # Project Instructions header", () => {
      const { content } = buildClaudeMdContent([]);
      expect(content).toContain(PROJECT_INSTRUCTIONS_HEADER);
    });
  });

  describe("only-alwaysApply default", () => {
    it("only includes ALWAYS_APPLY rules by default", () => {
      const rules = [
        makeRule("always-rule", ALWAYS_APPLY_CONTENT, { alwaysApply: true }),
        makeRule("manual-rule", MANUAL_RULE_CONTENT),
        makeRule("glob-rule", GLOB_RULE_CONTENT, { globs: ["**/*.ts"] }),
        makeRule("agent-rule", "Agent rule content", { description: "An agent rule" }),
      ];

      const { content, rulesIncluded, rulesSkipped } = buildClaudeMdContent(rules);

      expect(content).toContain(ALWAYS_APPLY_CONTENT);
      expect(content).not.toContain(MANUAL_RULE_CONTENT);
      expect(content).not.toContain(GLOB_RULE_CONTENT);
      expect(content).not.toContain("Agent rule content");

      expect(rulesIncluded).toContain("always-rule");
      expect(rulesSkipped).toContain("manual-rule");
      expect(rulesSkipped).toContain("glob-rule");
      expect(rulesSkipped).toContain("agent-rule");
    });

    it("includes multiple alwaysApply rules", () => {
      const rules = [
        makeRule("always-1", "Always content 1", { alwaysApply: true }),
        makeRule("always-2", "Always content 2", { alwaysApply: true }),
        makeRule("manual-rule", "Manual content"),
      ];

      const { content, rulesIncluded, rulesSkipped } = buildClaudeMdContent(rules);

      expect(content).toContain("Always content 1");
      expect(content).toContain("Always content 2");
      expect(content).not.toContain("Manual content");

      expect(rulesIncluded).toContain("always-1");
      expect(rulesIncluded).toContain("always-2");
      expect(rulesSkipped).toContain("manual-rule");
    });

    it("returns empty rulesIncluded when no alwaysApply rules exist", () => {
      const rules = [
        makeRule("manual-rule", MANUAL_RULE_CONTENT),
        makeRule("glob-rule", GLOB_RULE_CONTENT, { globs: ["**/*.ts"] }),
      ];

      const { rulesIncluded, rulesSkipped } = buildClaudeMdContent(rules);

      expect(rulesIncluded).toHaveLength(0);
      expect(rulesSkipped).toContain("manual-rule");
      expect(rulesSkipped).toContain("glob-rule");
    });

    it("returns empty arrays for empty input", () => {
      const { rulesIncluded, rulesSkipped } = buildClaudeMdContent([]);

      expect(rulesIncluded).toHaveLength(0);
      expect(rulesSkipped).toHaveLength(0);
    });
  });

  describe("output format", () => {
    it("always-apply rules appear directly in the output without section headers", () => {
      const rules = [makeRule("always-rule", ALWAYS_APPLY_CONTENT, { alwaysApply: true })];

      const { content } = buildClaudeMdContent(rules);

      const lines = content.split("\n");
      const sectionHeaders = lines.filter((l) => l.startsWith("## "));
      expect(sectionHeaders).toHaveLength(0);
    });
  });

  describe("ordering (spec ## Ordering — alphabetical, not insertion order)", () => {
    it("preserves the input array order (the caller — loadAdaptedRules — is responsible for sorting)", () => {
      const rules = [
        makeRule("zebra", "Zebra content", { alwaysApply: true }),
        makeRule("alpha", "Alpha content", { alwaysApply: true }),
      ];
      const { content } = buildClaudeMdContent(rules);
      expect(content.indexOf("Zebra content")).toBeLessThan(content.indexOf("Alpha content"));
    });
  });

  describe("memory-usage rule filtering (memoryLoadingMode)", () => {
    const MEMORY_DIRECTIVE = "Memory is stored in Minsky DB, not files. Use `memory_search`";

    const memoryUsageRule = makeRule(
      "memory-usage",
      `${MEMORY_DIRECTIVE} with a query matching the user's intent at the start of any non-trivial conversation.`,
      { alwaysApply: true, tags: ["memory"] }
    );

    const otherAlwaysRule = makeRule("other-always", ALWAYS_APPLY_CONTENT, { alwaysApply: true });

    it("includes memory-usage rule by default (no mode arg)", () => {
      const { content, rulesIncluded, rulesSkipped } = buildClaudeMdContent([memoryUsageRule]);

      expect(content).toContain(MEMORY_DIRECTIVE);
      expect(rulesIncluded).toContain("memory-usage");
      expect(rulesSkipped).not.toContain("memory-usage");
    });

    it("includes memory-usage rule in on_demand mode", () => {
      const { content, rulesIncluded, rulesSkipped } = buildClaudeMdContent(
        [memoryUsageRule, otherAlwaysRule],
        "on_demand"
      );

      expect(content).toContain(MEMORY_DIRECTIVE);
      expect(rulesIncluded).toContain("memory-usage");
      expect(rulesSkipped).not.toContain("memory-usage");
    });

    it("suppresses memory-usage rule in legacy mode", () => {
      const { content, rulesIncluded, rulesSkipped } = buildClaudeMdContent(
        [memoryUsageRule, otherAlwaysRule],
        "legacy"
      );

      expect(content).not.toContain(MEMORY_DIRECTIVE);
      expect(rulesIncluded).not.toContain("memory-usage");
      expect(rulesSkipped).toContain("memory-usage");
    });

    it("legacy mode still includes other always-apply rules", () => {
      const { content, rulesIncluded } = buildClaudeMdContent(
        [memoryUsageRule, otherAlwaysRule],
        "legacy"
      );

      expect(content).toContain(ALWAYS_APPLY_CONTENT);
      expect(rulesIncluded).toContain("other-always");
    });
  });
});

describe("claude.md target (new pipeline): DEFAULT_CLAUDE_MD_SIZE_BUDGET", () => {
  it("matches the legacy target's grounded defaults: warn=135000, fail=145000 (mt#3075)", () => {
    // Both pipelines import this constant from the SAME shared module
    // (`../claude-md-size-budget.ts`) as of mt#3075 — before that fix, this
    // dormant target carried its own stale copy (115_000/140_000) that had
    // drifted from the legacy pipeline's mt#3052/mt#3061 update. This test
    // pins parity going forward; a future divergence would fail it.
    expect(DEFAULT_CLAUDE_MD_SIZE_BUDGET).toEqual({ warnChars: 135_000, failChars: 145_000 });
  });

  it("fail sits strictly above warn", () => {
    expect(DEFAULT_CLAUDE_MD_SIZE_BUDGET.failChars).toBeGreaterThan(
      DEFAULT_CLAUDE_MD_SIZE_BUDGET.warnChars
    );
  });
});

// ─── Target-level (fake fs, real .mdc source parsing) ──────────────────────

type FileMap = Record<string, string>;

function makeFakeFs(files: FileMap): MinskyCompileFsDeps {
  const written: FileMap = {};
  const deleted = new Set<string>();

  return {
    async readFile(path: string): Promise<string> {
      if (deleted.has(path)) throw Object.assign(new Error(`ENOENT: ${path}`), { code: "ENOENT" });
      // `written` takes precedence over the initial `files` fixture.
      const content = written[path] ?? files[path];
      if (content === undefined) {
        throw Object.assign(new Error(`ENOENT: ${path}`), { code: "ENOENT" });
      }
      return content;
    },
    async writeFile(path: string, data: string): Promise<void> {
      written[path] = data;
      deleted.delete(path);
    },
    async mkdir(): Promise<undefined> {
      return undefined;
    },
    async readdir(path: string): Promise<string[]> {
      const prefix = path.endsWith("/") ? path : `${path}/`;
      const names = new Set<string>();
      for (const key of [...Object.keys(files), ...Object.keys(written)]) {
        if (deleted.has(key)) continue;
        if (key.startsWith(prefix)) {
          const rest = key.slice(prefix.length);
          const segment = rest.split("/")[0];
          if (segment !== undefined) names.add(segment);
        }
      }
      return Array.from(names);
    },
    async access(path: string): Promise<void> {
      if (deleted.has(path) || (files[path] === undefined && written[path] === undefined)) {
        throw Object.assign(new Error(`ENOENT: ${path}`), { code: "ENOENT" });
      }
    },
    async chmod(): Promise<void> {},
    async unlink(path: string): Promise<void> {
      deleted.add(path);
    },
  };
}

const WORKSPACE = "/workspace";

function ruleMdcPath(name: string): string {
  return `${WORKSPACE}/.minsky/rules/${name}.mdc`;
}

describe("claudeMdTarget (end-to-end via fake fs + .mdc sources)", () => {
  it("listOutputFiles returns single path at <workspace>/CLAUDE.md", async () => {
    const target = makeClaudeMdTarget();
    const files = await target.listOutputFiles({}, WORKSPACE, makeFakeFs({}));
    expect(files).toEqual([`${WORKSPACE}/CLAUDE.md`]);
  });

  it("compiles always-apply .mdc sources into CLAUDE.md content and reports size budget", async () => {
    const fakeFs = makeFakeFs({
      [ruleMdcPath("always-rule")]:
        "---\ndescription: An always rule\nalwaysApply: true\n---\nAlways rule body.\n",
      [ruleMdcPath("manual-rule")]: "---\ndescription: A manual rule\n---\nManual rule body.\n",
    });
    const target = makeClaudeMdTarget();

    const result = await target.compile({ dryRun: true }, WORKSPACE, fakeFs);

    expect(result.definitionsIncluded).toEqual(["always-rule"]);
    expect(result.definitionsSkipped).toEqual(["manual-rule"]);
    expect(result.content).toContain("Always rule body.");
    expect(result.content).not.toContain("Manual rule body.");
    expect((result as unknown as { sizeChars: number }).sizeChars).toBe(result.content?.length);
    expect((result as unknown as { sizeBudgetStatus: string }).sizeBudgetStatus).toBe("ok");
  });

  it("writes CLAUDE.md when not a dry run", async () => {
    const fakeFs = makeFakeFs({
      [ruleMdcPath("always-rule")]:
        "---\ndescription: An always rule\nalwaysApply: true\n---\nAlways rule body.\n",
    });
    const target = makeClaudeMdTarget();

    const result = await target.compile({}, WORKSPACE, fakeFs);
    expect(result.filesWritten).toEqual([`${WORKSPACE}/CLAUDE.md`]);
    expect(result.content).toBeUndefined();

    const written = await fakeFs.readFile(`${WORKSPACE}/CLAUDE.md`, "utf-8");
    expect(written).toContain("Always rule body.");
  });

  it("suppresses memory-usage under legacy memoryLoadingMode end-to-end", async () => {
    const fakeFs = makeFakeFs({
      [ruleMdcPath("memory-usage")]:
        "---\ndescription: Memory usage rule\nalwaysApply: true\ntags:\n  - memory\n---\nMemory directive body.\n",
    });
    const target = makeClaudeMdTarget();

    const result = await target.compile(
      { dryRun: true, memoryLoadingMode: "legacy" },
      WORKSPACE,
      fakeFs
    );

    expect(result.definitionsIncluded).toEqual([]);
    expect(result.definitionsSkipped).toEqual(["memory-usage"]);
    expect(result.content).not.toContain("Memory directive body.");
  });

  it("HARD-FAILS via perRuleViolations when a synthetic rule exceeds the per-rule ceiling", async () => {
    const fakeFs = makeFakeFs({
      [ruleMdcPath("over-ceiling")]:
        `---\ndescription: An oversized always rule\nalwaysApply: true\n---\n${"x".repeat(15_001)}\n`,
    });
    const target = makeClaudeMdTarget();

    const result = await target.compile({ dryRun: true, check: true }, WORKSPACE, fakeFs);
    const withBudget = result as unknown as {
      perRuleViolations: Array<{ id: string; size: number }>;
    };
    expect(withBudget.perRuleViolations).toHaveLength(1);
    expect(withBudget.perRuleViolations[0]?.id).toBe("over-ceiling");
  });
});
