/**
 * CLAUDE.md Compile Target (new pipeline — mt#2992, Phase 1 of ADR-016
 * convergence)
 *
 * Ports the legacy `claude.md` target's content-assembly logic
 * (`packages/domain/src/rules/compile/targets/claude-md.ts`) onto the new
 * `compile` pipeline's rule source: `discoverRuleSources` /
 * `extractRuleDefinitionFromMdc` (`../rule-sources.ts`) via the shared
 * `loadAdaptedRules` loader (`./rule-loader.ts`), rather than the legacy
 * `RuleService`.
 *
 * **This target lands DORMANT** (mt#2992 spec) — registered in
 * `createMinskyCompileService()` and reachable only via explicit
 * `compile --target claude.md`. It is NOT added to
 * `minskyCompileTargetsFromPresence` or `compileCheckTargets` in this task;
 * legacy remains the authoritative CLAUDE.md writer until the cutover task
 * (mt#3058) flips them atomically.
 *
 * By default, only includes ALWAYS_APPLY rules. The `memory-usage` rule
 * (id: "memory-usage", tag: "memory") is always-apply by default, but is
 * suppressed when `memoryLoadingMode` is `"legacy"`, allowing a
 * soft-transition window where operators can fall back to MEMORY.md
 * preamble loading.
 *
 * **Ordering (spec `## Ordering`):** rules are embedded in the order
 * `loadAdaptedRules` returns them — the same alphabetical-by-source-name
 * order `discoverRuleSources` already sorts by. This is a DELIBERATE
 * divergence from legacy, which appends in unstable `readdir` order — see
 * the mt#2992 spec's `## Ordering` section for the full rationale.
 *
 * **Generation banner is NOT changed** (spec `## Scope`) — the literal HTML
 * comment below matches the legacy writer exactly, since
 * `check-generated-file-edit.ts` and both bare-invocation staleness probes
 * key off it. Duplicated as a literal here (not imported from the legacy
 * `rules/compile/targets/claude-md.ts`, which mt#2996 deletes) — the same
 * precedent `claude-rules.ts`'s `CLAUDE_RULES_BANNER` already establishes
 * for a banner shared across systems mid-migration.
 */

import { join } from "path";
import realFs from "fs/promises";
import { classifyRuleType, RuleType } from "../../rules/rule-classifier";
import type { Rule } from "../../rules/types";
import type { MinskyCompileTarget, MinskyTargetOptions, MinskyCompileFsDeps } from "../types";
import {
  evaluateSizeBudget,
  DEFAULT_PER_RULE_CEILING_CHARS,
  type SizeBudget,
} from "../size-budget";
import type { MinskyMonolithicCompileResult } from "../size-budget-report";
import { loadAdaptedRules, type SkipLogFn, type DynamicImportFn } from "./rule-loader";

/** The canonical rule ID for the memory-usage directive. */
const MEMORY_USAGE_RULE_ID = "memory-usage";

/** Matches the legacy `rules/compile/targets/claude-md.ts` banner exactly (see module doc). */
const CLAUDE_MD_BANNER = "<!-- Generated by minsky rules compile. Do not edit directly. -->";

/**
 * Default size budget for CLAUDE.md (mt#2802, ported unchanged in mt#2992).
 * Grounded in the 2026-07-15 planning calibration — see the legacy target's
 * identical constant for the full rationale.
 */
export const DEFAULT_CLAUDE_MD_SIZE_BUDGET: SizeBudget = {
  warnChars: 115_000,
  failChars: 140_000,
};

function claudeMdOutputPath(workspacePath: string): string {
  return join(workspacePath, "CLAUDE.md");
}

/**
 * Build CLAUDE.md content from always-apply rules. Ports
 * `buildClaudeMdContent` from the legacy target 1:1 in behavior, operating
 * on the legacy-shaped `Rule[]` `loadAdaptedRules` produces.
 */
export function buildClaudeMdContent(
  allRules: Rule[],
  memoryLoadingMode: MinskyTargetOptions["memoryLoadingMode"] = "on_demand"
): {
  content: string;
  rulesIncluded: string[];
  rulesSkipped: string[];
} {
  const rulesIncluded: string[] = [];
  const rulesSkipped: string[] = [];

  const alwaysApplyRules: Rule[] = [];
  for (const rule of allRules) {
    const ruleType = classifyRuleType(rule);
    if (ruleType === RuleType.ALWAYS_APPLY) {
      if (memoryLoadingMode === "legacy" && rule.id === MEMORY_USAGE_RULE_ID) {
        rulesSkipped.push(rule.id);
        continue;
      }
      alwaysApplyRules.push(rule);
      rulesIncluded.push(rule.id);
    } else {
      rulesSkipped.push(rule.id);
    }
  }

  const lines: string[] = [];
  lines.push(CLAUDE_MD_BANNER);
  lines.push("");
  lines.push("# Project Instructions");
  lines.push("");

  for (const rule of alwaysApplyRules) {
    const content = rule.content.trim();
    if (content) {
      lines.push(content);
      lines.push("");
    }
  }

  return { content: lines.join("\n"), rulesIncluded, rulesSkipped };
}

/** Build the claude.md target, injecting fs/dynamicImport/skip-log for tests. */
function makeClaudeMdTarget(
  dynamicImport?: DynamicImportFn,
  onSkip?: SkipLogFn
): MinskyCompileTarget {
  return {
    id: "claude.md",
    displayName: "CLAUDE.md",

    defaultOutputPath(workspacePath: string): string {
      return claudeMdOutputPath(workspacePath);
    },

    async listOutputFiles(
      options: MinskyTargetOptions,
      workspacePath: string,
      _fsDeps?: MinskyCompileFsDeps
    ): Promise<string[]> {
      return [options.outputPath || claudeMdOutputPath(workspacePath)];
    },

    async compile(
      options: MinskyTargetOptions,
      workspacePath: string,
      fsDeps?: MinskyCompileFsDeps
    ): Promise<MinskyMonolithicCompileResult> {
      const fs = fsDeps ?? (realFs as MinskyCompileFsDeps);
      const rules = await loadAdaptedRules(workspacePath, fs, onSkip, dynamicImport);

      const { content, rulesIncluded, rulesSkipped } = buildClaudeMdContent(
        rules,
        options.memoryLoadingMode
      );

      // Evaluate BEFORE writing so the reported evaluation always describes
      // the exact content string being emitted (mirrors legacy R1 fix).
      const sizeEvaluation = evaluateSizeBudget({
        sizeChars: content.length,
        rules,
        includedIds: rulesIncluded,
        defaultBudget: DEFAULT_CLAUDE_MD_SIZE_BUDGET,
        override: options.sizeBudget,
        // mt#2874: per-rule 15K ceiling — claude.md only, per the spec's scope.
        perRuleCeiling: DEFAULT_PER_RULE_CEILING_CHARS,
      });

      const outputPath = options.outputPath || claudeMdOutputPath(workspacePath);
      const contentsByPath = new Map<string, string>([[outputPath, content]]);

      if (options.dryRun) {
        // no write
      } else {
        await fs.writeFile(outputPath, content, "utf-8");
      }

      return {
        target: "claude.md",
        filesWritten: [outputPath],
        definitionsIncluded: rulesIncluded,
        definitionsSkipped: rulesSkipped,
        content: options.dryRun ? content : undefined,
        contentsByPath: options.dryRun ? contentsByPath : undefined,
        sizeChars: sizeEvaluation.sizeChars,
        sizeBudget: sizeEvaluation.budget,
        sizeBudgetStatus: sizeEvaluation.status,
        topContributors: sizeEvaluation.topContributors,
        ruleContentChars: sizeEvaluation.ruleContentChars,
        perRuleViolations: sizeEvaluation.perRuleViolations,
      };
    },
  };
}

export const claudeMdTarget = makeClaudeMdTarget();

/** Export factory for test injection */
export { makeClaudeMdTarget };
