/**
 * Codex compile targets (mt#3854)
 *
 * Two things are under test, and they carry different risk.
 *
 * The HOOKS target is a construction over `hook-copy-target`, whose behaviour
 * is already covered by `claude-hooks.test.ts`; what is worth asserting here is
 * that it is wired to the right directory and identity, because a wrong output
 * path would quietly write a second copy of the corpus somewhere nobody reads.
 *
 * The TOML emitter is the only genuinely new logic in this task, and its
 * failure mode is silent corruption rather than a crash: a mis-escaped prompt
 * still writes a file, still parses in the common case, and only differs from
 * the source in the middle of a 40KB body. So it is tested against the TOML
 * v1.0.0 string rules, not against the three values that happen to exist today.
 */
import { describe, it, expect } from "bun:test";
import { GENERATION_BANNER_PATTERNS } from "../../rules/compile/banner-constants";
import { minskyCompileTargetsFromPresence } from "../compile";
import { makeCodexHooksTarget } from "./codex-hooks";
import {
  makeCodexAgentsTarget,
  buildAgentToml,
  escapeTomlBasicString,
  escapeTomlMultilineString,
} from "./codex-agents";
import type { MinskyCompileFsDeps } from "../types";
import type { AgentDefinition } from "../../definitions/types";

// ─── Fake fs ─────────────────────────────────────────────────────────────────

type FileMap = Record<string, string>;

function makeFakeFs(files: FileMap): MinskyCompileFsDeps & { written: FileMap } {
  const written: FileMap = {};
  return {
    written,
    async readFile(path: string): Promise<string> {
      const content = files[path];
      if (content === undefined) throw new Error(`ENOENT: ${path}`);
      return content;
    },
    async writeFile(path: string, data: string): Promise<void> {
      written[path] = data;
    },
    async mkdir(): Promise<string | undefined> {
      return undefined;
    },
    async readdir(path: string): Promise<string[]> {
      const prefix = `${path}/`;
      const names = new Set<string>();
      for (const key of Object.keys(files)) {
        if (!key.startsWith(prefix)) continue;
        const rest = key.slice(prefix.length);
        const head = rest.split("/")[0];
        if (head !== undefined && head.length > 0) names.add(head);
      }
      return [...names];
    },
    async access(path: string): Promise<void> {
      const isFile = files[path] !== undefined;
      const isDir = Object.keys(files).some((k) => k.startsWith(`${path}/`));
      if (!isFile && !isDir) throw new Error(`ENOENT: ${path}`);
    },
    async chmod(): Promise<void> {
      /* recorded by the claude-hooks suite; not asserted here */
    },
  };
}

// ─── codex-hooks ─────────────────────────────────────────────────────────────

describe("codexHooksTarget — identity and output location", () => {
  const target = makeCodexHooksTarget();

  it("has id 'codex-hooks' and a Codex display name", () => {
    expect(target.id).toBe("codex-hooks");
    expect(target.displayName).toBe("Codex Hooks");
  });

  it("writes to .codex/hooks, NOT .claude/hooks", () => {
    const out = target.defaultOutputPath("/ws");
    expect(out).toBe("/ws/.codex/hooks");
    // The failure this guards: constructing the shared factory with the Claude
    // segments would pass every other assertion in this file while silently
    // making the two targets write to the same directory.
    expect(out).not.toContain(".claude");
  });

  it("owns its output directory exclusively, so --check reports orphans", () => {
    // Contrast with claude-agents, which is shared with hand-authored files.
    // A leftover in .codex/hooks must be a build failure, not a fossil — that
    // is the whole point of mt#3854.
    expect(target.sharedOutputDirectory).toBe(false);
  });

  it("compiles a hook source into .codex/hooks with the generation banner", async () => {
    const fs = makeFakeFs({
      "/ws/.minsky/hooks/example-guard.ts": "export function run() {}\n",
    });

    const result = await target.compile({}, "/ws", fs);

    expect(result.target).toBe("codex-hooks");
    expect(result.definitionsIncluded).toEqual(["example-guard.ts"]);
    const written = fs.written["/ws/.codex/hooks/example-guard.ts"];
    expect(written).toBeDefined();
    expect(written).toContain("#!/usr/bin/env bun");
    expect(written).toContain("// Generated by minsky compile. Do not edit directly.");
    // Provenance names the SOURCE, which is shared across harnesses.
    expect(written).toContain("// Source: .minsky/hooks/example-guard.ts");
    expect(written).toContain("export function run() {}");
  });
});

// ─── Bare-invocation gating (SC3) ────────────────────────────────────────────

describe("minskyCompileTargetsFromPresence — Codex is opt-in", () => {
  const allSourcesPresent = { skills: true, rules: true, agents: true, hooks: true };

  it("does NOT emit codex targets when .codex/ is absent", () => {
    // The criterion this protects, verbatim from mt#3854 SC3: a bare compile
    // "does NOT create `.codex/` on a machine that has never had it." Gating on
    // the .minsky sources instead would create a harness config on every clone
    // in the fleet, because those sources are always present.
    const targets = minskyCompileTargetsFromPresence({ ...allSourcesPresent, codex: false });
    expect(targets).not.toContain("codex-hooks");
    expect(targets).not.toContain("codex-agents");
    // The Claude targets are unaffected — this is an addition, not a swap.
    expect(targets).toContain("claude-hooks");
    expect(targets).toContain("claude-agents");
  });

  it("emits both codex targets once .codex/ exists", () => {
    const targets = minskyCompileTargetsFromPresence({ ...allSourcesPresent, codex: true });
    expect(targets).toContain("codex-hooks");
    expect(targets).toContain("codex-agents");
  });

  it("still requires the matching source tree for each codex target", () => {
    // .codex/ present but no hook sources: emitting codex-hooks would write an
    // empty directory and then, with orphan detection on, report every existing
    // file there as stale.
    const noHooks = minskyCompileTargetsFromPresence({
      skills: true,
      rules: true,
      agents: true,
      hooks: false,
      codex: true,
    });
    expect(noHooks).not.toContain("codex-hooks");
    expect(noHooks).toContain("codex-agents");

    const noAgents = minskyCompileTargetsFromPresence({
      skills: true,
      rules: true,
      agents: false,
      hooks: true,
      codex: true,
    });
    expect(noAgents).toContain("codex-hooks");
    expect(noAgents).not.toContain("codex-agents");
  });
});

// ─── TOML escaping ───────────────────────────────────────────────────────────

describe("escapeTomlBasicString", () => {
  it("escapes backslash before quote, so quote-escapes are not double-escaped", () => {
    // Order matters: escaping `"` first would turn `\"` into `\\"` on the
    // backslash pass, producing an escaped backslash followed by a RAW quote —
    // which terminates the string early.
    expect(escapeTomlBasicString('a\\b"c')).toBe('a\\\\b\\"c');
  });

  it("escapes newlines, which a basic string may not contain raw", () => {
    expect(escapeTomlBasicString("line1\nline2")).toBe("line1\\nline2");
  });

  it("escapes other control characters as \\uXXXX", () => {
    // A source-level escape, so a REAL control character reaches the escaper at
    // runtime without a literal byte living in this file — a literal one makes
    // the source read as binary to grep and trips no-control-regex.
    expect(escapeTomlBasicString("a\u0007b")).toBe("a\\u0007b");
  });

  it("leaves ordinary prose untouched", () => {
    const plain = "Ad-hoc spec verification when explicitly requested";
    expect(escapeTomlBasicString(plain)).toBe(plain);
  });
});

describe("escapeTomlMultilineString", () => {
  it("keeps newlines and single quotes raw — the reason multi-line is used", () => {
    const body = 'Read the "spec" first.\n\nThen verify.';
    expect(escapeTomlMultilineString(body)).toBe(body);
  });

  it("escapes backslashes, which TOML reads as escape introducers here too", () => {
    // Real case: agent prompts in this repo contain regexes.
    expect(escapeTomlMultilineString("match \\bfoo\\b")).toBe("match \\\\bfoo\\\\b");
  });

  it("breaks a run of three quotes so it cannot close the string early", () => {
    const escaped = escapeTomlMultilineString('before """ after');
    expect(escaped).toBe('before \\""" after');
    // The delimiter sequence no longer appears unescaped.
    expect(escaped).not.toMatch(/(^|[^\\])"""/);
  });

  it("escapes a trailing quote that would fuse with the closing delimiter", () => {
    // `...\"` + `"""` would read as four quotes and end the string one char early.
    expect(escapeTomlMultilineString('ends with a quote"')).toBe('ends with a quote\\"');
  });

  it("negative control: an unescaped body WOULD contain the delimiter", () => {
    // Proves the assertion above can fail — without this, a no-op escaper
    // would pass the previous test for the wrong reason.
    const raw = 'before """ after';
    expect(raw).toMatch(/(^|[^\\])"""/);
  });
});

// ─── codex-agents ────────────────────────────────────────────────────────────

/** The TOML key carrying the prompt body — repeated across assertions below. */
const DEV_INSTRUCTIONS = "developer_instructions";

function makeAgent(overrides: Partial<AgentDefinition> = {}): AgentDefinition {
  return {
    name: "auditor",
    description: "Verifies a task's criteria.",
    prompt: "# Auditor\n\nYou verify completion.",
    ...overrides,
  } as AgentDefinition;
}

describe("buildAgentToml", () => {
  it("emits name, description and developer_instructions", () => {
    const toml = buildAgentToml(makeAgent());
    expect(toml).toContain('name = "auditor"');
    expect(toml).toContain('description = "Verifies a task\'s criteria."');
    expect(toml).toContain(`${DEV_INSTRUCTIONS} = """`);
    expect(toml).toContain("You verify completion.");
    expect(toml.trimEnd().endsWith('"""')).toBe(true);
  });

  it("carries a banner the generated-file guard actually recognises (SC6)", () => {
    const toml = buildAgentToml(makeAgent());
    // Not "contains the word Generated" — asserted against the guard's OWN
    // pattern list, so a banner the guard cannot see fails here. Presence of a
    // banner and recognition of a banner are different claims, and only the
    // second one denies a hand-edit.
    const matched = GENERATION_BANNER_PATTERNS.some(({ re }) => re.test(toml));
    expect(matched).toBe(true);
  });

  it("negative control: a TOML body with no banner is NOT recognised", () => {
    // Proves the assertion above can fail. Without it, a pattern list that
    // matched anything would pass the previous test for the wrong reason.
    const unbannered = 'name = "auditor"\ndescription = "x"\n';
    expect(GENERATION_BANNER_PATTERNS.some(({ re }) => re.test(unbannered))).toBe(false);
  });

  it("strips exactly one leading newline from the prompt body", () => {
    // AgentDefinition prompts are authored both ways; the Claude target
    // normalises by ADDING one, so this target must not inherit a stray blank
    // first line from the same source.
    // Asserted through the parser rather than against the literal bytes: what
    // matters is the VALUE Codex ends up with, and pinning the byte layout
    // would have made this test fail for the delimiter change that fixed the
    // round-trip — a correct change breaking a test that was checking the
    // wrong thing.
    const parsedFromPadded = Bun.TOML.parse(
      buildAgentToml(makeAgent({ prompt: "\n# Auditor" }))
    ) as Record<string, unknown>;
    const parsedFromBare = Bun.TOML.parse(
      buildAgentToml(makeAgent({ prompt: "# Auditor" }))
    ) as Record<string, unknown>;

    expect(parsedFromPadded[DEV_INSTRUCTIONS]).toBe("# Auditor");
    // Both authoring styles converge on the same value.
    expect(parsedFromBare[DEV_INSTRUCTIONS]).toBe("# Auditor");
  });

  it("round-trips through a TOML parser with the body intact", () => {
    // The strongest available check: Bun ships a TOML parser (parse-only), so
    // the emitter's output is validated by something other than itself.
    const prompt = 'Use \\bregex\\b and "quotes" and even """ runs.\nSecond line.';
    const toml = buildAgentToml(makeAgent({ prompt }));
    const parsed = Bun.TOML.parse(toml) as Record<string, unknown>;
    expect(parsed["name"]).toBe("auditor");
    expect(parsed[DEV_INSTRUCTIONS]).toBe(prompt);
  });
});

describe("codexAgentsTarget — identity and output location", () => {
  const target = makeCodexAgentsTarget();

  it("has id 'codex-agents' and writes .toml under .codex/agents", () => {
    expect(target.id).toBe("codex-agents");
    expect(target.defaultOutputPath("/ws")).toBe("/ws/.codex/agents");
  });

  it("owns its output directory exclusively, unlike .claude/agents", () => {
    expect(target.sharedOutputDirectory).toBe(false);
  });

  it("compiles a definition to <name>.toml", async () => {
    const agent = makeAgent();
    const fs = makeFakeFs({ "/ws/.minsky/agents/auditor/agent.ts": "" });
    const target = makeCodexAgentsTarget(async () => ({ default: agent }));

    const result = await target.compile({}, "/ws", fs);

    expect(result.definitionsIncluded).toEqual(["auditor"]);
    expect(result.filesWritten).toEqual(["/ws/.codex/agents/auditor.toml"]);
    expect(fs.written["/ws/.codex/agents/auditor.toml"]).toContain('name = "auditor"');
  });

  it("skips a definition whose name disagrees with its directory", async () => {
    // Same invariant the Claude target enforces: listOutputFiles only sees
    // dirNames, so a mismatch would make --check permanently stale.
    const fs = makeFakeFs({ "/ws/.minsky/agents/auditor/agent.ts": "" });
    const target = makeCodexAgentsTarget(async () => ({ default: makeAgent({ name: "other" }) }));

    const result = await target.compile({}, "/ws", fs);

    expect(result.definitionsIncluded).toEqual([]);
    expect(result.definitionsSkipped).toEqual(["auditor"]);
  });
});
